// Code generated by wireforge. DO NOT EDIT.
//
// This file contains type-safe message definitions with binary serialization
// for a length-prefixed wire protocol. All multi-byte integers are encoded in
// Big-Endian (network byte order) to ensure cross-platform compatibility.
//
// Wire Protocol Layout (per message):
//
//	[Message Type ID : 2 bytes, Big-Endian uint16]
//	[Fixed Header Length : 2 bytes, Big-Endian uint16]
//	[Fixed Header Block : N bytes, padded for natural alignment]
//	[Dynamic Payload : variable length, concatenated string/byte data]
//
// Safety guarantees:
//   - MaxAllowedPacket (16 MB) prevents memory allocation exploits from
//     corrupted length fields ("poison pill" attack mitigation).
//   - init() performs compile-time layout validation via unsafe.Sizeof to
//     catch struct size mismatches between the generator and the Go compiler.
//   - All reads use io.ReadFull to handle socket short-reads correctly.
//   - Big-Endian encoding ensures consistent behavior across architectures.
package messages

import (
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"unsafe"
)

const (
	// FrameHeaderSize represents the 2 bytes for TypeID and 2 bytes for FixedHeaderLen.
	FrameHeaderSize = 4

	// MaxAllowedPacket is the hard ceiling on any single message size (16 MB).
	// Any incoming length field exceeding this value is treated as corrupted
	// data and rejected immediately, preventing denial-of-service via
	// malicious allocation requests.
	MaxAllowedPacket = 16 * 1024 * 1024
)

// Compile-time import usage guarantees.
var (
	_ = binary.BigEndian
	_ = fmt.Errorf
	_ = io.ReadFull
	_ = math.Float32frombits
	_ = unsafe.Sizeof(uint8(0))
)

// ---------------------------------------------------------------------------
// UserMessage
// ---------------------------------------------------------------------------
// Wire Type ID: 1
// Fixed Header: 16 bytes (includes alignment padding)
// ---------------------------------------------------------------------------

// UserMessage represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type UserMessage struct {
	Timestamp int64
	Content string
	Attachment []byte
}

// UserMessageFixedSize is the byte size of the fixed header portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const UserMessageFixedSize = 16

// MessageTypeID returns the unique wire protocol type identifier for UserMessage.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (u *UserMessage) MessageTypeID() uint16 {
	return 1
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg UserMessage
	_ = msg
	if unsafe.Sizeof(msg.Timestamp) != 8 {
		panic("wireforge: UserMessage.Timestamp size mismatch")
	}
}

// Marshal serializes the UserMessage message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (1)
//	[2:4]     Fixed Header Length (16)
//	[4:20]    Fixed header (primitives + length prefixes, Big-Endian)
//	[20:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (u *UserMessage) Marshal() ([]byte, error) {
	dynamicSize := 0
	dynamicSize += len(u.Content)
	dynamicSize += len(u.Attachment)

	totalSize := FrameHeaderSize + UserMessageFixedSize + dynamicSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("UserMessage message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed header length
	binary.BigEndian.PutUint16(buf[0:2], 1)
	binary.BigEndian.PutUint16(buf[2:4], uint16(UserMessageFixedSize))

	// Fixed header block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + UserMessageFixedSize


	binary.BigEndian.PutUint64(hdr[0:8], uint64(u.Timestamp))
	binary.BigEndian.PutUint32(hdr[8:12], uint32(len(u.Content)))
	copy(buf[dynOff:], u.Content)
	dynOff += len(u.Content)
	binary.BigEndian.PutUint32(hdr[12:16], uint32(len(u.Attachment)))
	copy(buf[dynOff:], u.Attachment)
	dynOff += len(u.Attachment)

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a UserMessage from the wire after the 4-byte frame
// header has already been consumed. The caller provides fixedHeaderLen (read
// from the frame) so forward-compatible readers can skip unknown trailing
// bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (u *UserMessage) Unmarshal(reader io.Reader, fixedHeaderLen uint16) error {
	if int(fixedHeaderLen) < UserMessageFixedSize {
		return fmt.Errorf("UserMessage fixed header too short: got %d, need %d", fixedHeaderLen, UserMessageFixedSize)
	}

	hdr := make([]byte, fixedHeaderLen)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading UserMessage fixed header: %w", err)
	}


	u.Timestamp = int64(binary.BigEndian.Uint64(hdr[0:8]))
	u_Content_len := binary.BigEndian.Uint32(hdr[8:12])
	if u_Content_len > MaxAllowedPacket {
		return fmt.Errorf("UserMessage.Content length %d exceeds MaxAllowedPacket", u_Content_len)
	}
	u_Attachment_len := binary.BigEndian.Uint32(hdr[12:16])
	if u_Attachment_len > MaxAllowedPacket {
		return fmt.Errorf("UserMessage.Attachment length %d exceeds MaxAllowedPacket", u_Attachment_len)
	}

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed header in the same order as their length prefixes above.
	if u_Content_len > 0 {
		u_Content_buf := make([]byte, u_Content_len)
		if _, err := io.ReadFull(reader, u_Content_buf); err != nil {
			return fmt.Errorf("reading UserMessage.Content payload: %w", err)
		}
		u.Content = string(u_Content_buf)
	}
	if u_Attachment_len > 0 {
		u_Attachment_buf := make([]byte, u_Attachment_len)
		if _, err := io.ReadFull(reader, u_Attachment_buf); err != nil {
			return fmt.Errorf("reading UserMessage.Attachment payload: %w", err)
		}
		u.Attachment = u_Attachment_buf
	}

	return nil
}

// ---------------------------------------------------------------------------
// HeartbeatMessage
// ---------------------------------------------------------------------------
// Wire Type ID: 2
// Fixed Header: 8 bytes (includes alignment padding)
// ---------------------------------------------------------------------------

// HeartbeatMessage represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type HeartbeatMessage struct {
	Timestamp int64
}

// HeartbeatMessageFixedSize is the byte size of the fixed header portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const HeartbeatMessageFixedSize = 8

// MessageTypeID returns the unique wire protocol type identifier for HeartbeatMessage.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (h *HeartbeatMessage) MessageTypeID() uint16 {
	return 2
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg HeartbeatMessage
	_ = msg
	if unsafe.Sizeof(msg.Timestamp) != 8 {
		panic("wireforge: HeartbeatMessage.Timestamp size mismatch")
	}
}

// Marshal serializes the HeartbeatMessage message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (2)
//	[2:4]     Fixed Header Length (8)
//	[4:12]    Fixed header (primitives + length prefixes, Big-Endian)
//	[12:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (h *HeartbeatMessage) Marshal() ([]byte, error) {
	dynamicSize := 0

	totalSize := FrameHeaderSize + HeartbeatMessageFixedSize + dynamicSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("HeartbeatMessage message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed header length
	binary.BigEndian.PutUint16(buf[0:2], 2)
	binary.BigEndian.PutUint16(buf[2:4], uint16(HeartbeatMessageFixedSize))

	// Fixed header block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + HeartbeatMessageFixedSize


	binary.BigEndian.PutUint64(hdr[0:8], uint64(h.Timestamp))

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a HeartbeatMessage from the wire after the 4-byte frame
// header has already been consumed. The caller provides fixedHeaderLen (read
// from the frame) so forward-compatible readers can skip unknown trailing
// bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (h *HeartbeatMessage) Unmarshal(reader io.Reader, fixedHeaderLen uint16) error {
	if int(fixedHeaderLen) < HeartbeatMessageFixedSize {
		return fmt.Errorf("HeartbeatMessage fixed header too short: got %d, need %d", fixedHeaderLen, HeartbeatMessageFixedSize)
	}

	hdr := make([]byte, fixedHeaderLen)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading HeartbeatMessage fixed header: %w", err)
	}


	h.Timestamp = int64(binary.BigEndian.Uint64(hdr[0:8]))

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed header in the same order as their length prefixes above.

	return nil
}

// ---------------------------------------------------------------------------
// UserJoinedMessage
// ---------------------------------------------------------------------------
// Wire Type ID: 3
// Fixed Header: 16 bytes (includes alignment padding)
// ---------------------------------------------------------------------------

// UserJoinedMessage represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type UserJoinedMessage struct {
	Timestamp int64
	Username string
}

// UserJoinedMessageFixedSize is the byte size of the fixed header portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const UserJoinedMessageFixedSize = 16

// MessageTypeID returns the unique wire protocol type identifier for UserJoinedMessage.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (u *UserJoinedMessage) MessageTypeID() uint16 {
	return 3
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg UserJoinedMessage
	_ = msg
	if unsafe.Sizeof(msg.Timestamp) != 8 {
		panic("wireforge: UserJoinedMessage.Timestamp size mismatch")
	}
}

// Marshal serializes the UserJoinedMessage message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (3)
//	[2:4]     Fixed Header Length (16)
//	[4:20]    Fixed header (primitives + length prefixes, Big-Endian)
//	[20:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (u *UserJoinedMessage) Marshal() ([]byte, error) {
	dynamicSize := 0
	dynamicSize += len(u.Username)

	totalSize := FrameHeaderSize + UserJoinedMessageFixedSize + dynamicSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("UserJoinedMessage message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed header length
	binary.BigEndian.PutUint16(buf[0:2], 3)
	binary.BigEndian.PutUint16(buf[2:4], uint16(UserJoinedMessageFixedSize))

	// Fixed header block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + UserJoinedMessageFixedSize


	binary.BigEndian.PutUint64(hdr[0:8], uint64(u.Timestamp))
	binary.BigEndian.PutUint32(hdr[8:12], uint32(len(u.Username)))
	copy(buf[dynOff:], u.Username)
	dynOff += len(u.Username)

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a UserJoinedMessage from the wire after the 4-byte frame
// header has already been consumed. The caller provides fixedHeaderLen (read
// from the frame) so forward-compatible readers can skip unknown trailing
// bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (u *UserJoinedMessage) Unmarshal(reader io.Reader, fixedHeaderLen uint16) error {
	if int(fixedHeaderLen) < UserJoinedMessageFixedSize {
		return fmt.Errorf("UserJoinedMessage fixed header too short: got %d, need %d", fixedHeaderLen, UserJoinedMessageFixedSize)
	}

	hdr := make([]byte, fixedHeaderLen)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading UserJoinedMessage fixed header: %w", err)
	}


	u.Timestamp = int64(binary.BigEndian.Uint64(hdr[0:8]))
	u_Username_len := binary.BigEndian.Uint32(hdr[8:12])
	if u_Username_len > MaxAllowedPacket {
		return fmt.Errorf("UserJoinedMessage.Username length %d exceeds MaxAllowedPacket", u_Username_len)
	}

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed header in the same order as their length prefixes above.
	if u_Username_len > 0 {
		u_Username_buf := make([]byte, u_Username_len)
		if _, err := io.ReadFull(reader, u_Username_buf); err != nil {
			return fmt.Errorf("reading UserJoinedMessage.Username payload: %w", err)
		}
		u.Username = string(u_Username_buf)
	}

	return nil
}

// ---------------------------------------------------------------------------
// UserLeftMessage
// ---------------------------------------------------------------------------
// Wire Type ID: 4
// Fixed Header: 16 bytes (includes alignment padding)
// ---------------------------------------------------------------------------

// UserLeftMessage represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type UserLeftMessage struct {
	Timestamp int64
	Username string
}

// UserLeftMessageFixedSize is the byte size of the fixed header portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const UserLeftMessageFixedSize = 16

// MessageTypeID returns the unique wire protocol type identifier for UserLeftMessage.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (u *UserLeftMessage) MessageTypeID() uint16 {
	return 4
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg UserLeftMessage
	_ = msg
	if unsafe.Sizeof(msg.Timestamp) != 8 {
		panic("wireforge: UserLeftMessage.Timestamp size mismatch")
	}
}

// Marshal serializes the UserLeftMessage message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (4)
//	[2:4]     Fixed Header Length (16)
//	[4:20]    Fixed header (primitives + length prefixes, Big-Endian)
//	[20:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (u *UserLeftMessage) Marshal() ([]byte, error) {
	dynamicSize := 0
	dynamicSize += len(u.Username)

	totalSize := FrameHeaderSize + UserLeftMessageFixedSize + dynamicSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("UserLeftMessage message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed header length
	binary.BigEndian.PutUint16(buf[0:2], 4)
	binary.BigEndian.PutUint16(buf[2:4], uint16(UserLeftMessageFixedSize))

	// Fixed header block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + UserLeftMessageFixedSize


	binary.BigEndian.PutUint64(hdr[0:8], uint64(u.Timestamp))
	binary.BigEndian.PutUint32(hdr[8:12], uint32(len(u.Username)))
	copy(buf[dynOff:], u.Username)
	dynOff += len(u.Username)

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a UserLeftMessage from the wire after the 4-byte frame
// header has already been consumed. The caller provides fixedHeaderLen (read
// from the frame) so forward-compatible readers can skip unknown trailing
// bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (u *UserLeftMessage) Unmarshal(reader io.Reader, fixedHeaderLen uint16) error {
	if int(fixedHeaderLen) < UserLeftMessageFixedSize {
		return fmt.Errorf("UserLeftMessage fixed header too short: got %d, need %d", fixedHeaderLen, UserLeftMessageFixedSize)
	}

	hdr := make([]byte, fixedHeaderLen)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading UserLeftMessage fixed header: %w", err)
	}


	u.Timestamp = int64(binary.BigEndian.Uint64(hdr[0:8]))
	u_Username_len := binary.BigEndian.Uint32(hdr[8:12])
	if u_Username_len > MaxAllowedPacket {
		return fmt.Errorf("UserLeftMessage.Username length %d exceeds MaxAllowedPacket", u_Username_len)
	}

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed header in the same order as their length prefixes above.
	if u_Username_len > 0 {
		u_Username_buf := make([]byte, u_Username_len)
		if _, err := io.ReadFull(reader, u_Username_buf); err != nil {
			return fmt.Errorf("reading UserLeftMessage.Username payload: %w", err)
		}
		u.Username = string(u_Username_buf)
	}

	return nil
}


// ReadMessageFrame reads the 4-byte wire frame header from r and returns the
// message type ID and fixed header length. Use this when you need to dispatch
// to different message types based on the type ID before calling Unmarshal.
func ReadMessageFrame(r io.Reader) (typeID uint16, fixedHeaderLen uint16, err error) {
	var frame [FrameHeaderSize]byte
	if _, err = io.ReadFull(r, frame[:]); err != nil {
		return 0, 0, err
	}
	typeID = binary.BigEndian.Uint16(frame[0:2])
	fixedHeaderLen = binary.BigEndian.Uint16(frame[2:4])

	return typeID, fixedHeaderLen, nil
}
