// Copyright (c) 2026 Sachin S. All rights reserved.
// 
// Licensed under the MIT License.
// See LICENSE in the project root.

package codegen

import (
	"io"
	"strings"
	"text/template"

	"github.com/avatar31/wireforge/internal/compiler"
	"github.com/avatar31/wireforge/internal/schema"
)

var cTemplate = template.Must(template.New("c").Funcs(template.FuncMap{
	"lower":      strings.ToLower,
	"upper":      strings.ToUpper,
	"snakeUpper": func(name string) string { return strings.ToUpper(compiler.ToSnakeCase(name)) },
	"snakeLower": func(name string) string { return strings.ToLower(compiler.ToSnakeCase(name)) },
	"cType":      func(ft schema.FieldType) string { return ft.CType() },
	"isVariable": func(ft schema.FieldType) bool { return ft.IsVariable() },
	"isByteArray": func(ft schema.FieldType) bool { return ft.GoType() == "[]byte" },
	"add":        func(a, b int) int { return a + b },
	"sub":        func(a, b int) int { return a - b },
}).Parse(cTemplateSource))

// GenerateC writes the generated C implementation to w.
func GenerateC(w io.Writer, cs *compiler.CompiledSchema) error {
	return cTemplate.Execute(w, cs)
}

const cTemplateSource = `/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 *
 * This file implements the serialization, deserialization, stream I/O, and
 * memory management functions declared in {{lower .PackageName}}.h.
 */

#include <stdlib.h>
#include <string.h>

#include "{{lower .PackageName}}.h"

/* ---------------------------------------------------------------------------
 * Big-Endian encoding/decoding helpers
 * These ensure consistent wire format regardless of host CPU byte order.
 * ---------------------------------------------------------------------------*/

static inline void put_u16_be(uint8_t* buf, uint16_t val) {
    buf[0] = (uint8_t)(val >> 8);
    buf[1] = (uint8_t)(val);
}

static inline void put_u32_be(uint8_t* buf, uint32_t val) {
    buf[0] = (uint8_t)(val >> 24);
    buf[1] = (uint8_t)(val >> 16);
    buf[2] = (uint8_t)(val >> 8);
    buf[3] = (uint8_t)(val);
}

static inline void put_u64_be(uint8_t* buf, uint64_t val) {
    buf[0] = (uint8_t)(val >> 56);
    buf[1] = (uint8_t)(val >> 48);
    buf[2] = (uint8_t)(val >> 40);
    buf[3] = (uint8_t)(val >> 32);
    buf[4] = (uint8_t)(val >> 24);
    buf[5] = (uint8_t)(val >> 16);
    buf[6] = (uint8_t)(val >> 8);
    buf[7] = (uint8_t)(val);
}

static inline uint16_t get_u16_be(const uint8_t* buf) {
    return (uint16_t)((uint16_t)buf[0] << 8 | (uint16_t)buf[1]);
}

static inline uint32_t get_u32_be(const uint8_t* buf) {
    return (uint32_t)buf[0] << 24 | (uint32_t)buf[1] << 16 |
           (uint32_t)buf[2] << 8  | (uint32_t)buf[3];
}

static inline uint64_t get_u64_be(const uint8_t* buf) {
    return (uint64_t)buf[0] << 56 | (uint64_t)buf[1] << 48 |
           (uint64_t)buf[2] << 40 | (uint64_t)buf[3] << 32 |
           (uint64_t)buf[4] << 24 | (uint64_t)buf[5] << 16 |
           (uint64_t)buf[6] << 8  | (uint64_t)buf[7];
}

uint16_t get_message_type(const uint8_t* buf) {
    return get_u16_be(buf);
}

uint16_t get_message_fixed_length(const uint8_t* buf) {
    return get_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE);
}

{{range .Messages}}{{$msg := .}}
/* ===========================================================================
 * {{.Name}} (Type ID: {{.TypeID}}, Fixed Header: {{.TotalFixedSize}} bytes)
 * ===========================================================================*/

{{- range .Fields}}{{$msg_field := .}}

/**
 * Sets the value of the {{$msg_field.CName}} field in the {{snakeLower $msg.Name}}_t struct.
 */
{{- if isVariable $msg_field.Type}}
{{- if isByteArray $msg_field.Type}}
void {{snakeLower $msg.Name}}_set_{{$msg_field.CName}}({{snakeLower $msg.Name}}_t* msg, const uint8_t* value, size_t len) {
    if (!msg || !value || len == 0) return;
    if (msg->{{$msg_field.CName}} != NULL) {
        free(msg->{{$msg_field.CName}});
    }

    uint8_t* new_value = (uint8_t*) malloc(len);
    if (!new_value) return;

    memcpy(new_value, value, len);
    msg->{{$msg_field.CName}} = new_value;
    msg->{{$msg_field.CName}}_len = (uint32_t)len;
}
{{- else}}
void {{snakeLower $msg.Name}}_set_{{$msg_field.CName}}({{snakeLower $msg.Name}}_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->{{$msg_field.CName}} != NULL) {
        free(msg->{{$msg_field.CName}});
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->{{$msg_field.CName}} = new_value;
    msg->{{$msg_field.CName}}_len = (uint32_t)len;
}
{{- end}}
{{- else}}
void {{snakeLower $msg.Name}}_set_{{$msg_field.CName}}({{snakeLower $msg.Name}}_t* msg, const {{cType $msg_field.Type}} value) {
    if (msg) msg->{{$msg_field.CName}} = value;
}
{{- end}}
{{- end}}

/**
 * calculate_{{snakeLower .Name}}_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the {{$msg.Name}} message from the fixed header.
 */
size_t calculate_{{snakeLower .Name}}_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
{{- range .VariableFields}}
    uint32_t {{.CName}}_len = get_u32_be(hdr_buf + {{.Offset}});
    dyn_total += {{.CName}}_len;
{{- end}}
    return dyn_total;
}

/**
 * {{snakeLower .Name}}_marshal - Serialize {{.Name}} to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID ({{.TypeID}}, Big-Endian)
 *   [2:4]     Fixed header length ({{.TotalFixedSize}}, Big-Endian)
 *   [4:{{add 4 .TotalFixedSize}}]    Fixed header (fields + padding, Big-Endian encoded)
 *   [{{add 4 .TotalFixedSize}}:end]  Dynamic payload (variable-length field data)
 */
int {{snakeLower .Name}}_marshal(const {{snakeLower .Name}}_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;
{{- range .VariableFields}}
    dyn_size += msg->{{.CName}}_len;
{{- end}}

    size_t total = WIRE_FRAME_HEADER_SIZE + {{snakeUpper .Name}}_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + {{snakeUpper .Name}}_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, {{snakeUpper .Name}}_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, {{snakeUpper .Name}}_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + {{snakeUpper .Name}}_FIXED_SIZE;

{{- range .Fields}}
{{- if isVariable .Type}}
    put_u32_be(hdr + {{.Offset}}, msg->{{.CName}}_len);
    if (msg->{{.CName}}_len > 0 && msg->{{.CName}}) {
        memcpy(buf + dyn_off, msg->{{.CName}}, msg->{{.CName}}_len);
        dyn_off += msg->{{.CName}}_len;
    }
{{- else}}
{{- if eq (cType .Type) "uint8_t"}}
    hdr[{{.Offset}}] = msg->{{.CName}};
{{- else if eq (cType .Type) "int8_t"}}
    hdr[{{.Offset}}] = (uint8_t)msg->{{.CName}};
{{- else if eq (cType .Type) "uint16_t"}}
    put_u16_be(hdr + {{.Offset}}, msg->{{.CName}});
{{- else if eq (cType .Type) "int16_t"}}
    put_u16_be(hdr + {{.Offset}}, (uint16_t)msg->{{.CName}});
{{- else if eq (cType .Type) "uint32_t"}}
    put_u32_be(hdr + {{.Offset}}, msg->{{.CName}});
{{- else if eq (cType .Type) "int32_t"}}
    put_u32_be(hdr + {{.Offset}}, (uint32_t)msg->{{.CName}});
{{- else if eq (cType .Type) "uint64_t"}}
    put_u64_be(hdr + {{.Offset}}, msg->{{.CName}});
{{- else if eq (cType .Type) "int64_t"}}
    put_u64_be(hdr + {{.Offset}}, (uint64_t)msg->{{.CName}});
{{- else if eq (cType .Type) "float"}}
    {
        uint32_t tmp;
        memcpy(&tmp, &msg->{{.CName}}, sizeof(tmp));
        put_u32_be(hdr + {{.Offset}}, tmp);
    }
{{- else if eq (cType .Type) "double"}}
    {
        uint64_t tmp;
        memcpy(&tmp, &msg->{{.CName}}, sizeof(tmp));
        put_u64_be(hdr + {{.Offset}}, tmp);
    }
{{- end}}
{{- end}}
{{- end}}

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * {{snakeLower .Name}}_unmarshal - Deserialize {{.Name}} from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call {{snakeLower .Name}}_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int {{snakeLower .Name}}_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, {{snakeLower .Name}}_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < {{snakeUpper .Name}}_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof({{snakeLower .Name}}_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
{{- range .Fields}}
{{- if isVariable .Type}}
    out_msg->{{.CName}}_len = get_u32_be(hdr + {{.Offset}});
{{- else}}
{{- if eq (cType .Type) "uint8_t"}}
    out_msg->{{.CName}} = hdr[{{.Offset}}];
{{- else if eq (cType .Type) "int8_t"}}
    out_msg->{{.CName}} = (int8_t)hdr[{{.Offset}}];
{{- else if eq (cType .Type) "uint16_t"}}
    out_msg->{{.CName}} = get_u16_be(hdr + {{.Offset}});
{{- else if eq (cType .Type) "int16_t"}}
    out_msg->{{.CName}} = (int16_t)get_u16_be(hdr + {{.Offset}});
{{- else if eq (cType .Type) "uint32_t"}}
    out_msg->{{.CName}} = get_u32_be(hdr + {{.Offset}});
{{- else if eq (cType .Type) "int32_t"}}
    out_msg->{{.CName}} = (int32_t)get_u32_be(hdr + {{.Offset}});
{{- else if eq (cType .Type) "uint64_t"}}
    out_msg->{{.CName}} = get_u64_be(hdr + {{.Offset}});
{{- else if eq (cType .Type) "int64_t"}}
    out_msg->{{.CName}} = (int64_t)get_u64_be(hdr + {{.Offset}});
{{- else if eq (cType .Type) "float"}}
    {
        uint32_t tmp = get_u32_be(hdr + {{.Offset}});
        memcpy(&out_msg->{{.CName}}, &tmp, sizeof(tmp));
    }
{{- else if eq (cType .Type) "double"}}
    {
        uint64_t tmp = get_u64_be(hdr + {{.Offset}});
        memcpy(&out_msg->{{.CName}}, &tmp, sizeof(tmp));
    }
{{- end}}
{{- end}}
{{- end}}

    /* Decode variable-length dynamic fields safely */
{{- range .VariableFields}}
    if (out_msg->{{.CName}}_len > 0) {
        if (out_msg->{{.CName}}_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->{{.CName}}_len > in_len) {
            {{snakeLower $msg.Name}}_free(out_msg);
            return -1;
        }

{{- if eq (.Type.GoType) "string"}}
        out_msg->{{.CName}} = (char*) malloc(out_msg->{{.CName}}_len + 1);
        if (!out_msg->{{.CName}}) {
            {{snakeLower $msg.Name}}_free(out_msg);
            return -1;
        }

        memcpy(out_msg->{{.CName}}, in_buf + dyn_off, out_msg->{{.CName}}_len);
        out_msg->{{.CName}}[out_msg->{{.CName}}_len] = '\0';
{{- else}}
        out_msg->{{.CName}} = (uint8_t*)malloc(out_msg->{{.CName}}_len);
        if (!out_msg->{{.CName}}) {
            {{snakeLower $msg.Name}}_free(out_msg);
            return -1;
        }
        memcpy(out_msg->{{.CName}}, in_buf + dyn_off, out_msg->{{.CName}}_len);
{{- end}}
        dyn_off += out_msg->{{.CName}}_len;
    }
{{- end}}

    (void)dyn_off;
    return 0;
}

/**
 * {{snakeLower .Name}}_free - Release heap memory owned by a {{snakeLower .Name}}_t struct.
 */
void {{snakeLower .Name}}_free({{snakeLower .Name}}_t* msg) {
    if (!msg) return;
{{- range .VariableFields}}
    if (msg->{{.CName}}) {
        free(msg->{{.CName}});
        msg->{{.CName}} = NULL;
    }
    msg->{{.CName}}_len = 0;
{{- end}}
}

{{end}}
`
