// Copyright (c) 2026 Sachin S. All rights reserved.
// 
// Licensed under the MIT License.
// See LICENSE in the project root.

package codegen

import (
	"io"
	"strings"
	"text/template"

	"github.com/avatar31/wireforge/internal/compiler"
	"github.com/avatar31/wireforge/internal/schema"
)

var cHeaderTemplate = template.Must(template.New("cheader").Funcs(template.FuncMap{
	"upper":      strings.ToUpper,
	"lower":      strings.ToLower,
	"cType":      func(ft schema.FieldType) string { return ft.CType() },
	"isVariable": func(ft schema.FieldType) bool { return ft.IsVariable() },
	"isByteArray": func(ft schema.FieldType) bool { return ft.GoType() == "[]byte" },
	"add":        func(a, b int) int { return a + b },
	"snakeUpper": func(name string) string { return strings.ToUpper(compiler.ToSnakeCase(name)) },
	"snakeLower": func(name string) string { return strings.ToLower(compiler.ToSnakeCase(name)) },
	"padFields":  generatePadFields,
}).Parse(cHeaderTemplateSource))

// GenerateCHeader writes the generated C header to w.
func GenerateCHeader(w io.Writer, cs *compiler.CompiledSchema) error {
	return cHeaderTemplate.Execute(w, cs)
}

const cHeaderTemplateSource = `/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 *
 * This header defines C structure types and function prototypes for a
 * length-prefixed binary wire protocol. Each message type has:
 *
 *   - A typedef struct with explicit padding fields for deterministic layout
 *   - _Static_assert to verify struct size at compile time
 *   - Marshal/Unmarshal functions for buffer-based serialization
 *   - Stream-safe read/write functions for socket I/O (handles short reads)
 *   - A free function to release dynamically allocated fields
 *
 * Wire Protocol Frame Layout:
 *   +--------+------------------+-------------------+------------------+
 *   | Offset | Field            | Type              | Description      |
 *   +--------+------------------+-------------------+------------------+
 *   | 0      | Message Type ID  | uint16 Big-Endian | Codec selector   |
 *   | 2      | Fixed Header Len | uint16 Big-Endian | Fixed block size |
 *   | 4      | Fixed Header     | raw bytes         | Padded fields    |
 *   | 4+N    | Dynamic Payload  | raw bytes         | Strings/blobs    |
 *   +--------+------------------+-------------------+------------------+
 *
 * Safety guarantees:
 *   - MAX_ALLOWED_PACKET caps any single allocation (prevents malloc bombs)
 *   - NULL checks on every allocation result
 *   - Strings are always NULL-terminated after deserialization
 *   - free functions set pointers to NULL to prevent double-free
 *
 * Memory ownership:
 *   - After unmarshal, the caller owns the struct and must call
 *     the corresponding _free() function when done.
 *   - After marshal, no heap memory is retained by the callee.
 */
#ifndef {{upper .PackageName}}_H
#define {{upper .PackageName}}_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Maximum allowed packet size (16 MB).
 * Any length field exceeding this is treated as data corruption and
 * immediately rejected to prevent denial-of-service via malloc bombs.
 */
#define MAX_ALLOWED_PACKET (16 * 1024 * 1024)

#define WIRE_FRAME_MSG_TYPE_SIZE 2
#define WIRE_FRAME_MSG_FIXED_SIZE 2

/** Size of the wire frame header: 2-byte type ID + 2-byte fixed header length. */
#define WIRE_FRAME_HEADER_SIZE 4

uint16_t get_message_type(const uint8_t* buf);
uint16_t get_message_fixed_length(const uint8_t* buf);

{{range .Messages}}{{$msg := .}}
/* ===========================================================================
 * {{.Name}}
 * Wire Type ID: {{.TypeID}}
 * Fixed Header: {{.TotalFixedSize}} bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for {{.Name}}. */
#define {{snakeUpper .Name}}_TYPE_ID {{.TypeID}}

/** Byte size of the fixed header block for {{.Name}} (padded for alignment). */
#define {{snakeUpper .Name}}_FIXED_SIZE {{.TotalFixedSize}}

/**
 * {{snakeLower .Name}}_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
{{- range padFields .}}
{{- if .IsPadding}}
    uint8_t {{.PadName}}[{{.PadSize}}]; /**< Explicit alignment padding. */
{{- else}}
{{- if isVariable .Field.Type}}
{{- if .Field.Description}}
    /** {{.Field.Description}} (length of dynamic payload below). */
{{- end}}
    uint32_t {{.Field.CName}}_len;
    {{cType .Field.Type}} {{.Field.CName}};     /**< Heap-allocated; call {{lower $msg.Name}}_free() when done. */
{{- else}}
{{- if .Field.Description}}
    /** {{.Field.Description}} */
{{- end}}
    {{cType .Field.Type}} {{.Field.CName}};
{{- end}}
{{- end}}
{{- end}}
} {{snakeLower .Name}}_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof({{snakeLower .Name}}_t) >= {{.TotalFixedSize}},
    "wireforge: {{snakeLower .Name}}_t fixed layout size mismatch");

{{- range .Fields}}{{$msg_field := .}}

/**
 * Sets the value of the {{$msg_field.CName}} field in the {{snakeLower $msg.Name}}_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
{{- if isVariable $msg_field.Type}}
{{- if isByteArray $msg_field.Type}}
void {{snakeLower $msg.Name}}_set_{{$msg_field.CName}}({{snakeLower $msg.Name}}_t* msg, const uint8_t* value, size_t len);
{{- else}}
void {{snakeLower $msg.Name}}_set_{{$msg_field.CName}}({{snakeLower $msg.Name}}_t* msg, const char* value);
{{- end}}
{{- else}}
void {{snakeLower $msg.Name}}_set_{{$msg_field.CName}}({{snakeLower $msg.Name}}_t* msg, const {{cType $msg_field.Type}} value);
{{- end}}
{{- end}}

/**
 * calculate_{{snakeLower .Name}}_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the {{$msg.Name}} message from the fixed header.
 */
size_t calculate_{{snakeLower .Name}}_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a {{.Name}} message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int {{snakeLower .Name}}_marshal(const {{snakeLower .Name}}_t* msg, uint8_t** out_buf);

/**
 * Deserialize a {{.Name}} message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call {{snakeLower .Name}}_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int {{snakeLower .Name}}_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, {{snakeLower .Name}}_t* out_msg);

/**
 * Free all dynamically allocated fields in a {{snakeLower .Name}}_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void {{snakeLower .Name}}_free({{snakeLower .Name}}_t* msg);

{{end}}
#ifdef __cplusplus
}
#endif

#endif /* {{upper .PackageName}}_H */
`
