// Copyright (c) 2026 Sachin S. All rights reserved.
//
// Licensed under the MIT License.
// See LICENSE in the project root.

package codegen

import (
	"io"
	"strings"
	"text/template"

	"github.com/avatar31/wireforge/internal/compiler"
	"github.com/avatar31/wireforge/internal/schema"
)

var cHeaderTemplate = template.Must(template.New("cheader").Funcs(template.FuncMap{
	"upper":       strings.ToUpper,
	"lower":       strings.ToLower,
	"cBaseType":   func (f *compiler.CompiledField) string { return f.Type.CType() },
	"cType":       cType,
	"isVariable":  func(ft schema.FieldType) bool { return ft.IsVariable() },
	"add":         func(a, b int) int { return a + b },
	"snakeUpper":  func(name string) string { return strings.ToUpper(compiler.ToSnakeCase(name)) },
	"snakeLower":  snakeLower,
	"padFields":   generatePadFields,
}).Parse(cHeaderTemplateSource))

// GenerateCHeader writes the generated C header to w.
func GenerateCHeader(w io.Writer, cs *compiler.CompiledSchema) error {
	return cHeaderTemplate.Execute(w, cs)
}

func snakeLower(name string) string {
	return strings.ToLower(compiler.ToSnakeCase(name))
}

func cType(f *compiler.CompiledField, messages []*compiler.CompiledMessage) string {
	switch f.Type {
	case schema.FieldTypeObject:
		for _, msg := range messages {
			if msg.TypeID == f.NestedMessageId {
				return snakeLower(msg.Name)
			}
		}
	case schema.FieldTypeArray:
		return "dynamic_array_t*"
	default:
		return f.Type.CType()
	}

	return ""
}

const cHeaderTemplateSource = `/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 * To know more visit: github.com/avatar31/wireforge
 *
 * This header defines C structure types and function prototypes for a
 * length-prefixed binary wire protocol. Each message type has:
 *
 *   - A typedef struct with explicit padding fields for deterministic layout
 *   - _Static_assert to verify struct size at compile time
 *   - Marshal/Unmarshal functions for buffer-based serialization
 *   - Stream-safe read/write functions for socket I/O (handles short reads)
 *   - A free function to release dynamically allocated fields
 *
 * Wire Protocol Frame Layout:
 *   +--------+---------------------+-------------------+--------------------+
 *   | Offset | Field               | Type              | Description        |
 *   +--------+---------------------+-------------------+--------------------+
 *   | 0      | Message Type ID     | uint16 Big-Endian | Codec selector     |
 *   | 2      | Fixed Payload Len   | uint16 Big-Endian | Fixed block size   |
 *   | 4      | Overall Payload Len | uint32 Big-Endian | Fixed + Dynamic    |
 *   | 8      | Fixed Payload       | raw bytes         | Padded fields      |
 *   | 8+N    | Dynamic Payload     | raw bytes         | Strings/blobs      |
 *   +--------+---------------------+-------------------+--------------------+
 *
 * Safety guarantees:
 *   - MAX_ALLOWED_PACKET caps any single allocation (prevents malloc bombs)
 *   - NULL checks on every allocation result
 *   - Strings are always NULL-terminated after deserialization
 *   - free functions set pointers to NULL to prevent double-free
 *
 * Memory ownership:
 *   - After unmarshal, the caller owns the struct and must call
 *     the corresponding _free() function when done.
 *   - After marshal, no heap memory is retained by the callee.
 */

#ifndef {{upper .PackageName}}_H
#define {{upper .PackageName}}_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Maximum allowed packet size (16 MB).
 * Any length field exceeding this is treated as data corruption and
 * immediately rejected to prevent denial-of-service via malloc bombs.
 */
#define MAX_ALLOWED_PACKET (16 * 1024 * 1024)

#define WIRE_FRAME_MSG_TYPE_SIZE 2
#define WIRE_FRAME_MSG_FIXED_PAYLOAD_SIZE 2
#define WIRE_FRAME_MSG_OVERALL_PAYLOAD_SIZE 4
#define TYPE_MARKER_SIZE 2
#define ARRAY_COUNT_PREFIX_SIZE 2
#define STRING_OR_BYTE_LEN_PREFIX_SIZE 4
#define MAX_ARRAY_ELEMENTS 65535

/**
 * Size of the wire frame header:
 *		2-byte type ID + 2-byte fixed payload length + 4-byte overall payload length
 */
#define WIRE_FRAME_HEADER_SIZE 8

typedef enum {
    TAG_NONE        = 0x0000,
    TAG_UINT8       = 0x0001,
    TAG_INT8        = 0x0002,
    TAG_BOOL        = 0x0003,
    TAG_UINT16      = 0x0004,
    TAG_INT16       = 0x0005,
    TAG_UINT32      = 0x0006,
    TAG_INT32       = 0x0007,
    TAG_FLOAT32     = 0x0008,
    TAG_UINT64      = 0x0009,
    TAG_INT64       = 0x000A,
    TAG_FLOAT64     = 0x000B,
    TAG_STRING      = 0x000C,
    TAG_BYTES       = 0x000D,
    TAG_ARRAY       = 0x000E,
    TAG_2D_ARRAY    = 0x000F,
    TAG_3D_ARRAY    = 0x0010,
{{- range $i, $msg := .Messages }}
    TAG_{{snakeUpper $msg.Name}}       = {{ printf "0x%04X" (add $i 32) }},
{{- end }}
} element_type_t;

typedef struct {
	char *data;
	uint32_t len;
} string_t;

typedef struct {
	uint8_t *data;
	uint32_t len;
} byte_array_t;

typedef struct {
    void *data;
    size_t elem_size;
    
    // User dimensions
    uint8_t num_dims; // 1, 2, or 3
    size_t x;
    size_t y;
    size_t z;
    
    // The total maximum flat elements the current memory can hold
    size_t capacity; 
	element_type_t ele_type; // element type for dynamic arrays
} dynamic_array_t;

uint16_t get_message_type(const uint8_t *buf);
uint16_t get_message_fixed_payload_length(const uint8_t *buf);
uint32_t get_message_overall_payload_length(const uint8_t *buf);

{{$overallMessages := .Messages}}
{{range .Messages}}{{$msg := .}}
typedef struct {{snakeLower $msg.Name}} {{snakeLower $msg.Name}}_t;
{{end}}{{/* range .Messages */}}
{{$overallMessages := .Messages}}
{{range .Messages}}{{$msg := .}}
/* ===========================================================================
 * {{$msg.Name}}
 * Wire Type ID: {{$msg.TypeID}}
 * Fixed Block Length: {{.TotalFixedSize}} bytes (including alignment padding)
 * Overall Payload Length: {{.TotalFixedSize}} bytes + Runtime dynamic payload
 * ===========================================================================*/

/** Wire protocol message type ID for {{$msg.Name}}. */
#define {{snakeUpper $msg.Name}}_TYPE_ID {{$msg.TypeID}}

/** Byte size of the fixed block for {{$msg.Name}} (padded for alignment). */
#define {{snakeUpper $msg.Name}}_FIXED_SIZE {{.TotalFixedSize}}

/**
 * {{snakeLower $msg.Name}}_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
struct {{snakeLower $msg.Name}} {
{{- range padFields .}} {{$pad_field := .}}
{{- if $pad_field.IsPadding}}
    uint8_t {{$pad_field.PadName}}[{{$pad_field.PadSize}}]; /**< Explicit alignment padding. */
{{- else}}
{{- if isVariable $pad_field.Field.Type}}
{{- if $pad_field.Field.Description}}
    /** {{$pad_field.Field.Description}} */
{{- end}} {{/* $pad_field.Field.Description */}}
{{- if eq (cBaseType $pad_field.Field) "struct"}}
	{{snakeLower (cType $pad_field.Field $overallMessages)}}_t *{{$pad_field.Field.CName}};
{{- else if eq (cBaseType $pad_field.Field) "[]any"}}
	dynamic_array_t {{$pad_field.Field.CName}};
{{- else if eq (cBaseType $pad_field.Field) "string"}}
	string_t {{$pad_field.Field.CName}};
{{- else if eq (cBaseType $pad_field.Field) "[]byte"}}
	byte_array_t {{$pad_field.Field.CName}};
{{end}}{{/* eq (cBaseType $pad_field.Field) */}}

{{- else}} {{/* not (isVariable $pad_field.Field.Type) */}}
{{- if $pad_field.Field.Description}}
    /** {{$pad_field.Field.Description}} */
{{- end}} {{/* $pad_field.Field.Description */}}
    {{cBaseType $pad_field.Field}} {{$pad_field.Field.CName}};
{{- end}} {{/* isVariable $pad_field.Field.Type */}}
{{- end}} {{/* $pad_field.IsPadding */}}
{{- end}} {{/* range padFields . */}}
};

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof({{snakeLower $msg.Name}}_t) >= {{.TotalFixedSize}},
    "wireforge: {{snakeLower $msg.Name}}_t fixed layout size mismatch");

{{- range $msg.Fields}}{{$field := .}}

/**
 * Sets the value of the {{$field.CName}} field in the {{snakeLower $msg.Name}}_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
{{- if isVariable $field.Type}}
{{- if eq (cBaseType $field) "[]any"}}
void {{snakeLower $msg.Name}}_t_set_{{$field.CName}}({{snakeLower $msg.Name}}_t *msg, const dynamic_array_t *value);
{{- else if eq (cBaseType $field) "struct"}}
void {{snakeLower $msg.Name}}_t_set_{{$field.CName}}({{snakeLower $msg.Name}}_t *msg, const {{cType $field $overallMessages}}_t *value);
{{- else if eq (cBaseType $field) "string"}}
void {{snakeLower $msg.Name}}_t_set_{{$field.CName}}({{snakeLower $msg.Name}}_t *msg, const char *value, const size_t len);
{{- else if eq (cBaseType $field) "[]byte"}}
void {{snakeLower $msg.Name}}_t_set_{{$field.CName}}({{snakeLower $msg.Name}}_t *msg, const uint8_t *value, const size_t len);
{{- end}}{{/* if (cBaseType $field) */}}
{{- else}}{{/* not (isVariable $field.Type) */}}
void {{snakeLower $msg.Name}}_t_set_{{$field.CName}}({{snakeLower $msg.Name}}_t *msg, const {{cBaseType $field}} value);
{{- end}}{{/* isVariable $field.Type */}}
{{- end}}{{/* range $msg.Fields */}}

size_t {{snakeLower $msg.Name}}_t_dynamic_payload_size(const {{snakeLower $msg.Name}}_t *msg);

size_t {{snakeLower $msg.Name}}_t_size(const {{snakeLower $msg.Name}}_t *msg);

/**
 * Serialize a {{$msg.Name}} message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function
 * 					will write the serialized message stream into the buffer referenced
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int {{snakeLower $msg.Name}}_t_marshal(const {{snakeLower $msg.Name}}_t *msg, uint8_t **out_buf);

/**
 * Deserialize a {{$msg.Name}} message from a contiguous buffer.
 *
 * @param in_buf				Input buffer starting at the fixed payload (after 8-bytes frame header).
 * @param fixed_payload_len		Fixed payload length as read from the wire frame header.
 * @param overall_payload_len	Total available bytes in in_buf (fixed + dynamic payload).
 * @param out_msg				Output struct (zeroed on entry; fields populated on success).
 * @return						0 on success, -1 on error (truncated data, allocation failure,
 *                          		length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call {{snakeLower $msg.Name}}_t_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int {{snakeLower $msg.Name}}_t_unmarshal(const uint8_t *in_buf, uint16_t fixed_payload_len,
		uint32_t overall_payload_len, {{snakeLower $msg.Name}}_t *out_msg);

/**
 * Free all dynamically allocated fields in a {{snakeLower $msg.Name}}_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void {{snakeLower $msg.Name}}_t_free({{snakeLower $msg.Name}}_t *msg);

{{end}}{{/* range .Messages */}}

/**
 * Internal Helpers
 */

typedef size_t (*custom_size_fn)(const void *item);
typedef int (*custom_marshal_fn)(const void *item, uint8_t **out_buf);
typedef int (*custom_unmarshal_fn)(const uint8_t *buf, uint16_t buf_len,
	uint32_t overall_payload_len, void *out_item);

size_t calc_type_size(
    const void *item,
    element_type_t ele_type,
    custom_size_fn size_fn
);

size_t calc_array_size(
    const dynamic_array_t *arr,
    element_type_t ele_type,
    custom_size_fn size_fn
);

#ifdef __cplusplus
}
#endif

#endif /* {{upper .PackageName}}_H */
`
