// Copyright (c) 2026 Sachin S. All rights reserved.
//
// Licensed under the MIT License.
// See LICENSE in the project root.

package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strings"
	"text/template"

	"github.com/avatar31/wireforge/internal/compiler"
	"github.com/avatar31/wireforge/internal/schema"
)

var goTemplate = template.Must(template.New("go").Funcs(template.FuncMap{
	"lower":             strings.ToLower,
	"goBaseType":        func(ft schema.FieldType) string { return ft.GoType() },
	"goType":            goType,
	"isVariable":        func(ft schema.FieldType) bool { return ft.IsVariable() },
	"size":              func(ft schema.FieldType) int { return ft.Size() },
	"sub":               func(a, b int) int { return a - b },
	"add":               func(a, b int) int { return a + b },
	"receiver":          func(name string) string { return strings.ToLower(name[:1]) },
	"hasVariable":       func(msg *compiler.CompiledMessage) bool { return len(msg.VariableFields) > 0 },
	"arrayDimension":    arrayDimension,
	"arrayRootGoType":   arrayRootGoType,
	"arrayRootBaseType": arrayRootBaseType,
}).Parse(goTemplateSource))

// GenerateGo writes the generated Go source to w.
func GenerateGo(w io.Writer, cs *compiler.CompiledSchema) error {
	var buf bytes.Buffer
	err := goTemplate.Execute(&buf, cs)
	if err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Print("Warning: failed to format go generated code")
		_, _ = w.Write(buf.Bytes())
		return err
	}

	_, err = w.Write(formatted)
	return err
}

func goType(f *compiler.CompiledField, messages []*compiler.CompiledMessage, pointerStruct bool) string {
	switch f.Type {
	case schema.FieldTypeObject:
		for _, msg := range messages {
			if msg.TypeID == f.NestedMessageId {
				if pointerStruct {
					return fmt.Sprintf("*%s", msg.Name)
				}
				return msg.Name
			}
		}
	case schema.FieldTypeArray:
		dimension := arrayDimension(f)
		var output strings.Builder
		for range dimension {
			output.WriteString("[]")
		}

		// if pointerStruct {
		// 	output.WriteString("*")
		// }

		output.WriteString(arrayRootGoType(f, messages, true))
		return output.String()
	default:
		return f.Type.GoType()
	}

	return ""
}

const goTemplateSource = `// Code generated by wireforge. DO NOT EDIT.
// To know more visit: github.com/avatar31/wireforge
//
// This file contains type-safe message definitions with binary serialization
// for a length-prefixed wire protocol. All multi-byte integers are encoded in
// Big-Endian (network byte order) to ensure cross-platform compatibility.
//
// Wire Protocol Frame Layout:
// 		+--------+---------------------+-------------------+--------------------+
// 		| Offset | Field               | Type              | Description        |
// 		+--------+---------------------+-------------------+--------------------+
// 		| 0      | Message Type ID     | uint16 Big-Endian | Codec selector     |
// 		| 2      | Fixed Payload Len   | uint16 Big-Endian | Fixed block size   |
// 		| 4      | Overall Payload Len | uint32 Big-Endian | Fixed + Dynamic    |
// 		| 8      | Fixed Payload       | raw bytes         | Padded fields      |
// 		| 8+N    | Dynamic Payload     | raw bytes         | Strings/blobs      |
// 		+--------+---------------------+-------------------+--------------------+
//
// Safety guarantees:
//   - MaxAllowedPacket (16 MB) prevents memory allocation exploits from
//     corrupted length fields ("poison pill" attack mitigation).
//   - init() performs compile-time layout validation via unsafe.Sizeof to
//     catch struct size mismatches between the generator and the Go compiler.
//   - All reads use io.ReadFull to handle socket short-reads correctly.
//   - Big-Endian encoding ensures consistent behavior across architectures.
package {{.PackageName}}

import (
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"unsafe"
)

const (
	// FrameHeaderSize represents the 2 bytes for TypeID, 2 bytes for FixedBlockLen
	// and 4 bytes for overall data size.
	FrameHeaderSize = 8

	// 2 bytes for the count prefix of any array
	ArrayCountPrefixSize = 2

	// 2 bytes for the type tag of any array
	TypeMarkerSize = 2

	// 2B Array Tag + 2B Element Type + 2B Overall Count + 2B X-axis Count
	ArrayPrefixSize = (TypeMarkerSize * 2) + (ArrayCountPrefixSize * 2)

	// 4 bytes for the length prefix of any string or byte slice
	StrOrByteLenPrefixSize = 4

	// 1 byte for the length prefix of any object set or unset field
	ObjectSetUnsetPrefixSize = 1

	// MaxAllowedPacket is the hard ceiling on any single message size (16 MB).
	// Any incoming length field exceeding this value is treated as corrupted
	// data and rejected immediately, preventing denial-of-service via
	// malicious allocation requests.
	MaxAllowedPacket = 16 * 1024 * 1024

	// 2^16 - 1, since array length is encoded as uint16
	MaxArrayElements = 65535
)

// Constants for our 2-byte Type Markers
const (
    TagNone      uint16 = 0x0000
    TagUint8     uint16 = 0x0001
    TagInt8 	 uint16 = 0x0002
    TagBool      uint16 = 0x0003
	TagUint16    uint16 = 0x0004
	TagInt16     uint16 = 0x0005
	TagUint32    uint16 = 0x0006
	TagInt32     uint16 = 0x0007
	TagFloat32   uint16 = 0x0008
	TagUint64    uint16 = 0x0009
	TagInt64     uint16 = 0x000A
	TagFloat64   uint16 = 0x000B
	TagString    uint16 = 0x000C
    TagBytes 	 uint16 = 0x000D
    TagArray     uint16 = 0x000E
	Tag2DArray 	 uint16 = 0x000F
	Tag3DArray 	 uint16 = 0x0010
{{- range $i, $msg := .Messages }}
    Tag{{$msg.Name}} uint16 = {{ printf "0x%04X" (add $i 32) }}
{{- end }}
)

// Compile-time import usage guarantees.
var (
	_ = binary.BigEndian
	_ = io.ReadFull
	_ = math.Float32frombits
	_ = unsafe.Sizeof(uint8(0))
)

type Sizable interface {
    Size() int
}

type ArraySizer interface {
	SetElements(elements any)
	CalcSize() int
	GetEleType() uint16
}

type array1D[T any] struct {
	Elements []T
	EleType  uint16
}

func (arr *array1D[T]) SetElements(elements any) {
	items, ok := elements.([]T)
	if !ok {
		panic("array1D: invalid element type")
	}
	arr.Elements = items
}

func (arr *array1D[T]) CalcSize() int {
	return (TypeMarkerSize * 2) + 
		(ArrayCountPrefixSize * 2) +
		calc1DArraySize(arr.EleType, arr.Elements)
}

func (arr *array1D[T]) SetEleType(eleType uint16) {
	arr.EleType = eleType
}

func (arr *array1D[T]) GetEleType() uint16 {
	return arr.EleType
}

type array2D[T any] struct {
	Elements [][]T
	EleType  uint16
}

func (arr *array2D[T]) SetElements(elements any) {
	items, ok := elements.([][]T)
	if !ok {
		panic("array2D: invalid element type")
	}
	arr.Elements = items
}

func (arr *array2D[T]) CalcSize() int {
	size := (TypeMarkerSize * 2) + ArrayCountPrefixSize + ArrayCountPrefixSize
	for _, row := range arr.Elements {
		size += ArrayCountPrefixSize
		size += calc1DArraySize(arr.EleType, row)
	}
	return size
}

func (arr *array2D[T]) GetEleType() uint16 {
	return arr.EleType
}

type array3D[T any] struct {
	Elements [][][]T
	EleType  uint16
}

func (arr *array3D[T]) SetElements(elements any) {
	items, ok := elements.([][][]T)
	if !ok {
		panic("array3D: invalid element type")
	}
	arr.Elements = items
}

func (arr *array3D[T]) CalcSize() int {
	size := (TypeMarkerSize * 2) + ArrayCountPrefixSize + ArrayCountPrefixSize
	for _, plane := range arr.Elements {
		size += ArrayCountPrefixSize
		for _, row := range plane {
			size += ArrayCountPrefixSize
			size += calc1DArraySize(arr.EleType, row)
		}
	}
	return size
}

func (arr *array3D[T]) GetEleType() uint16 {
	return arr.EleType
}

// WireMessage defines the interface that all generated message types implement.
type WireMessage interface {
	MessageTypeID() uint16
	Size() int
	DynamicPayloadSize() int
	Marshal() ([]byte, error)
	Unmarshal(reader io.Reader, fixedPayloadSize uint16, overallPayloadSize uint32) error
}

{{$overallMessages := .Messages}}
{{range .Messages}}{{$msg := .}}
// ---------------------------------------------------------------------------
// {{$msg.Name}}
// ---------------------------------------------------------------------------
// Wire Type ID: {{$msg.TypeID}}
// Fixed Block Length: {{$msg.TotalFixedSize}} bytes (includes alignment padding)
// Overall Block Length: {{$msg.TotalFixedSize}} bytes + Runtime dynamic payload
// ---------------------------------------------------------------------------

// TODO: Check order of fields in the struct to ensure they are ordered by offset to avoid padding issues.
// {{$msg.Name}} represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type {{$msg.Name}} struct {
{{- range $msg.Fields}}{{$field := .}}
{{- if $field.Description}}

	// {{$field.Description}}
{{- end}} {{/* $field.Description */}}
	{{$field.GoName}} {{goType $field $overallMessages true}} ` + "`" + `json:"{{$field.Name}}"` + "`" + `
{{- end}} {{/* range $msg.Fields */}}
}

// {{$msg.Name}}FixedSize is the byte size of the fixed block portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const {{$msg.Name}}FixedSize = {{$msg.TotalFixedSize}}

// MessageTypeID returns the unique wire protocol type identifier for {{$msg.Name}}.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func ({{receiver $msg.Name}} *{{$msg.Name}}) MessageTypeID() uint16 {
	return {{$msg.TypeID}}
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg {{$msg.Name}}
	_ = msg
{{- range $msg.Fields}}{{$field := .}}
{{- if not (isVariable $field.Type)}}
	if unsafe.Sizeof(msg.{{$field.GoName}}) != {{$field.Size}} {
		panic("wireforge: {{$msg.Name}}.{{$field.GoName}} size mismatch")
	}
{{- end}} {{/* not (isVariable $field.Type) */}}
{{- end}} {{/* range $msg.Fields */}}
}

func ({{receiver $msg.Name}} *{{$msg.Name}}) DynamicPayloadSize() int {
	dynamicSize := 0

{{- range $msg.VariableFields}}{{$field := .}}
{{- if eq (goBaseType $field.Type) "[]any"}}
	if len({{receiver $msg.Name}}.{{$field.GoName}}) > 0 {
		sizer := getArraySizer[{{arrayRootGoType $field $overallMessages true}}]({{arrayDimension $field}})
		sizer.SetElements({{receiver $msg.Name}}.{{$field.GoName}})
		dynamicSize += sizer.CalcSize()
	}
{{- else}}{{/* not eq (goBaseType $field.Type) "[]any" */}}
{{- if eq (goBaseType $field.Type) "struct"}}
	if {{receiver $msg.Name}}.{{$field.GoName}} != nil {
		dynamicSize += calcTypeSize({{receiver $msg.Name}}.{{$field.GoName}})
	}
{{- else}}{{/* not eq (goBaseType $field.Type) "struct" */}}
	if len({{receiver $msg.Name}}.{{$field.GoName}}) > 0 {
		dynamicSize += calcTypeSize({{receiver $msg.Name}}.{{$field.GoName}})
	}
{{- end}}{{/* if eq (goBaseType $field.Type) "struct" */}}
{{- end}}

{{- end}} {{/* range $msg.VariableFields */}}

	return dynamicSize
}

func ({{receiver $msg.Name}} *{{$msg.Name}}) Size() int {
	if {{receiver $msg.Name}} == nil {
		return 0
	}
	return FrameHeaderSize + {{$msg.Name}}FixedSize + {{receiver $msg.Name}}.DynamicPayloadSize()
}

// Marshal serializes the {{$msg.Name}} message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID ({{$msg.TypeID}})
//	[2:4]     Fixed Block Length ({{$msg.TotalFixedSize}})
//	[4:8]     Fixed and Dynamic Block Length
//	[8:{{add 8 $msg.TotalFixedSize}}]    Fixed payload (primitives + length prefixes, Big-Endian)
//	[{{add 8 $msg.TotalFixedSize}}:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func ({{receiver $msg.Name}} *{{$msg.Name}}) Marshal() ([]byte, error) {
	payloadSize := {{$msg.Name}}FixedSize + {{receiver $msg.Name}}.DynamicPayloadSize()
	totalSize := FrameHeaderSize + payloadSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("{{$msg.Name}} message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed payload length + overall payload length
	binary.BigEndian.PutUint16(buf[0:2], {{$msg.TypeID}})
	binary.BigEndian.PutUint16(buf[2:4], uint16({{$msg.Name}}FixedSize))
	binary.BigEndian.PutUint32(buf[4:8], uint32(payloadSize))

	// Fixed block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + {{$msg.Name}}FixedSize

{{range $msg.Fields}}{{$field := .}}
{{- if isVariable $field.Type}}

{{- if eq (goBaseType $field.Type) "struct"}}

	{{receiver $msg.Name}}_{{$field.GoName}}_len := 0
	if {{receiver $msg.Name}}.{{$field.GoName}} != nil {
		{{receiver $msg.Name}}_{{$field.GoName}}_Bytes, err := {{receiver $msg.Name}}.{{$field.GoName}}.Marshal()
		if err != nil {
			return nil, fmt.Errorf("wireforge: failed to marshal {{$msg.Name}}.{{$field.GoName}}: %v", err)
		}
		copy(buf[dynOff:], {{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
		dynOff += len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
		{{receiver $msg.Name}}_{{$field.GoName}}_len = len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	}
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32({{receiver $msg.Name}}_{{$field.GoName}}_len))
{{- else if eq (goBaseType $field.Type) "[]any"}}

	if len({{receiver $msg.Name}}.{{$field.GoName}}) > 0 {
		var zero {{(arrayRootGoType $field $overallMessages true)}}
		eleType{{$field.GoName}}, err := getElementType(zero)
		if err != nil {
			return nil, fmt.Errorf("wireforge: failed to marshal {{$msg.Name}}.{{$field.GoName}}: %v", err)
		}
		{{receiver $msg.Name}}_{{$field.GoName}}_Bytes, err := sliceToBytes[{{arrayRootGoType $field $overallMessages true}}](eleType{{$field.GoName}}, {{receiver $msg.Name}}.{{$field.GoName}})
		if err != nil {
			return nil, fmt.Errorf("wireforge: failed to marshal {{$msg.Name}}.{{$field.GoName}}: %v", err)
		}
		copy(buf[dynOff:], {{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
		binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32(len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)))
		dynOff += len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	}
{{- else}} {{/* eq (goBaseType $field.Type) "string" or "[]byte" */}}

	copy(buf[dynOff:], {{receiver $msg.Name}}.{{$field.GoName}})
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32(len({{receiver $msg.Name}}.{{$field.GoName}})))
	dynOff += len({{receiver $msg.Name}}.{{$field.GoName}})
{{- end}} {{/* eq (goBaseType $field.Type) */}}
{{- else}} {{/* isVariable $field.Type */}}
{{- if eq (goBaseType $field.Type) "uint8"}}
	hdr[{{$field.Offset}}] = {{receiver $msg.Name}}.{{$field.GoName}}
{{- else if eq (goBaseType $field.Type) "int8"}}
	hdr[{{$field.Offset}}] = uint8({{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "bool"}}
	if {{receiver $msg.Name}}.{{$field.GoName}} {
		hdr[{{$field.Offset}}] = 1
	} else {
		hdr[{{$field.Offset}}] = 0
	}
{{- else if eq (goBaseType $field.Type) "uint16"}}
	binary.BigEndian.PutUint16(hdr[{{$field.Offset}}:{{add $field.Offset 2}}], {{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "int16"}}
	binary.BigEndian.PutUint16(hdr[{{$field.Offset}}:{{add $field.Offset 2}}], uint16({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "uint32"}}
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], {{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "int32"}}
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "uint64"}}
	binary.BigEndian.PutUint64(hdr[{{$field.Offset}}:{{add $field.Offset 8}}], {{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "int64"}}
	binary.BigEndian.PutUint64(hdr[{{$field.Offset}}:{{add $field.Offset 8}}], uint64({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "float32"}}
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], math.Float32bits({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "float64"}}
	binary.BigEndian.PutUint64(hdr[{{$field.Offset}}:{{add $field.Offset 8}}], math.Float64bits({{receiver $msg.Name}}.{{$field.GoName}}))
{{- end}} {{/* eq (goBaseType $field.Type) */}}
{{- end}} {{/* isVariable $field.Type */}}
{{- end}} {{/* range $msg.Fields */}}

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a {{$msg.Name}} from the wire after the 8-byte frame
// header has already been consumed. The caller provides fixedPayloadSize (read
// from the frame) and overallPayloadSize so forward-compatible readers can skip
// unknown trailing bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func ({{receiver $msg.Name}} *{{$msg.Name}}) Unmarshal(reader io.Reader, fixedPayloadSize uint16,
	overallPayloadSize uint32) error {
	if int(fixedPayloadSize) < {{$msg.Name}}FixedSize || int(overallPayloadSize) > MaxAllowedPacket {
		return fmt.Errorf("wireforge: {{$msg.Name}} payload size mismatch: fixed %d, overall %d",
			fixedPayloadSize, overallPayloadSize)
	}

	hdr := make([]byte, fixedPayloadSize)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading {{$msg.Name}} fixed payload: %w", err)
	}

{{range $msg.Fields}}{{$field := .}}
{{- if isVariable $field.Type}}
	{{receiver $msg.Name}}_{{$field.GoName}}_len := binary.BigEndian.Uint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}])
	if {{receiver $msg.Name}}_{{$field.GoName}}_len > MaxAllowedPacket {
		return fmt.Errorf("{{$msg.Name}}.{{$field.GoName}} length %d exceeds MaxAllowedPacket", {{receiver $msg.Name}}_{{$field.GoName}}_len)
	}
{{- else}} {{/* not (isVariable $field.Type) */}}
{{- if eq (goBaseType $field.Type) "uint8"}}
	{{receiver $msg.Name}}.{{.GoName}} = hdr[{{.Offset}}]
{{- else if eq (goBaseType $field.Type) "int8"}}
	{{receiver $msg.Name}}.{{.GoName}} = int8(hdr[{{.Offset}}])
{{- else if eq (goBaseType $field.Type) "bool"}}
	{{receiver $msg.Name}}.{{.GoName}} = hdr[{{.Offset}}] != 0
{{- else if eq (goBaseType $field.Type) "uint16"}}
	{{receiver $msg.Name}}.{{.GoName}} = binary.BigEndian.Uint16(hdr[{{.Offset}}:{{add .Offset 2}}])
{{- else if eq (goBaseType $field.Type) "int16"}}
	{{receiver $msg.Name}}.{{.GoName}} = int16(binary.BigEndian.Uint16(hdr[{{.Offset}}:{{add .Offset 2}}]))
{{- else if eq (goBaseType $field.Type) "uint32"}}
	{{receiver $msg.Name}}.{{.GoName}} = binary.BigEndian.Uint32(hdr[{{.Offset}}:{{add .Offset 4}}])
{{- else if eq (goBaseType $field.Type) "int32"}}
	{{receiver $msg.Name}}.{{.GoName}} = int32(binary.BigEndian.Uint32(hdr[{{.Offset}}:{{add .Offset 4}}]))
{{- else if eq (goBaseType $field.Type) "uint64"}}
	{{receiver $msg.Name}}.{{.GoName}} = binary.BigEndian.Uint64(hdr[{{.Offset}}:{{add .Offset 8}}])
{{- else if eq (goBaseType $field.Type) "int64"}}
	{{receiver $msg.Name}}.{{.GoName}} = int64(binary.BigEndian.Uint64(hdr[{{.Offset}}:{{add .Offset 8}}]))
{{- else if eq (goBaseType $field.Type) "float32"}}
	{{receiver $msg.Name}}.{{.GoName}} = math.Float32frombits(binary.BigEndian.Uint32(hdr[{{.Offset}}:{{add .Offset 4}}]))
{{- else if eq (goBaseType $field.Type) "float64"}}
	{{receiver $msg.Name}}.{{.GoName}} = math.Float64frombits(binary.BigEndian.Uint64(hdr[{{.Offset}}:{{add .Offset 8}}]))
{{- end}} {{/* eq (goBaseType $field.Type) */}}
{{- end}} {{/* isVariable $field.Type */}}
{{- end}} {{/* range $msg.Fields */}}

{{- if hasVariable $msg}}

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed payload in the same order as their length prefixes above.
{{range $msg.VariableFields}}{{$field := .}}

	if {{receiver $msg.Name}}_{{$field.GoName}}_len > 0 {
{{- if eq (goBaseType $field.Type) "string"}}
		{{receiver $msg.Name}}_{{$field.GoName}}_buf := make([]byte, {{receiver $msg.Name}}_{{$field.GoName}}_len)
		if _, err := io.ReadFull(reader, {{receiver $msg.Name}}_{{$field.GoName}}_buf); err != nil {
			return fmt.Errorf("wireforge: reading {{$msg.Name}}.{{$field.GoName}} payload: %w", err)
		}
		{{receiver $msg.Name}}.{{$field.GoName}} = string({{receiver $msg.Name}}_{{$field.GoName}}_buf)
{{- else if eq (goBaseType $field.Type) "[]any"}}
		if int({{receiver $msg.Name}}_{{$field.GoName}}_len) < ArrayPrefixSize {
			return fmt.Errorf("wireforge: {{$msg.Name}}.{{$field.GoName}} length %d too short", {{receiver $msg.Name}}_{{$field.GoName}}_len)
		}

		{{receiver $msg.Name}}_{{$field.GoName}}_reader := io.LimitReader(reader, int64({{receiver $msg.Name}}_{{$field.GoName}}_len))
{{- $arrDim := arrayDimension $field}}
{{- if eq $arrDim 1}}
		err := validateReaderArrayPrefix[{{(arrayRootGoType $field $overallMessages true)}}]({{receiver $msg.Name}}_{{$field.GoName}}_reader, TagArray)
		if err != nil {
			return fmt.Errorf("wireforge: error reading {{$msg.Name}}.{{$field.GoName}} array prefix: %w", err)
		}

		{{receiver $msg.Name}}_{{$field.GoName}}_arr , err := readOneDimensionalSlice[{{(arrayRootGoType $field $overallMessages true)}}]({{receiver $msg.Name}}_{{$field.GoName}}_reader)
{{- else if eq $arrDim 2}}
		err := validateReaderArrayPrefix[{{(arrayRootGoType $field $overallMessages true)}}]({{receiver $msg.Name}}_{{$field.GoName}}_reader, Tag2DArray)
		if err != nil {
			return fmt.Errorf("wireforge: error reading {{$msg.Name}}.{{$field.GoName}} array prefix: %w", err)
		}

		{{receiver $msg.Name}}_{{$field.GoName}}_arr , err := readTwoDimensionalSlice[{{(arrayRootGoType $field $overallMessages true)}}]({{receiver $msg.Name}}_{{$field.GoName}}_reader)
{{- else if eq $arrDim 3}}
		err := validateReaderArrayPrefix[{{(arrayRootGoType $field $overallMessages true)}}]({{receiver $msg.Name}}_{{$field.GoName}}_reader, Tag3DArray)	
		if err != nil {
			return fmt.Errorf("wireforge: error reading {{$msg.Name}}.{{$field.GoName}} array prefix: %w", err)
		}

		{{receiver $msg.Name}}_{{$field.GoName}}_arr , err := readThreeDimensionalSlice[{{(arrayRootGoType $field $overallMessages true)}}]({{receiver $msg.Name}}_{{$field.GoName}}_reader)
{{- else}}
		err := fmt.Errorf("wireforge: {{$msg.Name}}.{{$field.GoName}} has unsupported array type")
{{- end}}
		if err != nil {
			return fmt.Errorf("wireforge: reading {{$msg.Name}}.{{$field.GoName}} array: %w", err)
		}

		{{receiver $msg.Name}}.{{$field.GoName}} = {{receiver $msg.Name}}_{{$field.GoName}}_arr
{{- else if eq (goBaseType $field.Type) "struct"}}
		{{receiver $msg.Name}}_{{$field.GoName}}_reader := io.LimitReader(reader, int64({{receiver $msg.Name}}_{{$field.GoName}}_len))

		typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame({{receiver $msg.Name}}_{{$field.GoName}}_reader)
		if err != nil {
			return fmt.Errorf("wireforge: reading {{$msg.Name}}.{{$field.GoName}} frame header: %w", err)
		}

		var {{lower $field.GoName}} {{(goType $field $overallMessages false)}}
		if typeID != {{lower $field.GoName}}.MessageTypeID() {
			return fmt.Errorf("wireforge: unexpected type ID %d for {{$msg.Name}}.{{$field.GoName}}, expected %d", typeID, {{lower $field.GoName}}.MessageTypeID())
		}

		if err := {{lower $field.GoName}}.Unmarshal({{receiver $msg.Name}}_{{$field.GoName}}_reader, fixedPayloadLen, overallPayloadLen); err != nil {
			return fmt.Errorf("wireforge: unmarshalling {{$msg.Name}}.{{$field.GoName}}: %w", err)
		}
		{{receiver $msg.Name}}.{{$field.GoName}} = &{{lower $field.GoName}}
{{- else}} {{/* eq (goBaseType $field.Type) "[]byte" */}}
		{{receiver $msg.Name}}_{{$field.GoName}}_buf := make([]byte, {{receiver $msg.Name}}_{{$field.GoName}}_len)
		if _, err := io.ReadFull(reader, {{receiver $msg.Name}}_{{$field.GoName}}_buf); err != nil {
			return fmt.Errorf("reading {{$msg.Name}}.{{$field.GoName}} payload: %w", err)
		}
		{{receiver $msg.Name}}.{{$field.GoName}} = {{receiver $msg.Name}}_{{$field.GoName}}_buf
{{- end}} {{/* eq (goBaseType $field.Type)*/}}
	}
{{- end}} {{/* range $msg.VariableFields */}}
{{- end}} {{/* hasVariable $msg */}}

	return nil
}
{{end}} {{/* range .Messages */}}

// ReadMessageFrame reads the 8-byte wire frame header from r and returns the
// message type ID, fixed & overall payload length. Use this when you need to dispatch
// to different message types based on the type ID before calling Unmarshal.
func ReadMessageFrame(r io.Reader) (uint16, uint16, uint32, error) {
	var frame [FrameHeaderSize]byte
	if _, err := io.ReadFull(r, frame[:]); err != nil {
		return 0, 0, 0, err
	}
	typeID := binary.BigEndian.Uint16(frame[0:2])
	fixedPayloadLen := binary.BigEndian.Uint16(frame[2:4])
	overallPayloadLen := binary.BigEndian.Uint32(frame[4:8])

	return typeID, fixedPayloadLen, overallPayloadLen, nil
}

// ---------------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------------

func calc1DArraySize[T any](eleType uint16, arr []T) int {
	eleBytes := 0
	switch eleType {
	case TagBool, TagInt8, TagUint8:
		eleBytes = 1
	case TagInt16, TagUint16:
		eleBytes = 2
	case TagInt32, TagUint32, TagFloat32:
		eleBytes = 4
	case TagInt64, TagUint64, TagFloat64:
		eleBytes = 8
	default:
		eleBytes = 0
	}

	getSizableSize := func(innerArr []T) int {
		size := 0
		for _, item := range innerArr {
			sizableItem, ok := any(item).(Sizable)
			if !ok {
				panic("item does not implement Sizable interface")
			}
			size += ObjectSetUnsetPrefixSize
			if sizableItem == nil {
				continue
			}
			size += sizableItem.Size()
		}
		return size
	}

	switch eleType {
	case TagBool, TagInt8, TagUint8, TagInt16, TagUint16, TagInt32, TagUint32, TagFloat32, TagInt64, TagUint64, TagFloat64:
		return len(arr) * eleBytes
	case TagString:
		size := 0
		for _, item := range arr {
			str, ok := any(item).(string)
			if !ok {
				panic("item is not a string")
			}
			size += StrOrByteLenPrefixSize + len(str)
		}
		return size
	case TagBytes:
		size := 0
		for _, item := range arr {
			bytes, ok := any(item).([]byte)
			if !ok {
				panic("item is not a []byte")
			}
			size += StrOrByteLenPrefixSize + len(bytes)
		}
		return size
{{range .Messages}}{{$msg := .}}
	case Tag{{$msg.Name}}:
		return getSizableSize(arr)
{{end}} {{/* range .Messages */}}
	default:
		return 0
	}
}

func calcTypeSize(ele any) int {
	switch val := ele.(type) {
	// Primitives
	case bool, int8, uint8:
		return 1
	case int16, uint16:
		return 2
	case int32, uint32, float32:
		return 4
	case int64, uint64, float64:
		return 8

	// Strings & Byte Slices
	case string:
		return len(val)
	case []byte:
		return len(val)

	case Sizable:
		if val != nil {
			return val.Size()
		}
		return 0

	default:
		panic(fmt.Sprintf("calcTypeSize: unsupported type %T", val))
	}
}

func sliceToBytes[T any](eleType uint16, elements any) ([]byte, error) {	
	switch arr := elements.(type) {
	case []T:
		overallItemsCount, arrBytes, err := oneDimensionalSliceToBytes(arr)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize 1D slice: %w", err)
		}
		result := make([]byte, (TypeMarkerSize * 2) + ArrayCountPrefixSize + len(arrBytes))
		binary.BigEndian.PutUint16(result[0:], TagArray)
		binary.BigEndian.PutUint16(result[2:], eleType)
		binary.BigEndian.PutUint16(result[4:], uint16(overallItemsCount))
		copy(result[6:], arrBytes)
		return result, nil

	case [][]T:
		overallItemsCount, arrBytes, err := twoDimensionalSliceToBytes(arr)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize 2D slice: %w", err)
		}
		result := make([]byte, (TypeMarkerSize * 2) + ArrayCountPrefixSize + len(arrBytes))
		binary.BigEndian.PutUint16(result[0:], Tag2DArray)
		binary.BigEndian.PutUint16(result[2:], eleType)
		binary.BigEndian.PutUint16(result[4:], uint16(overallItemsCount))
		copy(result[6:], arrBytes)
		return result, nil

	case [][][]T:
		overallItemsCount, arrBytes, err := threeDimensionalSliceToBytes(arr)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize 3D slice: %w", err)
		}
		result := make([]byte, (TypeMarkerSize * 2) + ArrayCountPrefixSize + len(arrBytes))
		binary.BigEndian.PutUint16(result[0:], Tag3DArray)
		binary.BigEndian.PutUint16(result[2:], eleType)
		binary.BigEndian.PutUint16(result[4:], uint16(overallItemsCount))
		copy(result[6:], arrBytes)
		return result, nil

	default:
		return nil, fmt.Errorf("unsupported slice type: %T", arr)
	}
}

func threeDimensionalSliceToBytes[T any](elements [][][]T) (int, []byte, error) {
	count := len(elements)
	if count == 0 {
		return 0, binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > int(MaxArrayElements) {
		return 0, nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	itemsCount := 0
	buf := make([]byte, ArrayCountPrefixSize, 512)
	binary.BigEndian.PutUint16(buf[0:], uint16(count))
	for i, v := range elements {
		n, bytes, err := twoDimensionalSliceToBytes(v)
		if err != nil {
			return 0, nil, fmt.Errorf("failed to serialize 2D slice at index %d: %w", i, err)
		}
		buf = append(buf, bytes...)
		itemsCount += n
		
	}
	return itemsCount, buf, nil
}

func twoDimensionalSliceToBytes[T any](elements [][]T) (int, []byte, error) {
	count := len(elements)
	if count == 0 {
		return 0, binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > int(MaxArrayElements) {
		return 0, nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	itemsCount := 0
	buf := make([]byte, ArrayCountPrefixSize, 256)
	binary.BigEndian.PutUint16(buf[0:], uint16(count))
	for i, v := range elements {
		n, bytes, err := oneDimensionalSliceToBytes(v)
		if err != nil {
			return 0, nil, fmt.Errorf("failed to serialize 1D slice at index %d: %w", i, err)
		}
		buf = append(buf, bytes...)
		itemsCount += n
	}
	return itemsCount, buf, nil
}

func oneDimensionalSliceToBytes[T any](elements []T) (int, []byte, error) {
	count := len(elements)
	if count == 0 {
		return 0, binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > int(MaxArrayElements) {
		return 0, nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	switch sl := any(elements).(type) {
	// --- 1-Byte Primitives ---
	case []bool:
		buf := make([]byte, ArrayCountPrefixSize+count)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			if v {
				buf[ArrayCountPrefixSize+i] = 1
			} else {
				buf[ArrayCountPrefixSize+i] = 0
			}
		}
		return count, buf, nil

	case []uint8:
		buf := make([]byte, ArrayCountPrefixSize+count)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		copy(buf[ArrayCountPrefixSize:], sl)
		return count, buf, nil

	case []int8:
		buf := make([]byte, ArrayCountPrefixSize+count)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			buf[ArrayCountPrefixSize+i] = byte(v)
		}
		return count, buf, nil

	// --- 2-Byte Primitives ---
	case []uint16:
		buf := make([]byte, ArrayCountPrefixSize+(count*2))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint16(buf[ArrayCountPrefixSize+i*2:], v)
		}
		return count, buf, nil

	case []int16:
		buf := make([]byte, ArrayCountPrefixSize+(count*2))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint16(buf[ArrayCountPrefixSize+i*2:], uint16(v))
		}
		return count, buf, nil

	// --- 4-Byte Primitives ---
	case []uint32:
		buf := make([]byte, ArrayCountPrefixSize+(count*4))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint32(buf[ArrayCountPrefixSize+i*4:], v)
		}
		return count, buf, nil

	case []int32:
		buf := make([]byte, ArrayCountPrefixSize+(count*4))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint32(buf[ArrayCountPrefixSize+i*4:], uint32(v))
		}
		return count, buf, nil

	case []float32:
		buf := make([]byte, ArrayCountPrefixSize+(count*4))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint32(buf[ArrayCountPrefixSize+i*4:], math.Float32bits(v))
		}
		return count, buf, nil

	// --- 8-Byte Primitives ---
	case []uint64:
		buf := make([]byte, ArrayCountPrefixSize+(count*8))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint64(buf[ArrayCountPrefixSize+i*8:], v)
		}
		return count, buf, nil

	case []int64:
		buf := make([]byte, ArrayCountPrefixSize+(count*8))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint64(buf[ArrayCountPrefixSize+i*8:], uint64(v))
		}
		return count, buf, nil

	case []float64:
		buf := make([]byte, ArrayCountPrefixSize+(count*8))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint64(buf[ArrayCountPrefixSize+i*8:], math.Float64bits(v))
		}
		return count, buf, nil

	// --- Variable-Length Sequences ---
	case []string:
		totalSize := 0
		for _, v := range sl {
			totalSize += StrOrByteLenPrefixSize + len(v)
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			binary.BigEndian.PutUint32(buf[dynOff:], uint32(len(v)))
			dynOff += StrOrByteLenPrefixSize
			copy(buf[dynOff:], v)
			dynOff += len(v)
		}
		return count, buf, nil

	case [][]byte:
		totalSize := 0
		for _, v := range sl {
			totalSize += StrOrByteLenPrefixSize + len(v)
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			binary.BigEndian.PutUint32(buf[dynOff:], uint32(len(v)))
			dynOff += StrOrByteLenPrefixSize
			copy(buf[dynOff:], v)
			dynOff += len(v)
		}
		return count, buf, nil
{{range .Messages}}{{$msg := .}}
	case []*{{$msg.Name}}:
		totalSize := 0
		for _, v := range sl {
			totalSize += ObjectSetUnsetPrefixSize
			if v == nil {
				continue
			}
			totalSize += v.Size()
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			if v == nil {
				buf[dynOff] = 0
				dynOff += ObjectSetUnsetPrefixSize
				continue
			}
			buf[dynOff] = 1
			dynOff += ObjectSetUnsetPrefixSize

			b, err := v.Marshal()
			if err != nil {
				return 0, nil, fmt.Errorf("failed to serialize *{{$msg.Name}} element: %w", err)
			}
			copy(buf[dynOff:], b)
			dynOff += len(b)
		}
		return count, buf, nil
{{end}} {{/* range .Messages */}}
	default:
		var zero T
		return 0, nil, fmt.Errorf("unsupported primitive type: %T", zero)
	}
}

func validateReaderArrayPrefix[T any](r io.Reader, expectedArrType uint16) error {
	arrType, err := readUint16(r)
	if err != nil {
		return fmt.Errorf("error reading array type marker: %w", err)
	}

	if arrType != expectedArrType {
		return fmt.Errorf("unexpected array type marker: got %d, expected %d", arrType, expectedArrType)
	}

	eleType, err := readUint16(r)
	if err != nil {
		return fmt.Errorf("error reading element type marker: %w", err)
	}

	var zero T
	expectedEleType, err := getElementType(zero)
	if err != nil {
		return fmt.Errorf("error reading element type marker: %w", err)
	}

	if eleType != expectedEleType {
		return fmt.Errorf("unexpected element type marker: got %d, expected %d", eleType, expectedEleType)
	}

	// Skip the overall items count written by sliceToBytes
	_, err = readUint16(r)
	if err != nil {
		return fmt.Errorf("error reading overall items count: %w", err)
	}

	return nil
}

func readThreeDimensionalSlice[T any](r io.Reader) ([][][]T, error) {
	count, err := readUint16(r)
	if err != nil {
		return nil, fmt.Errorf("failed to read 3D array count: %w", err)
	}

	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	if count == 0 {
		return nil, nil
	}

	// Read the 3D array elements
	slice := make([][][]T, count)
	for i := 0; i < int(count); i++ {
		innerSlice, err := readTwoDimensionalSlice[T](r)
		if err != nil {
			return nil, fmt.Errorf("failed to read 3D array element at index %d: %w", i, err)
		}

		slice[i] = innerSlice
	}
	return slice, nil
}

func readTwoDimensionalSlice[T any](r io.Reader) ([][]T, error) {
	count, err := readUint16(r)
	if err != nil {
		return nil, fmt.Errorf("failed to read 2D array count: %w", err)
	}

	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	if count == 0 {
		return nil, nil
	}
	
	// Read the 2D array elements
	slice := make([][]T, count)
	for i := 0; i < int(count); i++ {
		innerSlice, err := readOneDimensionalSlice[T](r)
		if err != nil {
			return nil, fmt.Errorf("failed to read 2D array element at index %d: %w", i, err)
		}

		slice[i] = innerSlice
	}
	return slice, nil
}

func readOneDimensionalSlice[T any](r io.Reader) ([]T, error) {
	count, err := readUint16(r)
	if err != nil {
		return nil, fmt.Errorf("failed to read 1D array count: %w", err)
	}
	
	if count == 0 {
		return nil, nil
	}
	
	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	slice := make([]T, count)

	// Read the 1D array elements
	switch sl := any(slice).(type) {
	// --- 1-Byte Primitives ---
	case []uint8:
		if _, err := io.ReadFull(r, sl); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
	case []int8:
		data := make([]byte, count)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int8(data[i])
		}
	case []bool:
		data := make([]byte, count)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = data[i] != 0
		}
	
	// --- 2-Byte Primitives ---
	case []uint16:
		data := make([]byte, count * 2)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = binary.BigEndian.Uint16(data[i*2:])
		}
	case []int16:
		data := make([]byte, count * 2)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int16(binary.BigEndian.Uint16(data[i*2:]))
		}

	// --- 4-Byte Primitives ---
	case []uint32:
		data := make([]byte, count * 4)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = binary.BigEndian.Uint32(data[i*4:])
		}
	case []int32:
		data := make([]byte, count * 4)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int32(binary.BigEndian.Uint32(data[i*4:]))
		}
	case []float32:
		data := make([]byte, count * 4)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = math.Float32frombits(binary.BigEndian.Uint32(data[i*4:]))
		}

	// --- 8-Byte Primitives ---
	case []uint64:
		data := make([]byte, count * 8)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = binary.BigEndian.Uint64(data[i*8:])
		}
	case []int64:
		data := make([]byte, count * 8)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int64(binary.BigEndian.Uint64(data[i*8:]))
		}
	case []float64:
		data := make([]byte, count * 8)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = math.Float64frombits(binary.BigEndian.Uint64(data[i*8:]))
		}

	// --- Variable-Length Sequences ---
	case []string:
		for i := range sl {
			length, err := readUint32(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read string length at index %d: %w", i, err)
			}
			if length > MaxAllowedPacket {
				return nil, fmt.Errorf("string length %d exceeds MaxAllowedPacket at index %d", length, i)
			}

			buf := make([]byte, length)
			if _, err := io.ReadFull(r, buf); err != nil {
				return nil, fmt.Errorf("failed to read string data at index %d: %w", i, err)
			}
			sl[i] = string(buf)
		}
	case [][]byte:
		for i := range sl {
			length, err := readUint32(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read []byte length at index %d: %w", i, err)
			}
			if length > MaxAllowedPacket {
				return nil, fmt.Errorf("[]byte length %d exceeds MaxAllowedPacket at index %d", length, i)
			}

			sl[i] = nil
			if length > 0 {
				buf := make([]byte, length)
				if _, err := io.ReadFull(r, buf); err != nil {
					return nil, fmt.Errorf("failed to read []byte data at index %d: %w", i, err)
				}
				sl[i] = buf
			}
		}
{{range .Messages}}{{$msg := .}}
	case []*{{$msg.Name}}:
		for i := range sl {
			set, err := readUint8(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read object set/unset prefix for *{{$msg.Name}} at index %d: %w", i, err)
			}

			if set == 0 {
				sl[i] = nil
				continue
			}

			typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read frame header for *{{$msg.Name}} at index %d: %w", i, err)
			}
			
			var msg {{$msg.Name}}
			if typeID != msg.MessageTypeID() {
				return nil, fmt.Errorf("unexpected type ID %d for {{$msg.Name}}, expected %d", typeID, msg.MessageTypeID())
			}

			{{$msg.Name}}_reader := io.LimitReader(r, int64(overallPayloadLen))
			if err := msg.Unmarshal({{$msg.Name}}_reader, fixedPayloadLen, overallPayloadLen); err != nil {
				return nil, fmt.Errorf("failed to deserialize {{$msg.Name}}: %w", err)
			}
			sl[i] = &msg
		}
{{end}} {{/* range .Messages */}}
	default:
		return nil, fmt.Errorf("unsupported array element type")
	}

	return slice, nil
}

func getElementType(item any) (uint16, error) {
	switch item.(type) {
	case bool:
		return TagBool, nil
	case int8:
		return TagInt8, nil
	case uint8:
		return TagUint8, nil
	case int16:
		return TagInt16, nil
	case uint16:
		return TagUint16, nil
	case int32:
		return TagInt32, nil
	case uint32:
		return TagUint32, nil
	case float32:
		return TagFloat32, nil
	case int64:
		return TagInt64, nil
	case uint64:
		return TagUint64, nil
	case float64:
		return TagFloat64, nil
	case string:
		return TagString, nil
	case []byte:
		return TagBytes, nil
{{range .Messages}}{{$msg := .}}
	case *{{$msg.Name}}:
		return Tag{{$msg.Name}}, nil
{{end}} {{/* range .Messages */}}
	default:
		return 0, fmt.Errorf("unsupported type: %T", item)
	}
}

func getArraySizer[T any](dimensions int) ArraySizer {
	var zero T
	elemType, err := getElementType(zero)
	if err != nil {
		panic(fmt.Errorf("unsupported type for array sizer: %T", zero))
	}
	switch dimensions {
	case 1:
		return &array1D[T]{EleType: elemType}
	case 2:
		return &array2D[T]{EleType: elemType}
	case 3:
		return &array3D[T]{EleType: elemType}
	default:
		panic(fmt.Errorf("unsupported array dimensions: %d", dimensions))
	}
}

func readUint8(r io.Reader) (uint8, error) {
	var buf [1]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return buf[0], nil
}

func readUint32(r io.Reader) (uint32, error) {
	var buf [4]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return binary.BigEndian.Uint32(buf[:]), nil
}

func readUint16(r io.Reader) (uint16, error) {
	var buf [2]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return binary.BigEndian.Uint16(buf[:]), nil
}
`
