// Copyright (c) 2026 Sachin S. All rights reserved.
// 
// Licensed under the MIT License.
// See LICENSE in the project root.

package codegen

import (
	"io"
	"strings"
	"text/template"

	"github.com/avatar31/wireforge/internal/compiler"
	"github.com/avatar31/wireforge/internal/schema"
)

var goTemplate = template.Must(template.New("go").Funcs(template.FuncMap{
	"lower":       strings.ToLower,
	"goType":      func(ft schema.FieldType) string { return ft.GoType() },
	"isVariable":  func(ft schema.FieldType) bool { return ft.IsVariable() },
	"sub":         func(a, b int) int { return a - b },
	"add":         func(a, b int) int { return a + b },
	"receiver":    func(name string) string { return strings.ToLower(name[:1]) },
	"hasVariable": func(msg *compiler.CompiledMessage) bool { return len(msg.VariableFields) > 0 },
}).Parse(goTemplateSource))

// GenerateGo writes the generated Go source to w.
func GenerateGo(w io.Writer, cs *compiler.CompiledSchema) error {
	return goTemplate.Execute(w, cs)
}

const goTemplateSource = `// Code generated by wireforge. DO NOT EDIT.
//
// This file contains type-safe message definitions with binary serialization
// for a length-prefixed wire protocol. All multi-byte integers are encoded in
// Big-Endian (network byte order) to ensure cross-platform compatibility.
//
// Wire Protocol Layout (per message):
//
//	[Message Type ID : 2 bytes, Big-Endian uint16]
//	[Fixed Header Length : 2 bytes, Big-Endian uint16]
//	[Fixed Header Block : N bytes, padded for natural alignment]
//	[Dynamic Payload : variable length, concatenated string/byte data]
//
// Safety guarantees:
//   - MaxAllowedPacket (16 MB) prevents memory allocation exploits from
//     corrupted length fields ("poison pill" attack mitigation).
//   - init() performs compile-time layout validation via unsafe.Sizeof to
//     catch struct size mismatches between the generator and the Go compiler.
//   - All reads use io.ReadFull to handle socket short-reads correctly.
//   - Big-Endian encoding ensures consistent behavior across architectures.
package {{.PackageName}}

import (
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"unsafe"
)

const (
	// FrameHeaderSize represents the 2 bytes for TypeID and 2 bytes for FixedHeaderLen.
	FrameHeaderSize = 4

	// MaxAllowedPacket is the hard ceiling on any single message size (16 MB).
	// Any incoming length field exceeding this value is treated as corrupted
	// data and rejected immediately, preventing denial-of-service via
	// malicious allocation requests.
	MaxAllowedPacket = 16 * 1024 * 1024
)

// Compile-time import usage guarantees.
var (
	_ = binary.BigEndian
	_ = fmt.Errorf
	_ = io.ReadFull
	_ = math.Float32frombits
	_ = unsafe.Sizeof(uint8(0))
)
{{range .Messages}}{{$msg := .}}
// ---------------------------------------------------------------------------
// {{$msg.Name}}
// ---------------------------------------------------------------------------
// Wire Type ID: {{$msg.TypeID}}
// Fixed Header: {{$msg.TotalFixedSize}} bytes (includes alignment padding)
// ---------------------------------------------------------------------------

// {{$msg.Name}} represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type {{$msg.Name}} struct {
{{- range $msg.Fields}}
{{- if .Description}}
	// {{.Description}}
{{- end}}
	{{.GoName}} {{goType .Type}}
{{- end}}
}

// {{$msg.Name}}FixedSize is the byte size of the fixed header portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const {{$msg.Name}}FixedSize = {{$msg.TotalFixedSize}}

// MessageTypeID returns the unique wire protocol type identifier for {{$msg.Name}}.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func ({{receiver $msg.Name}} *{{$msg.Name}}) MessageTypeID() uint16 {
	return {{$msg.TypeID}}
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg {{$msg.Name}}
	_ = msg
{{- range $msg.Fields}}
{{- if not (isVariable .Type)}}
	if unsafe.Sizeof(msg.{{.GoName}}) != {{.Size}} {
		panic("wireforge: {{$msg.Name}}.{{.GoName}} size mismatch")
	}
{{- end}}
{{- end}}
}

// Marshal serializes the {{$msg.Name}} message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID ({{$msg.TypeID}})
//	[2:4]     Fixed Header Length ({{$msg.TotalFixedSize}})
//	[4:{{add 4 $msg.TotalFixedSize}}]    Fixed header (primitives + length prefixes, Big-Endian)
//	[{{add 4 $msg.TotalFixedSize}}:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func ({{receiver $msg.Name}} *{{$msg.Name}}) Marshal() ([]byte, error) {
	dynamicSize := 0
{{- range $msg.VariableFields}}
	dynamicSize += len({{receiver $msg.Name}}.{{.GoName}})
{{- end}}

	totalSize := FrameHeaderSize + {{$msg.Name}}FixedSize + dynamicSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("{{$msg.Name}} message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed header length
	binary.BigEndian.PutUint16(buf[0:2], {{$msg.TypeID}})
	binary.BigEndian.PutUint16(buf[2:4], uint16({{$msg.Name}}FixedSize))

	// Fixed header block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + {{$msg.Name}}FixedSize

{{range $msg.Fields}}
{{- if isVariable .Type}}
	binary.BigEndian.PutUint32(hdr[{{.Offset}}:{{add .Offset 4}}], uint32(len({{receiver $msg.Name}}.{{.GoName}})))
	copy(buf[dynOff:], {{receiver $msg.Name}}.{{.GoName}})
	dynOff += len({{receiver $msg.Name}}.{{.GoName}})
{{- else}}
{{- if eq (goType .Type) "uint8"}}
	hdr[{{.Offset}}] = {{receiver $msg.Name}}.{{.GoName}}
{{- else if eq (goType .Type) "int8"}}
	hdr[{{.Offset}}] = uint8({{receiver $msg.Name}}.{{.GoName}})
{{- else if eq (goType .Type) "bool"}}
	if {{receiver $msg.Name}}.{{.GoName}} {
		hdr[{{.Offset}}] = 1
	} else {
		hdr[{{.Offset}}] = 0
	}
{{- else if eq (goType .Type) "uint16"}}
	binary.BigEndian.PutUint16(hdr[{{.Offset}}:{{add .Offset 2}}], {{receiver $msg.Name}}.{{.GoName}})
{{- else if eq (goType .Type) "int16"}}
	binary.BigEndian.PutUint16(hdr[{{.Offset}}:{{add .Offset 2}}], uint16({{receiver $msg.Name}}.{{.GoName}}))
{{- else if eq (goType .Type) "uint32"}}
	binary.BigEndian.PutUint32(hdr[{{.Offset}}:{{add .Offset 4}}], {{receiver $msg.Name}}.{{.GoName}})
{{- else if eq (goType .Type) "int32"}}
	binary.BigEndian.PutUint32(hdr[{{.Offset}}:{{add .Offset 4}}], uint32({{receiver $msg.Name}}.{{.GoName}}))
{{- else if eq (goType .Type) "uint64"}}
	binary.BigEndian.PutUint64(hdr[{{.Offset}}:{{add .Offset 8}}], {{receiver $msg.Name}}.{{.GoName}})
{{- else if eq (goType .Type) "int64"}}
	binary.BigEndian.PutUint64(hdr[{{.Offset}}:{{add .Offset 8}}], uint64({{receiver $msg.Name}}.{{.GoName}}))
{{- else if eq (goType .Type) "float32"}}
	binary.BigEndian.PutUint32(hdr[{{.Offset}}:{{add .Offset 4}}], math.Float32bits({{receiver $msg.Name}}.{{.GoName}}))
{{- else if eq (goType .Type) "float64"}}
	binary.BigEndian.PutUint64(hdr[{{.Offset}}:{{add .Offset 8}}], math.Float64bits({{receiver $msg.Name}}.{{.GoName}}))
{{- end}}
{{- end}}
{{- end}}

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a {{$msg.Name}} from the wire after the 4-byte frame
// header has already been consumed. The caller provides fixedHeaderLen (read
// from the frame) so forward-compatible readers can skip unknown trailing
// bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func ({{receiver $msg.Name}} *{{$msg.Name}}) Unmarshal(reader io.Reader, fixedHeaderLen uint16) error {
	if int(fixedHeaderLen) < {{$msg.Name}}FixedSize {
		return fmt.Errorf("{{$msg.Name}} fixed header too short: got %d, need %d", fixedHeaderLen, {{$msg.Name}}FixedSize)
	}

	hdr := make([]byte, fixedHeaderLen)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading {{$msg.Name}} fixed header: %w", err)
	}

{{range $msg.Fields}}
{{- if isVariable .Type}}
	{{receiver $msg.Name}}_{{.GoName}}_len := binary.BigEndian.Uint32(hdr[{{.Offset}}:{{add .Offset 4}}])
	if {{receiver $msg.Name}}_{{.GoName}}_len > MaxAllowedPacket {
		return fmt.Errorf("{{$msg.Name}}.{{.GoName}} length %d exceeds MaxAllowedPacket", {{receiver $msg.Name}}_{{.GoName}}_len)
	}
{{- else}}
{{- if eq (goType .Type) "uint8"}}
	{{receiver $msg.Name}}.{{.GoName}} = hdr[{{.Offset}}]
{{- else if eq (goType .Type) "int8"}}
	{{receiver $msg.Name}}.{{.GoName}} = int8(hdr[{{.Offset}}])
{{- else if eq (goType .Type) "bool"}}
	{{receiver $msg.Name}}.{{.GoName}} = hdr[{{.Offset}}] != 0
{{- else if eq (goType .Type) "uint16"}}
	{{receiver $msg.Name}}.{{.GoName}} = binary.BigEndian.Uint16(hdr[{{.Offset}}:{{add .Offset 2}}])
{{- else if eq (goType .Type) "int16"}}
	{{receiver $msg.Name}}.{{.GoName}} = int16(binary.BigEndian.Uint16(hdr[{{.Offset}}:{{add .Offset 2}}]))
{{- else if eq (goType .Type) "uint32"}}
	{{receiver $msg.Name}}.{{.GoName}} = binary.BigEndian.Uint32(hdr[{{.Offset}}:{{add .Offset 4}}])
{{- else if eq (goType .Type) "int32"}}
	{{receiver $msg.Name}}.{{.GoName}} = int32(binary.BigEndian.Uint32(hdr[{{.Offset}}:{{add .Offset 4}}]))
{{- else if eq (goType .Type) "uint64"}}
	{{receiver $msg.Name}}.{{.GoName}} = binary.BigEndian.Uint64(hdr[{{.Offset}}:{{add .Offset 8}}])
{{- else if eq (goType .Type) "int64"}}
	{{receiver $msg.Name}}.{{.GoName}} = int64(binary.BigEndian.Uint64(hdr[{{.Offset}}:{{add .Offset 8}}]))
{{- else if eq (goType .Type) "float32"}}
	{{receiver $msg.Name}}.{{.GoName}} = math.Float32frombits(binary.BigEndian.Uint32(hdr[{{.Offset}}:{{add .Offset 4}}]))
{{- else if eq (goType .Type) "float64"}}
	{{receiver $msg.Name}}.{{.GoName}} = math.Float64frombits(binary.BigEndian.Uint64(hdr[{{.Offset}}:{{add .Offset 8}}]))
{{- end}}
{{- end}}
{{- end}}

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed header in the same order as their length prefixes above.
{{- range $msg.VariableFields}}
	if {{receiver $msg.Name}}_{{.GoName}}_len > 0 {
		{{receiver $msg.Name}}_{{.GoName}}_buf := make([]byte, {{receiver $msg.Name}}_{{.GoName}}_len)
		if _, err := io.ReadFull(reader, {{receiver $msg.Name}}_{{.GoName}}_buf); err != nil {
			return fmt.Errorf("reading {{$msg.Name}}.{{.GoName}} payload: %w", err)
		}
{{- if eq (goType .Type) "string"}}
		{{receiver $msg.Name}}.{{.GoName}} = string({{receiver $msg.Name}}_{{.GoName}}_buf)
{{- else}}
		{{receiver $msg.Name}}.{{.GoName}} = {{receiver $msg.Name}}_{{.GoName}}_buf
{{- end}}
	}
{{- end}}

	return nil
}
{{end}}

// ReadMessageFrame reads the 4-byte wire frame header from r and returns the
// message type ID and fixed header length. Use this when you need to dispatch
// to different message types based on the type ID before calling Unmarshal.
func ReadMessageFrame(r io.Reader) (typeID uint16, fixedHeaderLen uint16, err error) {
	var frame [FrameHeaderSize]byte
	if _, err = io.ReadFull(r, frame[:]); err != nil {
		return 0, 0, err
	}
	typeID = binary.BigEndian.Uint16(frame[0:2])
	fixedHeaderLen = binary.BigEndian.Uint16(frame[2:4])

	return typeID, fixedHeaderLen, nil
}
`
