// Copyright (c) 2026 Sachin S. All rights reserved.
//
// Licensed under the MIT License.
// See LICENSE in the project root.

package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"strings"
	"text/template"

	"github.com/avatar31/wireforge/internal/compiler"
	"github.com/avatar31/wireforge/internal/schema"
)

var goTemplate = template.Must(template.New("go").Funcs(template.FuncMap{
	"lower":       strings.ToLower,
	"goBaseType":  func(ft schema.FieldType) string { return ft.GoType() },
	"goType":      goType,
	"isVariable":  func(ft schema.FieldType) bool { return ft.IsVariable() },
	"size":        func(ft schema.FieldType) int { return ft.Size() },
	"sub":         func(a, b int) int { return a - b },
	"add":         func(a, b int) int { return a + b },
	"receiver":    func(name string) string { return strings.ToLower(name[:1]) },
	"hasVariable": func(msg *compiler.CompiledMessage) bool { return len(msg.VariableFields) > 0 },
}).Parse(goTemplateSource))

// GenerateGo writes the generated Go source to w.
func GenerateGo(w io.Writer, cs *compiler.CompiledSchema) error {
	var buf bytes.Buffer
	err := goTemplate.Execute(&buf, cs)
	if err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Print("Warning: failed to format go generated code")
		_, _ = w.Write(buf.Bytes())
		return err
	}

	_, err = w.Write(formatted)
	return err
}

func goType(f *compiler.CompiledField, messages []*compiler.CompiledMessage, pointerStruct bool) string {
	switch f.Type {
	case schema.FieldTypeObject:
		for _, msg := range messages {
			if msg.TypeID == f.NestedMessageId {
				if pointerStruct {
					return fmt.Sprintf("*%s", msg.Name)
				}
				return fmt.Sprintf("%s", msg.Name)
			}
		}
	case schema.FieldTypeArray:
		for _, msg := range messages {
			if msg.TypeID == f.ArrElem.NestedMessageId {
				if pointerStruct {
					return fmt.Sprintf("[]*%s", msg.Name)
				}
				return fmt.Sprintf("[]%s", msg.Name)
			}
		}
		return fmt.Sprintf("[]%s", f.ArrElem.Type.GoType())
	default:
		return f.Type.GoType()
	}

	return ""
}

const goTemplateSource = `// Code generated by wireforge. DO NOT EDIT.
// To know more visit: github.com/avatar31/wireforge
//
// This file contains type-safe message definitions with binary serialization
// for a length-prefixed wire protocol. All multi-byte integers are encoded in
// Big-Endian (network byte order) to ensure cross-platform compatibility.
//
// Wire Protocol Frame Layout:
// 		+--------+---------------------+-------------------+--------------------+
// 		| Offset | Field               | Type              | Description        |
// 		+--------+---------------------+-------------------+--------------------+
// 		| 0      | Message Type ID     | uint16 Big-Endian | Codec selector     |
// 		| 2      | Fixed Payload Len   | uint16 Big-Endian | Fixed block size   |
// 		| 4      | Overall Payload Len | uint32 Big-Endian | Fixed + Dynamic    |
// 		| 8      | Fixed Payload       | raw bytes         | Padded fields      |
// 		| 8+N    | Dynamic Payload     | raw bytes         | Strings/blobs      |
// 		+--------+---------------------+-------------------+--------------------+
//
// Safety guarantees:
//   - MaxAllowedPacket (16 MB) prevents memory allocation exploits from
//     corrupted length fields ("poison pill" attack mitigation).
//   - init() performs compile-time layout validation via unsafe.Sizeof to
//     catch struct size mismatches between the generator and the Go compiler.
//   - All reads use io.ReadFull to handle socket short-reads correctly.
//   - Big-Endian encoding ensures consistent behavior across architectures.
package {{.PackageName}}

import (
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"unsafe"
)

const (
	// FrameHeaderSize represents the 2 bytes for TypeID, 2 bytes for FixedBlockLen
	// and 4 bytes for overall data size.
	FrameHeaderSize = 8

	// MaxAllowedPacket is the hard ceiling on any single message size (16 MB).
	// Any incoming length field exceeding this value is treated as corrupted
	// data and rejected immediately, preventing denial-of-service via
	// malicious allocation requests.
	MaxAllowedPacket = 16 * 1024 * 1024

	MaxArrayElements = 65535 // 2^16 - 1, since array length is encoded as uint16
)

// Compile-time import usage guarantees.
var (
	_ = binary.BigEndian
	_ = io.ReadFull
	_ = math.Float32frombits
	_ = unsafe.Sizeof(uint8(0))
)

type Primitive interface {
	bool | int8 | uint8 |
		int16 | uint16 |
		int32 | uint32 | float32 |
		int64 | uint64 | float64
}

type NonPrimitive interface {
	string |
		[]byte |{{range .Messages}}{{$msg := .}}
		*{{$msg.Name}} |{{end}}
		[]any
}
{{$overallMessages := .Messages}}
{{range .Messages}}{{$msg := .}}
// ---------------------------------------------------------------------------
// {{$msg.Name}}
// ---------------------------------------------------------------------------
// Wire Type ID: {{$msg.TypeID}}
// Fixed Block Length: {{$msg.TotalFixedSize}} bytes (includes alignment padding)
// Overall Block Length: {{$msg.TotalFixedSize}} bytes + Runtime dynamic payload
// ---------------------------------------------------------------------------

// {{$msg.Name}} represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type {{$msg.Name}} struct {
{{- range $msg.Fields}}{{$field := .}}
{{- if $field.Description}}
	// {{$field.Description}}
{{- end}} {{/* $field.Description */}}
	{{$field.GoName}} {{goType $field $overallMessages true}}
{{- end}} {{/* range $msg.Fields */}}
}

// {{$msg.Name}}FixedSize is the byte size of the fixed block portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const {{$msg.Name}}FixedSize = {{$msg.TotalFixedSize}}

// MessageTypeID returns the unique wire protocol type identifier for {{$msg.Name}}.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func ({{receiver $msg.Name}} *{{$msg.Name}}) MessageTypeID() uint16 {
	return {{$msg.TypeID}}
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg {{$msg.Name}}
	_ = msg
{{- range $msg.Fields}}{{$field := .}}
{{- if not (isVariable $field.Type)}}
	if unsafe.Sizeof(msg.{{$field.GoName}}) != {{$field.Size}} {
		panic("wireforge: {{$msg.Name}}.{{$field.GoName}} size mismatch")
	}
{{- end}} {{/* not (isVariable $field.Type) */}}
{{- end}} {{/* range $msg.Fields */}}
}

func ({{receiver $msg.Name}} *{{$msg.Name}}) DynamicPayloadSize() int {
	dynamicSize := 0

{{- range $msg.VariableFields}}{{$field := .}}
	dynamicSize += calcTypeSize({{receiver $msg.Name}}.{{$field.GoName}})
{{- end}} {{/* range $msg.VariableFields */}}

	return dynamicSize
}

func ({{receiver $msg.Name}} *{{$msg.Name}}) Size() int {
	return FrameHeaderSize + {{$msg.Name}}FixedSize + {{receiver $msg.Name}}.DynamicPayloadSize()
}

// Marshal serializes the {{$msg.Name}} message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID ({{$msg.TypeID}})
//	[2:4]     Fixed Block Length ({{$msg.TotalFixedSize}})
//	[4:8]     Fixed and Dynamic Block Length
//	[8:{{add 8 $msg.TotalFixedSize}}]    Fixed payload (primitives + length prefixes, Big-Endian)
//	[{{add 8 $msg.TotalFixedSize}}:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func ({{receiver $msg.Name}} *{{$msg.Name}}) Marshal() ([]byte, error) {
	payloadSize := {{$msg.Name}}FixedSize + {{receiver $msg.Name}}.DynamicPayloadSize()
	totalSize := FrameHeaderSize + payloadSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("{{$msg.Name}} message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed payload length + overall payload length
	binary.BigEndian.PutUint16(buf[0:2], {{$msg.TypeID}})
	binary.BigEndian.PutUint16(buf[2:4], uint16({{$msg.Name}}FixedSize))
	binary.BigEndian.PutUint32(buf[4:8], uint32(payloadSize))

	// Fixed block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + {{$msg.Name}}FixedSize

{{range $msg.Fields}}{{$field := .}}
{{- if isVariable $field.Type}}

{{- if eq (goBaseType $field.Type) "struct"}}
	
	{{receiver $msg.Name}}_{{$field.GoName}}_Bytes, err := {{receiver $msg.Name}}.{{$field.GoName}}.Marshal()
	if err != nil {
		return nil, fmt.Errorf("wireforge: failed to marshall {{$msg.Name}}.{{$field.GoName}}: %v", err)
	}
	copy(buf[dynOff:], {{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	dynOff += len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32(len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)))
{{- else if eq (goBaseType $field.Type) "[]any"}}
{{if (isVariable $field.ArrElem.Type)}}

	{{receiver $msg.Name}}_{{$field.GoName}}_Bytes, err := nonPrimitiveTypeSliceToBytes({{receiver $msg.Name}}.{{$field.GoName}}...)
	if err != nil {
		return nil, fmt.Errorf("wireforge: failed to marshall {{$msg.Name}}.{{$field.GoName}}: %v", err)
	}

	total{{$field.GoName}}Size := len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	copy(buf[dynOff:], {{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	dynOff += total{{$field.GoName}}Size
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32(total{{$field.GoName}}Size))
{{- else}} {{/* not (isVariable $field.ArrElem.Type) */}}

	{{receiver $msg.Name}}_{{$field.GoName}}_Bytes, err := primitiveTypeSliceToBytes({{receiver $msg.Name}}.{{$field.GoName}}...)
	if err != nil {
		return nil, fmt.Errorf("wireforge: failed to marshall {{$msg.Name}}.{{$field.GoName}}: %v", err)
	}

	copy(buf[dynOff:], {{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	dynOff += len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32(len({{receiver $msg.Name}}_{{$field.GoName}}_Bytes)))
{{- end}} {{/* isVariable $field.ArrElem.Type */}}
{{- else}} {{/* eq (goBaseType $field.Type) "string" or "[]byte" */}}

	copy(buf[dynOff:], {{receiver $msg.Name}}.{{$field.GoName}})
	dynOff += len({{receiver $msg.Name}}.{{$field.GoName}})
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32(len({{receiver $msg.Name}}.{{$field.GoName}})))
{{- end}} {{/* eq (goBaseType $field.Type) */}}
{{- else}} {{/* isVariable $field.Type */}}
{{- if eq (goBaseType $field.Type) "uint8"}}
	hdr[{{$field.Offset}}] = {{receiver $msg.Name}}.{{$field.GoName}}
{{- else if eq (goBaseType $field.Type) "int8"}}
	hdr[{{$field.Offset}}] = uint8({{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "bool"}}
	if {{receiver $msg.Name}}.{{$field.GoName}} {
		hdr[{{$field.Offset}}] = 1
	} else {
		hdr[{{$field.Offset}}] = 0
	}
{{- else if eq (goBaseType $field.Type) "uint16"}}
	binary.BigEndian.PutUint16(hdr[{{$field.Offset}}:{{add $field.Offset 2}}], {{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "int16"}}
	binary.BigEndian.PutUint16(hdr[{{$field.Offset}}:{{add $field.Offset 2}}], uint16({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "uint32"}}
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], {{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "int32"}}
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], uint32({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "uint64"}}
	binary.BigEndian.PutUint64(hdr[{{$field.Offset}}:{{add $field.Offset 8}}], {{receiver $msg.Name}}.{{$field.GoName}})
{{- else if eq (goBaseType $field.Type) "int64"}}
	binary.BigEndian.PutUint64(hdr[{{$field.Offset}}:{{add $field.Offset 8}}], uint64({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "float32"}}
	binary.BigEndian.PutUint32(hdr[{{$field.Offset}}:{{add $field.Offset 4}}], math.Float32bits({{receiver $msg.Name}}.{{$field.GoName}}))
{{- else if eq (goBaseType $field.Type) "float64"}}
	binary.BigEndian.PutUint64(hdr[{{$field.Offset}}:{{add $field.Offset 8}}], math.Float64bits({{receiver $msg.Name}}.{{$field.GoName}}))
{{- end}} {{/* eq (goBaseType $field.Type) */}}
{{- end}} {{/* isVariable $field.Type */}}
{{- end}} {{/* range $msg.Fields */}}

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a {{$msg.Name}} from the wire after the 8-byte frame
// header has already been consumed. The caller provides fixedPayloadSize (read
// from the frame) and overallPayloadSize so forward-compatible readers can skip
// unknown trailing bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func ({{receiver $msg.Name}} *{{$msg.Name}}) Unmarshal(reader io.Reader,
		fixedPayloadSize uint16, _ uint32) error {
	if int(fixedPayloadSize) < {{$msg.Name}}FixedSize {
		return fmt.Errorf("{{$msg.Name}} fixed payload size too short: got %d, need %d", fixedPayloadSize, {{$msg.Name}}FixedSize)
	}

	hdr := make([]byte, fixedPayloadSize)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading {{$msg.Name}} fixed payload: %w", err)
	}

{{range $msg.Fields}}{{$field := .}}
{{- if isVariable $field.Type}}
	{{receiver $msg.Name}}_{{$field.GoName}}_len := bytesToPrimitiveType[uint32](hdr[{{$field.Offset}}:{{add $field.Offset 4}}])
	if {{receiver $msg.Name}}_{{$field.GoName}}_len > MaxAllowedPacket {
		return fmt.Errorf("{{$msg.Name}}.{{$field.GoName}} length %d exceeds MaxAllowedPacket", {{receiver $msg.Name}}_{{$field.GoName}}_len)
	}
{{- else}} {{/* not (isVariable $field.Type) */}}
{{- if eq (goBaseType $field.Type) "uint8"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[uint8](hdr[{{$field.Offset}}])
{{- else if eq (goBaseType $field.Type) "int8"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[int8](hdr[{{$field.Offset}}])
{{- else if eq (goBaseType $field.Type) "bool"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[bool](hdr[{{$field.Offset}}])
{{- else if eq (goBaseType $field.Type) "uint16"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[uint16](hdr[{{$field.Offset}}:{{add $field.Offset 2}}])
{{- else if eq (goBaseType $field.Type) "int16"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[int16](hdr[{{$field.Offset}}:{{add $field.Offset 2}}])
{{- else if eq (goBaseType $field.Type) "uint32"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[uint32](hdr[{{$field.Offset}}:{{add $field.Offset 4}}])
{{- else if eq (goBaseType $field.Type) "int32"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[int32](hdr[{{$field.Offset}}:{{add $field.Offset 4}}])
{{- else if eq (goBaseType $field.Type) "uint64"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[uint64](hdr[{{$field.Offset}}:{{add $field.Offset 8}}])
{{- else if eq (goBaseType $field.Type) "int64"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[int64](hdr[{{$field.Offset}}:{{add $field.Offset 8}}])
{{- else if eq (goBaseType $field.Type) "float32"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[float32](hdr[{{$field.Offset}}:{{add $field.Offset 4}}])
{{- else if eq (goBaseType $field.Type) "float64"}}
	{{receiver $msg.Name}}.{{$field.GoName}} = bytesToPrimitiveType[float64](hdr[{{$field.Offset}}:{{add $field.Offset 8}}])
{{- end}} {{/* eq (goBaseType $field.Type) */}}
{{- end}} {{/* isVariable $field.Type */}}
{{- end}} {{/* range $msg.Fields */}}

{{- if hasVariable $msg}}

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed payload in the same order as their length prefixes above.
{{range $msg.VariableFields}}{{$field := .}}

	if {{receiver $msg.Name}}_{{$field.GoName}}_len > 0 {
{{- if eq (goBaseType $field.Type) "string"}}
		{{receiver $msg.Name}}_{{$field.GoName}}_buf := make([]byte, {{receiver $msg.Name}}_{{$field.GoName}}_len)
		if _, err := io.ReadFull(reader, {{receiver $msg.Name}}_{{$field.GoName}}_buf); err != nil {
			return fmt.Errorf("wireforge: reading {{$msg.Name}}.{{$field.GoName}} payload: %w", err)
		}
		{{receiver $msg.Name}}.{{$field.GoName}} = string({{receiver $msg.Name}}_{{$field.GoName}}_buf)
{{- else if eq (goBaseType $field.Type) "[]any"}}
{{if (isVariable $field.ArrElem.Type)}}
		if {{receiver $msg.Name}}_{{$field.GoName}}_len < 2 {
			return fmt.Errorf("wireforge: {{$msg.Name}}.{{$field.GoName}} length %d too short to contain count prefix", {{receiver $msg.Name}}_{{$field.GoName}}_len)
		}

		{{receiver $msg.Name}}_{{$field.GoName}}_reader := io.LimitReader(reader, int64({{receiver $msg.Name}}_{{$field.GoName}}_len))
		{{receiver $msg.Name}}_{{$field.GoName}}_arr , err := readerToNonPrimitiveTypeSlice[{{(goType $field.ArrElem $overallMessages true)}}]({{receiver $msg.Name}}_{{$field.GoName}}_reader)
		if err != nil {
			return fmt.Errorf("wireforge: reading {{$msg.Name}}.{{$field.GoName}} array: %w", err)
		}

		{{receiver $msg.Name}}.{{$field.GoName}} = {{receiver $msg.Name}}_{{$field.GoName}}_arr
{{- else}} {{/* not (isVariable $field.ArrElem.Type) */}}
		{{receiver $msg.Name}}_{{$field.GoName}}_buf := make([]byte, {{receiver $msg.Name}}_{{$field.GoName}}_len)
		if _, err := io.ReadFull(reader, {{receiver $msg.Name}}_{{$field.GoName}}_buf); err != nil {
			return fmt.Errorf("wireforge: reading {{$msg.Name}}.{{$field.GoName}} payload: %w", err)
		}
		
		var err error
		{{receiver $msg.Name}}.{{$field.GoName}}, err = bytesToPrimitiveTypeSlice[{{goBaseType $field.ArrElem.Type}}]({{receiver $msg.Name}}_{{$field.GoName}}_buf)
		if err != nil {
			return fmt.Errorf("wireforge: failed to convert {{$msg.Name}}.{{$field.GoName}} bytes to slice: %w", err)
		}
{{- end}} {{/* isVariable $field.ArrElem.Type */}}
{{- else if eq (goBaseType $field.Type) "struct"}}
		{{receiver $msg.Name}}_{{$field.GoName}}_reader := io.LimitReader(reader, int64({{receiver $msg.Name}}_{{$field.GoName}}_len))

		typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame({{receiver $msg.Name}}_{{$field.GoName}}_reader)
		if err != nil {
			return fmt.Errorf("wireforge: reading {{$msg.Name}}.{{$field.GoName}} frame header: %w", err)
		}

		var {{lower $field.GoName}} {{(goType $field $overallMessages false)}}
		if typeID != {{lower $field.GoName}}.MessageTypeID() {
			return fmt.Errorf("wireforge: unexpected type ID %d for {{$msg.Name}}.{{$field.GoName}}, expected %d", typeID, {{lower $field.GoName}}.MessageTypeID())
		}

		if err := {{lower $field.GoName}}.Unmarshal({{receiver $msg.Name}}_{{$field.GoName}}_reader, fixedPayloadLen, overallPayloadLen); err != nil {
			return fmt.Errorf("wireforge: unmarshalling {{$msg.Name}}.{{$field.GoName}}: %w", err)
		}
		{{receiver $msg.Name}}.{{$field.GoName}} = &{{lower $field.GoName}}
{{- else}} {{/* eq (goBaseType $field.Type) "[]byte" */}}
		{{receiver $msg.Name}}_{{$field.GoName}}_buf := make([]byte, {{receiver $msg.Name}}_{{$field.GoName}}_len)
		if _, err := io.ReadFull(reader, {{receiver $msg.Name}}_{{$field.GoName}}_buf); err != nil {
			return fmt.Errorf("reading {{$msg.Name}}.{{$field.GoName}} payload: %w", err)
		}
		{{receiver $msg.Name}}.{{$field.GoName}} = {{receiver $msg.Name}}_{{$field.GoName}}_buf
{{- end}} {{/* eq (goBaseType $field.Type)*/}}
	}
{{- end}} {{/* range $msg.VariableFields */}}
{{- end}} {{/* hasVariable $msg */}}

	return nil
}
{{end}} {{/* range .Messages */}}

// ReadMessageFrame reads the 8-byte wire frame header from r and returns the
// message type ID, fixed & overall payload length. Use this when you need to dispatch
// to different message types based on the type ID before calling Unmarshal.
func ReadMessageFrame(r io.Reader) (uint16, uint16, uint32, error) {
	var frame [FrameHeaderSize]byte
	if _, err := io.ReadFull(r, frame[:]); err != nil {
		return 0, 0, 0, err
	}
	typeID := bytesToPrimitiveType[uint16](frame[0:2])
	fixedPayloadLen := bytesToPrimitiveType[uint16](frame[2:4])
	overallPayloadLen := bytesToPrimitiveType[uint32](frame[4:8])

	return typeID, fixedPayloadLen, overallPayloadLen, nil
}

func nonPrimitiveTypeSliceToBytes[T NonPrimitive](elements ...T) ([]byte, error) {
	count := len(elements)
	if count == 0 {
		return binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements (%d)", count, MaxArrayElements)
	}

	result := make([]byte, 0, calcArraySize(elements...))
	result = binary.BigEndian.AppendUint16(result, uint16(count))

	for i, v := range elements {
		switch val := any(v).(type) {
		case string:
			length := len(val)
			if length > MaxAllowedPacket {
				return nil, fmt.Errorf("string length %d exceeds MaxAllowedPacket", length)
			}

			result = binary.BigEndian.AppendUint32(result, uint32(length))
			result = append(result, val...)
		case []byte:
			length := len(val)
			if length > MaxAllowedPacket {
				return nil, fmt.Errorf("[]byte length %d exceeds MaxAllowedPacket", length)
			}

			result = binary.BigEndian.AppendUint32(result, uint32(length))
			result = append(result, val...)
		case []any:
			innerBytes, err := nonPrimitiveTypeSliceToBytes(val)
			if err != nil {
				return nil, fmt.Errorf("failed to serialize inner array at index %d: %w", i, err)
			}
			result = append(result, innerBytes...)
{{range .Messages}}{{$msg := .}}
		case *{{$msg.Name}}:
			{{$msg.Name}}Bytes, err := val.Marshal()
			if err != nil {
				return nil, fmt.Errorf("failed to serialize {{$msg.Name}} at index %d: %w", i, err)
			}
			result = append(result, {{$msg.Name}}Bytes...)
{{end}}
		default:
			// This should never reach because nonPrimitiveTypeSliceToBytes will always be called with known types.
			panic(fmt.Errorf("unsupported type in array: %T", val))
		}
	}

	return result, nil
}

func readerToNonPrimitiveTypeSlice[T NonPrimitive](r io.Reader) ([]T, error) {
	var countBuf [2]byte
	if _, err := io.ReadFull(r, countBuf[:]); err != nil {
		return nil, err
	}
	
	count := bytesToPrimitiveType[uint16](countBuf[:])
	result := make([]T, count)
	if count == 0 {
		return result, nil
	}

	for i := 0; i < int(count); i++ {
		switch any(result[i]).(type) {
		case string:
			var lenBuf [2]byte
			if _, err := io.ReadFull(r, lenBuf[:]); err != nil {
				return nil, fmt.Errorf("failed to read string length prefix at index %d: %w", i, err)
			}

			length := bytesToPrimitiveType[uint16](lenBuf[:])
			buf := make([]byte, length)
			if _, err := io.ReadFull(r, buf); err != nil {
				return nil, fmt.Errorf("failed to read string data at index %d: %w", i, err)
			}
			result[i], _ = any(string(buf)).(T)
		case []byte:
			var lenBuf [2]byte
			if _, err := io.ReadFull(r, lenBuf[:]); err != nil {
				return nil, fmt.Errorf("failed to read []byte length prefix at index %d: %w", i, err)
			}

			length := bytesToPrimitiveType[uint16](lenBuf[:])
			buf := make([]byte, length)
			if _, err := io.ReadFull(r, buf); err != nil {
				return nil, fmt.Errorf("failed to read []byte data at index %d: %w", i, err)
			}
			result[i], _ = any(buf).(T)
		case []any:	// Multidimensional array case: recursively read inner arrays
			innerSlice, err := readerToNonPrimitiveTypeSlice[[]any](r)
			if err != nil {
				return nil, fmt.Errorf("failed to read inner array at index %d: %w", i, err)
			}
			result[i], _ = any(innerSlice).(T)
{{range .Messages}}{{$msg := .}}
		case *{{$msg.Name}}:
			typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame(r)
			if err != nil {
				return nil, err
			}

			var msg {{$msg.Name}}
			if typeID != msg.MessageTypeID() {
				return nil, fmt.Errorf("unexpected type ID %d for {{$msg.Name}} at index %d, expected %d", typeID, i, msg.MessageTypeID())
			}

			{{$msg.Name}}_reader := io.LimitReader(r, int64(overallPayloadLen))
			if err := msg.Unmarshal({{$msg.Name}}_reader, fixedPayloadLen, overallPayloadLen); err != nil {
				return nil, fmt.Errorf("failed to deserialize {{$msg.Name}} at index %d: %w", i, err)
			}
			result[i], _ = any(&msg).(T)
{{end}}
		default:
			// This should never reach because readerToNonPrimitiveTypeSlice will always be called with known types.
			panic(fmt.Errorf("unsupported type in array: %T", result[i]))
		}
	}

	return result, nil
}

func calcArraySize[T NonPrimitive](elements ...T) int {
	size := 2 // 2 bytes for the count prefix
	if len(elements) == 0 {
		return size
	}

	switch any(elements[0]).(type) {
	case int8, uint8, bool, int16, uint16, int32, uint32, float32, int64, uint64, float64:
		size += (len(elements) * calcTypeSize(elements[0]))
		return size
	}

	for _, v := range elements {
		switch any(v).(type) {
		case string, []byte:
			size += 2 // 2 bytes for the length prefix of each element
		}
		size += calcTypeSize(v)
	}

	return size
}

func calcTypeSize(ele any) int {
	switch val := ele.(type) {
	case []any:
		return calcArraySize(val)
	case string:
		return len(val)
	case []byte:
		return len(val)
	case int8, uint8, bool:
		return 1
	case int16, uint16:
		return 2
	case int32, uint32, float32:
		return 4
	case int64, uint64, float64:
		return 8
{{range .Messages}}{{$msg := .}}
	case {{$msg.Name}}:
		return val.Size()
	case *{{$msg.Name}}:
		if val != nil {
			return val.Size()
		}
		return 0
{{end}}
	default:
		// This should never reach because calcTypeSize will always be called with known types.
		panic(fmt.Errorf("unsupported type in array: %T", val))
	}
}

// primitiveTypeSliceToBytes takes a slice of mixed numeric types ([]any) and returns a single combined,
// flattened big-endian byte slice.
func primitiveTypeSliceToBytes[T Primitive](elements ...T) ([]byte, error) {
	// Pre-allocate a reasonable buffer capacity to minimize re-allocations
	count := len(elements)
	if count == 0 {
		return binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements (%d)", count, MaxArrayElements)
	}

	var zero T
	elemSize := calcTypeSize(zero)

	combinedBuf := make([]byte, 0, 2+int(count)*elemSize)
	combinedBuf = binary.BigEndian.AppendUint16(combinedBuf, uint16(count))

	for _, v := range elements {
		switch val := any(v).(type) {
		// 1-byte
		case int8:
			combinedBuf = append(combinedBuf, byte(val))

		case uint8:
			combinedBuf = append(combinedBuf, val)

		case bool:
			if val {
				combinedBuf = append(combinedBuf, 1)
			} else {
				combinedBuf = append(combinedBuf, 0)
			}

		// 2-byte
		case int16:
			combinedBuf = binary.BigEndian.AppendUint16(combinedBuf, uint16(val))

		case uint16:
			combinedBuf = binary.BigEndian.AppendUint16(combinedBuf, val)

		// 4-byte
		case int32:
			combinedBuf = binary.BigEndian.AppendUint32(combinedBuf, uint32(val))

		case uint32:
			combinedBuf = binary.BigEndian.AppendUint32(combinedBuf, val)

		case float32:
			combinedBuf = binary.BigEndian.AppendUint32(combinedBuf, math.Float32bits(val))

		// 8-byte
		case int64:
			combinedBuf = binary.BigEndian.AppendUint64(combinedBuf, uint64(val))

		case uint64:
			combinedBuf = binary.BigEndian.AppendUint64(combinedBuf, val)

		case float64:
			combinedBuf = binary.BigEndian.AppendUint64(combinedBuf, math.Float64bits(val))

		default:
			// This should never reach because primitiveTypeSliceToBytes will always be called with known types.
			panic(fmt.Errorf("unsupported primitive type: %T", val))
		}
	}

	return combinedBuf, nil
}

func bytesToPrimitiveTypeSlice[T Primitive](data []byte) ([]T, error) {
	if len(data) < 2 {
		return nil, fmt.Errorf("buffer too small")
	}

	count := int(bytesToPrimitiveType[uint16](data[:2]))
	data = data[2:]

	var zero T
	elemSize := calcTypeSize(zero)

	expected := count * elemSize
	if len(data) != expected {
		return nil, fmt.Errorf("invalid buffer length: expected %d bytes, got %d",
				expected, len(data))
	}

	result := make([]T, count)

	for i := range result {
		offset := i * elemSize
		result[i] = bytesToPrimitiveType[T](data[offset:])
	}

	return result, nil
}

func bytesToPrimitiveType[T Primitive](data []byte) T {
	var zero T

	switch any(zero).(type) {
	// 1-byte
	case int8:
		return any(int8(data[0])).(T)

	case uint8:
		return any(data[0]).(T)

	case bool:
		return any(data[0] != 0).(T)

	// 2-byte
	case int16:
		return any(int16(binary.BigEndian.Uint16(data))).(T)

	case uint16:
		return any(binary.BigEndian.Uint16(data)).(T)

	// 4-byte
	case int32:
		return any(int32(binary.BigEndian.Uint32(data))).(T)

	case uint32:
		return any(binary.BigEndian.Uint32(data)).(T)

	case float32:
		return any(math.Float32frombits(binary.BigEndian.Uint32(data))).(T)

	// 8-byte
	case int64:
		return any(int64(binary.BigEndian.Uint64(data))).(T)

	case uint64:
		return any(binary.BigEndian.Uint64(data)).(T)

	case float64:
		return any(math.Float64frombits(binary.BigEndian.Uint64(data))).(T)

	default:
		// This should never reach because bytesToPrimitiveType will always be called with known types.
		panic(fmt.Errorf("unsupported primitive type: %T", zero))
	}
}
`
