/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 * To know more visit: github.com/avatar31/wireforge
 *
 * This header defines C structure types and function prototypes for a
 * length-prefixed binary wire protocol. Each message type has:
 *
 *   - A typedef struct with explicit padding fields for deterministic layout
 *   - _Static_assert to verify struct size at compile time
 *   - Marshal/Unmarshal functions for buffer-based serialization
 *   - Stream-safe read/write functions for socket I/O (handles short reads)
 *   - A free function to release dynamically allocated fields
 *
 * Wire Protocol Frame Layout:
 *   +--------+---------------------+-------------------+--------------------+
 *   | Offset | Field               | Type              | Description        |
 *   +--------+---------------------+-------------------+--------------------+
 *   | 0      | Message Type ID     | uint16 Big-Endian | Codec selector     |
 *   | 2      | Fixed Payload Len   | uint16 Big-Endian | Fixed block size   |
 *   | 4      | Overall Payload Len | uint32 Big-Endian | Fixed + Dynamic    |
 *   | 8      | Fixed Payload       | raw bytes         | Padded fields      |
 *   | 8+N    | Dynamic Payload     | raw bytes         | Strings/blobs      |
 *   +--------+---------------------+-------------------+--------------------+
 *
 * Safety guarantees:
 *   - MAX_ALLOWED_PACKET caps any single allocation (prevents malloc bombs)
 *   - NULL checks on every allocation result
 *   - Strings are always NULL-terminated after deserialization
 *   - free functions set pointers to NULL to prevent double-free
 *
 * Memory ownership:
 *   - After unmarshal, the caller owns the struct and must call
 *     the corresponding _free() function when done.
 *   - After marshal, no heap memory is retained by the callee.
 */

#ifndef MESSAGES_H
#define MESSAGES_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Maximum allowed packet size (16 MB).
 * Any length field exceeding this is treated as data corruption and
 * immediately rejected to prevent denial-of-service via malloc bombs.
 */
#define MAX_ALLOWED_PACKET (16 * 1024 * 1024)

#define WIRE_FRAME_MSG_TYPE_SIZE 2
#define WIRE_FRAME_MSG_FIXED_PAYLOAD_SIZE 2
#define WIRE_FRAME_MSG_OVERALL_PAYLOAD_SIZE 4
#define TYPE_MARKER_SIZE 2
#define ARRAY_COUNT_PREFIX_SIZE 2
#define STRING_OR_BYTE_LEN_PREFIX_SIZE 4
#define MAX_ARRAY_ELEMENTS 65535

/**
 * Size of the wire frame header:
 *		2-byte type ID + 2-byte fixed payload length + 4-byte overall payload length
 */
#define WIRE_FRAME_HEADER_SIZE 8

typedef enum {
    TAG_NONE        = 0x0000,
    TAG_UINT8       = 0x0001,
    TAG_INT8        = 0x0002,
    TAG_BOOL        = 0x0003,
    TAG_UINT16      = 0x0004,
    TAG_INT16       = 0x0005,
    TAG_UINT32      = 0x0006,
    TAG_INT32       = 0x0007,
    TAG_FLOAT32     = 0x0008,
    TAG_UINT64      = 0x0009,
    TAG_INT64       = 0x000A,
    TAG_FLOAT64     = 0x000B,
    TAG_STRING      = 0x000C,
    TAG_BYTES       = 0x000D,
    TAG_ARRAY       = 0x000E,
    TAG_2D_ARRAY    = 0x000F,
    TAG_3D_ARRAY    = 0x0010,
    TAG_NO_PADDING_MSG       = 0x0020,
    TAG_SMALL_FIELDS_MSG       = 0x0021,
    TAG_MIXED_SIZE_MSG       = 0x0022,
    TAG_ALIGNED_MSG       = 0x0023,
} element_type_t;

typedef struct {
	char *data;
	uint32_t len;
} string_t;

typedef struct {
	uint8_t *data;
	uint32_t len;
} byte_array_t;

typedef struct {
    void *data;
    size_t elem_size;
    
    // User dimensions
    uint8_t num_dims; // 1, 2, or 3
    size_t x;
    size_t y;
    size_t z;
    
    // The total maximum flat elements the current memory can hold
    size_t capacity; 
	element_type_t ele_type; // element type for dynamic arrays
} dynamic_array_t;

uint16_t get_message_type(const uint8_t *buf);
uint16_t get_message_fixed_payload_length(const uint8_t *buf);
uint32_t get_message_overall_payload_length(const uint8_t *buf);



typedef struct no_padding_msg no_padding_msg_t;

typedef struct small_fields_msg small_fields_msg_t;

typedef struct mixed_size_msg mixed_size_msg_t;

typedef struct aligned_msg aligned_msg_t;



/* ===========================================================================
 * NoPaddingMsg
 * Wire Type ID: 1
 * Fixed Block Length: 8 bytes (including alignment padding)
 * Overall Payload Length: 8 bytes + Runtime dynamic payload
 * ===========================================================================*/

/** Wire protocol message type ID for NoPaddingMsg. */
#define NO_PADDING_MSG_TYPE_ID 1

/** Byte size of the fixed block for NoPaddingMsg (padded for alignment). */
#define NO_PADDING_MSG_FIXED_SIZE 8

/**
 * no_padding_msg_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
struct no_padding_msg {  
    /** A single 8-byte field; no padding required. */ 
    int64_t value;   
};

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(no_padding_msg_t) >= 8,
    "wireforge: no_padding_msg_t fixed layout size mismatch");

/**
 * Sets the value of the value field in the no_padding_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void no_padding_msg_t_set_value(no_padding_msg_t *msg, const int64_t value);

size_t no_padding_msg_t_dynamic_payload_size(const no_padding_msg_t *msg);

size_t no_padding_msg_t_size(const no_padding_msg_t *msg);

/**
 * Serialize a NoPaddingMsg message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function
 * 					will write the serialized message stream into the buffer referenced
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int no_padding_msg_t_marshal(const no_padding_msg_t *msg, uint8_t **out_buf);

/**
 * Deserialize a NoPaddingMsg message from a contiguous buffer.
 *
 * @param in_buf				Input buffer starting at the fixed payload (after 8-bytes frame header).
 * @param fixed_payload_len		Fixed payload length as read from the wire frame header.
 * @param overall_payload_len	Total available bytes in in_buf (fixed + dynamic payload).
 * @param out_msg				Output struct (zeroed on entry; fields populated on success).
 * @return						0 on success, -1 on error (truncated data, allocation failure,
 *                          		length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call no_padding_msg_t_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int no_padding_msg_t_unmarshal(const uint8_t *in_buf, uint16_t fixed_payload_len,
		uint32_t overall_payload_len, no_padding_msg_t *out_msg);

/**
 * Free all dynamically allocated fields in a no_padding_msg_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void no_padding_msg_t_free(no_padding_msg_t *msg);


/* ===========================================================================
 * SmallFieldsMsg
 * Wire Type ID: 2
 * Fixed Block Length: 4 bytes (including alignment padding)
 * Overall Payload Length: 4 bytes + Runtime dynamic payload
 * ===========================================================================*/

/** Wire protocol message type ID for SmallFieldsMsg. */
#define SMALL_FIELDS_MSG_TYPE_ID 2

/** Byte size of the fixed block for SmallFieldsMsg (padded for alignment). */
#define SMALL_FIELDS_MSG_FIXED_SIZE 4

/**
 * small_fields_msg_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
struct small_fields_msg {  
    /** First byte field. */ 
    uint8_t alpha;    
    /** Second byte field (signed). */ 
    int8_t beta;    
    /** Boolean field (1 byte). */ 
    uint8_t gamma;   
    uint8_t _pad0[1]; /**< Explicit alignment padding. */  
};

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(small_fields_msg_t) >= 4,
    "wireforge: small_fields_msg_t fixed layout size mismatch");

/**
 * Sets the value of the alpha field in the small_fields_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void small_fields_msg_t_set_alpha(small_fields_msg_t *msg, const uint8_t value);

/**
 * Sets the value of the beta field in the small_fields_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void small_fields_msg_t_set_beta(small_fields_msg_t *msg, const int8_t value);

/**
 * Sets the value of the gamma field in the small_fields_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void small_fields_msg_t_set_gamma(small_fields_msg_t *msg, const uint8_t value);

size_t small_fields_msg_t_dynamic_payload_size(const small_fields_msg_t *msg);

size_t small_fields_msg_t_size(const small_fields_msg_t *msg);

/**
 * Serialize a SmallFieldsMsg message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function
 * 					will write the serialized message stream into the buffer referenced
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int small_fields_msg_t_marshal(const small_fields_msg_t *msg, uint8_t **out_buf);

/**
 * Deserialize a SmallFieldsMsg message from a contiguous buffer.
 *
 * @param in_buf				Input buffer starting at the fixed payload (after 8-bytes frame header).
 * @param fixed_payload_len		Fixed payload length as read from the wire frame header.
 * @param overall_payload_len	Total available bytes in in_buf (fixed + dynamic payload).
 * @param out_msg				Output struct (zeroed on entry; fields populated on success).
 * @return						0 on success, -1 on error (truncated data, allocation failure,
 *                          		length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call small_fields_msg_t_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int small_fields_msg_t_unmarshal(const uint8_t *in_buf, uint16_t fixed_payload_len,
		uint32_t overall_payload_len, small_fields_msg_t *out_msg);

/**
 * Free all dynamically allocated fields in a small_fields_msg_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void small_fields_msg_t_free(small_fields_msg_t *msg);


/* ===========================================================================
 * MixedSizeMsg
 * Wire Type ID: 3
 * Fixed Block Length: 16 bytes (including alignment padding)
 * Overall Payload Length: 16 bytes + Runtime dynamic payload
 * ===========================================================================*/

/** Wire protocol message type ID for MixedSizeMsg. */
#define MIXED_SIZE_MSG_TYPE_ID 3

/** Byte size of the fixed block for MixedSizeMsg (padded for alignment). */
#define MIXED_SIZE_MSG_FIXED_SIZE 16

/**
 * mixed_size_msg_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
struct mixed_size_msg {  
    /** 8-byte integer field. */ 
    int64_t big;    
    /** 1-byte boolean field. */ 
    uint8_t flag;   
    uint8_t _pad0[7]; /**< Explicit alignment padding. */  
};

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(mixed_size_msg_t) >= 16,
    "wireforge: mixed_size_msg_t fixed layout size mismatch");

/**
 * Sets the value of the big field in the mixed_size_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void mixed_size_msg_t_set_big(mixed_size_msg_t *msg, const int64_t value);

/**
 * Sets the value of the flag field in the mixed_size_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void mixed_size_msg_t_set_flag(mixed_size_msg_t *msg, const uint8_t value);

size_t mixed_size_msg_t_dynamic_payload_size(const mixed_size_msg_t *msg);

size_t mixed_size_msg_t_size(const mixed_size_msg_t *msg);

/**
 * Serialize a MixedSizeMsg message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function
 * 					will write the serialized message stream into the buffer referenced
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int mixed_size_msg_t_marshal(const mixed_size_msg_t *msg, uint8_t **out_buf);

/**
 * Deserialize a MixedSizeMsg message from a contiguous buffer.
 *
 * @param in_buf				Input buffer starting at the fixed payload (after 8-bytes frame header).
 * @param fixed_payload_len		Fixed payload length as read from the wire frame header.
 * @param overall_payload_len	Total available bytes in in_buf (fixed + dynamic payload).
 * @param out_msg				Output struct (zeroed on entry; fields populated on success).
 * @return						0 on success, -1 on error (truncated data, allocation failure,
 *                          		length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call mixed_size_msg_t_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int mixed_size_msg_t_unmarshal(const uint8_t *in_buf, uint16_t fixed_payload_len,
		uint32_t overall_payload_len, mixed_size_msg_t *out_msg);

/**
 * Free all dynamically allocated fields in a mixed_size_msg_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void mixed_size_msg_t_free(mixed_size_msg_t *msg);


/* ===========================================================================
 * AlignedMsg
 * Wire Type ID: 4
 * Fixed Block Length: 12 bytes (including alignment padding)
 * Overall Payload Length: 12 bytes + Runtime dynamic payload
 * ===========================================================================*/

/** Wire protocol message type ID for AlignedMsg. */
#define ALIGNED_MSG_TYPE_ID 4

/** Byte size of the fixed block for AlignedMsg (padded for alignment). */
#define ALIGNED_MSG_FIXED_SIZE 12

/**
 * aligned_msg_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
struct aligned_msg {  
    /** 4-byte integer field. */ 
    int32_t count;    
    /** 4-byte float field. */ 
    float rate;   
    /** Variable-length string (4-byte length prefix in fixed block). */ 
	string_t name;   
};

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(aligned_msg_t) >= 12,
    "wireforge: aligned_msg_t fixed layout size mismatch");

/**
 * Sets the value of the count field in the aligned_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void aligned_msg_t_set_count(aligned_msg_t *msg, const int32_t value);

/**
 * Sets the value of the rate field in the aligned_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void aligned_msg_t_set_rate(aligned_msg_t *msg, const float value);

/**
 * Sets the value of the name field in the aligned_msg_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void aligned_msg_t_set_name(aligned_msg_t *msg, const char *value, const size_t len);

size_t aligned_msg_t_dynamic_payload_size(const aligned_msg_t *msg);

size_t aligned_msg_t_size(const aligned_msg_t *msg);

/**
 * Serialize a AlignedMsg message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function
 * 					will write the serialized message stream into the buffer referenced
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int aligned_msg_t_marshal(const aligned_msg_t *msg, uint8_t **out_buf);

/**
 * Deserialize a AlignedMsg message from a contiguous buffer.
 *
 * @param in_buf				Input buffer starting at the fixed payload (after 8-bytes frame header).
 * @param fixed_payload_len		Fixed payload length as read from the wire frame header.
 * @param overall_payload_len	Total available bytes in in_buf (fixed + dynamic payload).
 * @param out_msg				Output struct (zeroed on entry; fields populated on success).
 * @return						0 on success, -1 on error (truncated data, allocation failure,
 *                          		length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call aligned_msg_t_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int aligned_msg_t_unmarshal(const uint8_t *in_buf, uint16_t fixed_payload_len,
		uint32_t overall_payload_len, aligned_msg_t *out_msg);

/**
 * Free all dynamically allocated fields in a aligned_msg_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void aligned_msg_t_free(aligned_msg_t *msg);



/**
 * Internal Helpers
 */

typedef size_t (*custom_size_fn)(const void *item);
typedef int (*custom_marshal_fn)(const void *item, uint8_t **out_buf);
typedef int (*custom_unmarshal_fn)(const uint8_t *buf, uint16_t buf_len,
	uint32_t overall_payload_len, void *out_item);

size_t calc_type_size(
    const void *item,
    element_type_t ele_type,
    custom_size_fn size_fn
);

size_t calc_array_size(
    const dynamic_array_t *arr,
    element_type_t ele_type,
    custom_size_fn size_fn
);

#ifdef __cplusplus
}
#endif

#endif /* MESSAGES_H */
