openapi: 3.1.0
info:
  version: 1.0.0
  title: DotFS FSAL Message Schemas
paths: {}
components:
  schemas:
    ReadRequestMsg:
      type: object
      x-message-id: 1
      properties:
        protocol:
          description: Protocol identifier for the message
          type: string
        Request:
          description: Read request payload
          type: object
          properties:
            key:
              description: Key to look up
              type: string
            count:
              description: Number of bytes to read
              type: integer
            offset:
              description: Offset to read from
              type: integer
              format: uint64
    ReadResponseMsg:
      type: object
      x-message-id: 2
      properties:
        Error:
          description: Error response in case of failure
          type: object
          nullable: true
          properties:
            code:
              description: HTTP Status code of the error
              type: integer
            message:
              description: Error message
              type: string
        Data:
          description: Read response payload
          type: object
          nullable: true
          properties:
            key:
              description: Key that was read
              type: string
            data:
              description: Data that was read
              type: string
              format: binary
            bytesRead:
              description: Number of bytes read
              type: integer
              format: int64
    CreateObjectRequestMsg:
      type: object
      x-message-id: 3
      properties:
        Request:
          description: Create object request payload
          type: object
          properties:
            key:
              description: Key to create
              type: string
            protocols:
              description: List of protocols to use for the object
              type: array
              items:
                type: string
            ACL:
              description: Access control list for the object
              type: array
              items:
                type: object
                properties:
                  principal:
                    description: Principal for the ACL entry
                    type: string
                  permission:
                    description: Permission for the ACL entry
                    type: array
                    items:
                      type: string
                      enum:
                        - read
                        - write
                        - execute
