/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 *
 * This file implements the serialization, deserialization, stream I/O, and
 * memory management functions declared in messages.h.
 */

#include <stdlib.h>
#include <string.h>

#include "messages.h"

/* ---------------------------------------------------------------------------
 * Big-Endian encoding/decoding helpers
 * These ensure consistent wire format regardless of host CPU byte order.
 * ---------------------------------------------------------------------------*/

static inline void put_u16_be(uint8_t* buf, uint16_t val) {
    buf[0] = (uint8_t)(val >> 8);
    buf[1] = (uint8_t)(val);
}

static inline void put_u32_be(uint8_t* buf, uint32_t val) {
    buf[0] = (uint8_t)(val >> 24);
    buf[1] = (uint8_t)(val >> 16);
    buf[2] = (uint8_t)(val >> 8);
    buf[3] = (uint8_t)(val);
}

static inline void put_u64_be(uint8_t* buf, uint64_t val) {
    buf[0] = (uint8_t)(val >> 56);
    buf[1] = (uint8_t)(val >> 48);
    buf[2] = (uint8_t)(val >> 40);
    buf[3] = (uint8_t)(val >> 32);
    buf[4] = (uint8_t)(val >> 24);
    buf[5] = (uint8_t)(val >> 16);
    buf[6] = (uint8_t)(val >> 8);
    buf[7] = (uint8_t)(val);
}

static inline uint16_t get_u16_be(const uint8_t* buf) {
    return (uint16_t)((uint16_t)buf[0] << 8 | (uint16_t)buf[1]);
}

static inline uint32_t get_u32_be(const uint8_t* buf) {
    return (uint32_t)buf[0] << 24 | (uint32_t)buf[1] << 16 |
           (uint32_t)buf[2] << 8  | (uint32_t)buf[3];
}

static inline uint64_t get_u64_be(const uint8_t* buf) {
    return (uint64_t)buf[0] << 56 | (uint64_t)buf[1] << 48 |
           (uint64_t)buf[2] << 40 | (uint64_t)buf[3] << 32 |
           (uint64_t)buf[4] << 24 | (uint64_t)buf[5] << 16 |
           (uint64_t)buf[6] << 8  | (uint64_t)buf[7];
}

uint16_t get_message_type(const uint8_t* buf) {
    return get_u16_be(buf);
}

uint16_t get_message_fixed_length(const uint8_t* buf) {
    return get_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE);
}


/* ===========================================================================
 * UserMessage (Type ID: 1, Fixed Header: 16 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the timestamp field in the user_message_t struct.
 */
void user_message_set_timestamp(user_message_t* msg, const int64_t value) {
    if (msg) msg->timestamp = value;
}

/**
 * Sets the value of the content field in the user_message_t struct.
 */
void user_message_set_content(user_message_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->content != NULL) {
        free(msg->content);
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->content = new_value;
    msg->content_len = (uint32_t)len;
}

/**
 * Sets the value of the attachment field in the user_message_t struct.
 */
void user_message_set_attachment(user_message_t* msg, const uint8_t* value, size_t len) {
    if (!msg || !value || len == 0) return;
    if (msg->attachment != NULL) {
        free(msg->attachment);
    }

    uint8_t* new_value = (uint8_t*) malloc(len);
    if (!new_value) return;

    memcpy(new_value, value, len);
    msg->attachment = new_value;
    msg->attachment_len = (uint32_t)len;
}

/**
 * calculate_user_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserMessage message from the fixed header.
 */
size_t calculate_user_message_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    uint32_t content_len = get_u32_be(hdr_buf + 8);
    dyn_total += content_len;
    uint32_t attachment_len = get_u32_be(hdr_buf + 12);
    dyn_total += attachment_len;
    return dyn_total;
}

/**
 * user_message_marshal - Serialize UserMessage to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (1, Big-Endian)
 *   [2:4]     Fixed header length (16, Big-Endian)
 *   [4:20]    Fixed header (fields + padding, Big-Endian encoded)
 *   [20:end]  Dynamic payload (variable-length field data)
 */
int user_message_marshal(const user_message_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;
    dyn_size += msg->content_len;
    dyn_size += msg->attachment_len;

    size_t total = WIRE_FRAME_HEADER_SIZE + USER_MESSAGE_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + USER_MESSAGE_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, USER_MESSAGE_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, USER_MESSAGE_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + USER_MESSAGE_FIXED_SIZE;
    put_u64_be(hdr + 0, (uint64_t)msg->timestamp);
    put_u32_be(hdr + 8, msg->content_len);
    if (msg->content_len > 0 && msg->content) {
        memcpy(buf + dyn_off, msg->content, msg->content_len);
        dyn_off += msg->content_len;
    }
    put_u32_be(hdr + 12, msg->attachment_len);
    if (msg->attachment_len > 0 && msg->attachment) {
        memcpy(buf + dyn_off, msg->attachment, msg->attachment_len);
        dyn_off += msg->attachment_len;
    }

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * user_message_unmarshal - Deserialize UserMessage from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call user_message_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int user_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, user_message_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < USER_MESSAGE_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(user_message_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->timestamp = (int64_t)get_u64_be(hdr + 0);
    out_msg->content_len = get_u32_be(hdr + 8);
    out_msg->attachment_len = get_u32_be(hdr + 12);

    /* Decode variable-length dynamic fields safely */
    if (out_msg->content_len > 0) {
        if (out_msg->content_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->content_len > in_len) {
            user_message_free(out_msg);
            return -1;
        }
        out_msg->content = (char*) malloc(out_msg->content_len + 1);
        if (!out_msg->content) {
            user_message_free(out_msg);
            return -1;
        }

        memcpy(out_msg->content, in_buf + dyn_off, out_msg->content_len);
        out_msg->content[out_msg->content_len] = '\0';
        dyn_off += out_msg->content_len;
    }
    if (out_msg->attachment_len > 0) {
        if (out_msg->attachment_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->attachment_len > in_len) {
            user_message_free(out_msg);
            return -1;
        }
        out_msg->attachment = (uint8_t*)malloc(out_msg->attachment_len);
        if (!out_msg->attachment) {
            user_message_free(out_msg);
            return -1;
        }
        memcpy(out_msg->attachment, in_buf + dyn_off, out_msg->attachment_len);
        dyn_off += out_msg->attachment_len;
    }

    (void)dyn_off;
    return 0;
}

/**
 * user_message_free - Release heap memory owned by a user_message_t struct.
 */
void user_message_free(user_message_t* msg) {
    if (!msg) return;
    if (msg->content) {
        free(msg->content);
        msg->content = NULL;
    }
    msg->content_len = 0;
    if (msg->attachment) {
        free(msg->attachment);
        msg->attachment = NULL;
    }
    msg->attachment_len = 0;
}


/* ===========================================================================
 * HeartbeatMessage (Type ID: 2, Fixed Header: 8 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the timestamp field in the heartbeat_message_t struct.
 */
void heartbeat_message_set_timestamp(heartbeat_message_t* msg, const int64_t value) {
    if (msg) msg->timestamp = value;
}

/**
 * calculate_heartbeat_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the HeartbeatMessage message from the fixed header.
 */
size_t calculate_heartbeat_message_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    return dyn_total;
}

/**
 * heartbeat_message_marshal - Serialize HeartbeatMessage to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (2, Big-Endian)
 *   [2:4]     Fixed header length (8, Big-Endian)
 *   [4:12]    Fixed header (fields + padding, Big-Endian encoded)
 *   [12:end]  Dynamic payload (variable-length field data)
 */
int heartbeat_message_marshal(const heartbeat_message_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;

    size_t total = WIRE_FRAME_HEADER_SIZE + HEARTBEAT_MESSAGE_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + HEARTBEAT_MESSAGE_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, HEARTBEAT_MESSAGE_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, HEARTBEAT_MESSAGE_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + HEARTBEAT_MESSAGE_FIXED_SIZE;
    put_u64_be(hdr + 0, (uint64_t)msg->timestamp);

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * heartbeat_message_unmarshal - Deserialize HeartbeatMessage from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call heartbeat_message_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int heartbeat_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, heartbeat_message_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < HEARTBEAT_MESSAGE_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(heartbeat_message_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->timestamp = (int64_t)get_u64_be(hdr + 0);

    /* Decode variable-length dynamic fields safely */

    (void)dyn_off;
    return 0;
}

/**
 * heartbeat_message_free - Release heap memory owned by a heartbeat_message_t struct.
 */
void heartbeat_message_free(heartbeat_message_t* msg) {
    if (!msg) return;
}


/* ===========================================================================
 * UserJoinedMessage (Type ID: 3, Fixed Header: 16 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the timestamp field in the user_joined_message_t struct.
 */
void user_joined_message_set_timestamp(user_joined_message_t* msg, const int64_t value) {
    if (msg) msg->timestamp = value;
}

/**
 * Sets the value of the username field in the user_joined_message_t struct.
 */
void user_joined_message_set_username(user_joined_message_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->username != NULL) {
        free(msg->username);
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->username = new_value;
    msg->username_len = (uint32_t)len;
}

/**
 * calculate_user_joined_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserJoinedMessage message from the fixed header.
 */
size_t calculate_user_joined_message_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    uint32_t username_len = get_u32_be(hdr_buf + 8);
    dyn_total += username_len;
    return dyn_total;
}

/**
 * user_joined_message_marshal - Serialize UserJoinedMessage to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (3, Big-Endian)
 *   [2:4]     Fixed header length (16, Big-Endian)
 *   [4:20]    Fixed header (fields + padding, Big-Endian encoded)
 *   [20:end]  Dynamic payload (variable-length field data)
 */
int user_joined_message_marshal(const user_joined_message_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;
    dyn_size += msg->username_len;

    size_t total = WIRE_FRAME_HEADER_SIZE + USER_JOINED_MESSAGE_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + USER_JOINED_MESSAGE_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, USER_JOINED_MESSAGE_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, USER_JOINED_MESSAGE_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + USER_JOINED_MESSAGE_FIXED_SIZE;
    put_u64_be(hdr + 0, (uint64_t)msg->timestamp);
    put_u32_be(hdr + 8, msg->username_len);
    if (msg->username_len > 0 && msg->username) {
        memcpy(buf + dyn_off, msg->username, msg->username_len);
        dyn_off += msg->username_len;
    }

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * user_joined_message_unmarshal - Deserialize UserJoinedMessage from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call user_joined_message_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int user_joined_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, user_joined_message_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < USER_JOINED_MESSAGE_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(user_joined_message_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->timestamp = (int64_t)get_u64_be(hdr + 0);
    out_msg->username_len = get_u32_be(hdr + 8);

    /* Decode variable-length dynamic fields safely */
    if (out_msg->username_len > 0) {
        if (out_msg->username_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->username_len > in_len) {
            user_joined_message_free(out_msg);
            return -1;
        }
        out_msg->username = (char*) malloc(out_msg->username_len + 1);
        if (!out_msg->username) {
            user_joined_message_free(out_msg);
            return -1;
        }

        memcpy(out_msg->username, in_buf + dyn_off, out_msg->username_len);
        out_msg->username[out_msg->username_len] = '\0';
        dyn_off += out_msg->username_len;
    }

    (void)dyn_off;
    return 0;
}

/**
 * user_joined_message_free - Release heap memory owned by a user_joined_message_t struct.
 */
void user_joined_message_free(user_joined_message_t* msg) {
    if (!msg) return;
    if (msg->username) {
        free(msg->username);
        msg->username = NULL;
    }
    msg->username_len = 0;
}


/* ===========================================================================
 * UserLeftMessage (Type ID: 4, Fixed Header: 16 bytes)
 * ===========================================================================*/

/**
 * Sets the value of the timestamp field in the user_left_message_t struct.
 */
void user_left_message_set_timestamp(user_left_message_t* msg, const int64_t value) {
    if (msg) msg->timestamp = value;
}

/**
 * Sets the value of the username field in the user_left_message_t struct.
 */
void user_left_message_set_username(user_left_message_t* msg, const char* value) {
    if (!msg || !value) return;
    if (msg->username != NULL) {
        free(msg->username);
    }

    size_t len = strlen(value);
    char* new_value = (char*) malloc(len + 1);
    if (!new_value) return;

    memcpy(new_value, value, len + 1);
    msg->username = new_value;
    msg->username_len = (uint32_t)len;
}

/**
 * calculate_user_left_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserLeftMessage message from the fixed header.
 */
size_t calculate_user_left_message_dynamic_payload_size(const uint8_t* hdr_buf) {
    if (!hdr_buf) return 0;
    size_t dyn_total = 0;
    uint32_t username_len = get_u32_be(hdr_buf + 8);
    dyn_total += username_len;
    return dyn_total;
}

/**
 * user_left_message_marshal - Serialize UserLeftMessage to wire format.
 *
 * Writes the complete framed message into out_buf:
 *   [0:2]     Type ID (4, Big-Endian)
 *   [2:4]     Fixed header length (16, Big-Endian)
 *   [4:20]    Fixed header (fields + padding, Big-Endian encoded)
 *   [20:end]  Dynamic payload (variable-length field data)
 */
int user_left_message_marshal(const user_left_message_t* msg, uint8_t** out_buf) {
    if (!msg || !out_buf) return -1;

    /* Calculate total dynamic payload size from all variable-length fields */
    size_t dyn_size = 0;
    dyn_size += msg->username_len;

    size_t total = WIRE_FRAME_HEADER_SIZE + USER_LEFT_MESSAGE_FIXED_SIZE + dyn_size;
    if (total > MAX_ALLOWED_PACKET) return -1;

    uint8_t* buf = (uint8_t*)malloc(total);
    if (!buf) return -1;

    memset(buf, 0, WIRE_FRAME_HEADER_SIZE + USER_LEFT_MESSAGE_FIXED_SIZE);

    /* Write wire frame header identifiers */
    put_u16_be(buf, USER_LEFT_MESSAGE_TYPE_ID);
    put_u16_be(buf + WIRE_FRAME_MSG_TYPE_SIZE, USER_LEFT_MESSAGE_FIXED_SIZE);

    uint8_t* hdr = buf + WIRE_FRAME_HEADER_SIZE;
    size_t dyn_off = WIRE_FRAME_HEADER_SIZE + USER_LEFT_MESSAGE_FIXED_SIZE;
    put_u64_be(hdr + 0, (uint64_t)msg->timestamp);
    put_u32_be(hdr + 8, msg->username_len);
    if (msg->username_len > 0 && msg->username) {
        memcpy(buf + dyn_off, msg->username, msg->username_len);
        dyn_off += msg->username_len;
    }

    (void)dyn_off;
    *out_buf = buf;
    return (int)total;
}

/**
 * user_left_message_unmarshal - Deserialize UserLeftMessage from a contiguous buffer.
 *
 * in_buf points to the start of the fixed header (after the 4-byte frame header).
 * Variable-length fields are malloc'd; caller must call user_left_message_free().
 * On any error, partial allocations are cleaned up before returning.
 */
int user_left_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, user_left_message_t* out_msg) {
    if (!in_buf || !out_msg ||
        fixed_header_len < USER_LEFT_MESSAGE_FIXED_SIZE ||
        in_len < fixed_header_len ||
        in_len > MAX_ALLOWED_PACKET) {
        return -1;
    }

    memset(out_msg, 0, sizeof(user_left_message_t));

    const uint8_t* hdr = in_buf;
    size_t dyn_off = fixed_header_len;

    /* Decode fixed-size primitives from structural block offsets */
    out_msg->timestamp = (int64_t)get_u64_be(hdr + 0);
    out_msg->username_len = get_u32_be(hdr + 8);

    /* Decode variable-length dynamic fields safely */
    if (out_msg->username_len > 0) {
        if (out_msg->username_len > MAX_ALLOWED_PACKET || dyn_off + out_msg->username_len > in_len) {
            user_left_message_free(out_msg);
            return -1;
        }
        out_msg->username = (char*) malloc(out_msg->username_len + 1);
        if (!out_msg->username) {
            user_left_message_free(out_msg);
            return -1;
        }

        memcpy(out_msg->username, in_buf + dyn_off, out_msg->username_len);
        out_msg->username[out_msg->username_len] = '\0';
        dyn_off += out_msg->username_len;
    }

    (void)dyn_off;
    return 0;
}

/**
 * user_left_message_free - Release heap memory owned by a user_left_message_t struct.
 */
void user_left_message_free(user_left_message_t* msg) {
    if (!msg) return;
    if (msg->username) {
        free(msg->username);
        msg->username = NULL;
    }
    msg->username_len = 0;
}


