/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 *
 * This header defines C structure types and function prototypes for a
 * length-prefixed binary wire protocol. Each message type has:
 *
 *   - A typedef struct with explicit padding fields for deterministic layout
 *   - _Static_assert to verify struct size at compile time
 *   - Marshal/Unmarshal functions for buffer-based serialization
 *   - Stream-safe read/write functions for socket I/O (handles short reads)
 *   - A free function to release dynamically allocated fields
 *
 * Wire Protocol Frame Layout:
 *   +--------+------------------+-------------------+------------------+
 *   | Offset | Field            | Type              | Description      |
 *   +--------+------------------+-------------------+------------------+
 *   | 0      | Message Type ID  | uint16 Big-Endian | Codec selector   |
 *   | 2      | Fixed Header Len | uint16 Big-Endian | Fixed block size |
 *   | 4      | Fixed Header     | raw bytes         | Padded fields    |
 *   | 4+N    | Dynamic Payload  | raw bytes         | Strings/blobs    |
 *   +--------+------------------+-------------------+------------------+
 *
 * Safety guarantees:
 *   - MAX_ALLOWED_PACKET caps any single allocation (prevents malloc bombs)
 *   - NULL checks on every allocation result
 *   - Strings are always NULL-terminated after deserialization
 *   - free functions set pointers to NULL to prevent double-free
 *
 * Memory ownership:
 *   - After unmarshal, the caller owns the struct and must call
 *     the corresponding _free() function when done.
 *   - After marshal, no heap memory is retained by the callee.
 */
#ifndef MESSAGES_H
#define MESSAGES_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Maximum allowed packet size (16 MB).
 * Any length field exceeding this is treated as data corruption and
 * immediately rejected to prevent denial-of-service via malloc bombs.
 */
#define MAX_ALLOWED_PACKET (16 * 1024 * 1024)

#define WIRE_FRAME_MSG_TYPE_SIZE 2
#define WIRE_FRAME_MSG_FIXED_SIZE 2

/** Size of the wire frame header: 2-byte type ID + 2-byte fixed header length. */
#define WIRE_FRAME_HEADER_SIZE 4

uint16_t get_message_type(const uint8_t* buf);
uint16_t get_message_fixed_length(const uint8_t* buf);


/* ===========================================================================
 * UserMessage
 * Wire Type ID: 1
 * Fixed Header: 16 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for UserMessage. */
#define USER_MESSAGE_TYPE_ID 1

/** Byte size of the fixed header block for UserMessage (padded for alignment). */
#define USER_MESSAGE_FIXED_SIZE 16

/**
 * user_message_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
    uint32_t content_len;
    char* content;     /**< Heap-allocated; call usermessage_free() when done. */
    uint32_t attachment_len;
    uint8_t* attachment;     /**< Heap-allocated; call usermessage_free() when done. */
} user_message_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(user_message_t) >= 16,
    "wireforge: user_message_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the user_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void user_message_set_timestamp(user_message_t* msg, const int64_t value);

/**
 * Sets the value of the content field in the user_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void user_message_set_content(user_message_t* msg, const char* value);

/**
 * Sets the value of the attachment field in the user_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void user_message_set_attachment(user_message_t* msg, const uint8_t* value, size_t len);

/**
 * calculate_user_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserMessage message from the fixed header.
 */
size_t calculate_user_message_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a UserMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int user_message_marshal(const user_message_t* msg, uint8_t** out_buf);

/**
 * Deserialize a UserMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call user_message_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int user_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, user_message_t* out_msg);

/**
 * Free all dynamically allocated fields in a user_message_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void user_message_free(user_message_t* msg);


/* ===========================================================================
 * HeartbeatMessage
 * Wire Type ID: 2
 * Fixed Header: 8 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for HeartbeatMessage. */
#define HEARTBEAT_MESSAGE_TYPE_ID 2

/** Byte size of the fixed header block for HeartbeatMessage (padded for alignment). */
#define HEARTBEAT_MESSAGE_FIXED_SIZE 8

/**
 * heartbeat_message_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
} heartbeat_message_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(heartbeat_message_t) >= 8,
    "wireforge: heartbeat_message_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the heartbeat_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void heartbeat_message_set_timestamp(heartbeat_message_t* msg, const int64_t value);

/**
 * calculate_heartbeat_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the HeartbeatMessage message from the fixed header.
 */
size_t calculate_heartbeat_message_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a HeartbeatMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int heartbeat_message_marshal(const heartbeat_message_t* msg, uint8_t** out_buf);

/**
 * Deserialize a HeartbeatMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call heartbeat_message_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int heartbeat_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, heartbeat_message_t* out_msg);

/**
 * Free all dynamically allocated fields in a heartbeat_message_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void heartbeat_message_free(heartbeat_message_t* msg);


/* ===========================================================================
 * UserJoinedMessage
 * Wire Type ID: 3
 * Fixed Header: 16 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for UserJoinedMessage. */
#define USER_JOINED_MESSAGE_TYPE_ID 3

/** Byte size of the fixed header block for UserJoinedMessage (padded for alignment). */
#define USER_JOINED_MESSAGE_FIXED_SIZE 16

/**
 * user_joined_message_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
    uint32_t username_len;
    char* username;     /**< Heap-allocated; call userjoinedmessage_free() when done. */
    uint8_t _pad0[4]; /**< Explicit alignment padding. */
} user_joined_message_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(user_joined_message_t) >= 16,
    "wireforge: user_joined_message_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the user_joined_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void user_joined_message_set_timestamp(user_joined_message_t* msg, const int64_t value);

/**
 * Sets the value of the username field in the user_joined_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void user_joined_message_set_username(user_joined_message_t* msg, const char* value);

/**
 * calculate_user_joined_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserJoinedMessage message from the fixed header.
 */
size_t calculate_user_joined_message_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a UserJoinedMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int user_joined_message_marshal(const user_joined_message_t* msg, uint8_t** out_buf);

/**
 * Deserialize a UserJoinedMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call user_joined_message_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int user_joined_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, user_joined_message_t* out_msg);

/**
 * Free all dynamically allocated fields in a user_joined_message_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void user_joined_message_free(user_joined_message_t* msg);


/* ===========================================================================
 * UserLeftMessage
 * Wire Type ID: 4
 * Fixed Header: 16 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for UserLeftMessage. */
#define USER_LEFT_MESSAGE_TYPE_ID 4

/** Byte size of the fixed header block for UserLeftMessage (padded for alignment). */
#define USER_LEFT_MESSAGE_FIXED_SIZE 16

/**
 * user_left_message_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
    uint32_t username_len;
    char* username;     /**< Heap-allocated; call userleftmessage_free() when done. */
    uint8_t _pad0[4]; /**< Explicit alignment padding. */
} user_left_message_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(user_left_message_t) >= 16,
    "wireforge: user_left_message_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the user_left_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void user_left_message_set_timestamp(user_left_message_t* msg, const int64_t value);

/**
 * Sets the value of the username field in the user_left_message_t struct.
 * Note: Setting a dynamic field updates references safely; verify clean states before re-assignment.
 */
void user_left_message_set_username(user_left_message_t* msg, const char* value);

/**
 * calculate_user_left_message_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserLeftMessage message from the fixed header.
 */
size_t calculate_user_left_message_dynamic_payload_size(const uint8_t* hdr_buf);

/**
 * Serialize a UserLeftMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Pointer to the destination byte buffer pointer. The function 
 * 					will write the serialized message stream into the buffer referenced 
 * 					by this address.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int user_left_message_marshal(const user_left_message_t* msg, uint8_t** out_buf);

/**
 * Deserialize a UserLeftMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call user_left_message_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int user_left_message_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, user_left_message_t* out_msg);

/**
 * Free all dynamically allocated fields in a user_left_message_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void user_left_message_free(user_left_message_t* msg);


#ifdef __cplusplus
}
#endif

#endif /* MESSAGES_H */
