/*
 * DO NOT EDIT THIS FILE.
 * Code generated by wireforge.
 *
 * This header defines C structure types and function prototypes for a
 * length-prefixed binary wire protocol. Each message type has:
 *
 *   - A typedef struct with explicit padding fields for deterministic layout
 *   - _Static_assert to verify struct size at compile time
 *   - Marshal/Unmarshal functions for buffer-based serialization
 *   - Stream-safe read/write functions for socket I/O (handles short reads)
 *   - A free function to release dynamically allocated fields
 *
 * Wire Protocol Frame Layout:
 *   +--------+------------------+-------------------+------------------+
 *   | Offset | Field            | Type              | Description      |
 *   +--------+------------------+-------------------+------------------+
 *   | 0      | Message Type ID  | uint16 Big-Endian | Codec selector   |
 *   | 2      | Fixed Header Len | uint16 Big-Endian | Fixed block size |
 *   | 4      | Fixed Header     | raw bytes         | Padded fields    |
 *   | 4+N    | Dynamic Payload  | raw bytes         | Strings/blobs    |
 *   +--------+------------------+-------------------+------------------+
 *
 * Safety guarantees:
 *   - MAX_ALLOWED_PACKET caps any single allocation (prevents malloc bombs)
 *   - All length fields are validated before malloc()
 *   - NULL checks on every allocation result
 *   - Strings are always NUL-terminated after deserialization
 *   - free functions set pointers to NULL to prevent double-free
 *   - read/write use loops to handle EINTR and short transfers
 *
 * Memory ownership:
 *   - After unmarshal or read, the caller owns the struct and must call
 *     the corresponding _free() function when done.
 *   - After marshal or write, no heap memory is retained by the callee.
 */
#ifndef WIREFORGE_MESSAGES_H
#define WIREFORGE_MESSAGES_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Maximum allowed packet size (16 MB).
 * Any length field exceeding this is treated as data corruption and
 * immediately rejected to prevent denial-of-service via malloc bombs.
 */
#define MAX_ALLOWED_PACKET (16 * 1024 * 1024)

#define WIRE_FRAME_MSG_TYPE_SIZE 2
#define WIRE_FRAME_MSG_FIXED_SIZE 2

/** Size of the wire frame header: 2-byte type ID + 2-byte fixed header length. */
#define WIRE_FRAME_HEADER_SIZE 4

uint16_t get_message_type(const uint8_t* buf);
uint16_t get_message_fixed_length(const uint8_t* buf);


/* ===========================================================================
 * UserMessage
 * Wire Type ID: 1
 * Fixed Header: 16 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for UserMessage. */
#define USER_MESSAGE_TYPE_ID 1

/** Byte size of the fixed header block for UserMessage (padded for alignment). */
#define USER_MESSAGE_FIXED_SIZE 16

/**
 * UserMessage_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
    uint32_t content_len;
    char* content;     /**< Heap-allocated; call usermessage_free() when done. */
    uint32_t attachment_len;
    uint8_t* attachment;     /**< Heap-allocated; call usermessage_free() when done. */
} UserMessage_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(UserMessage_t) >= 16,
    "wireforge: UserMessage_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the UserMessage_t struct.
 */
void usermessage_set_timestamp(UserMessage_t* msg, const int64_t value);

/**
 * Sets the value of the content field in the UserMessage_t struct.
 */
void usermessage_set_content(UserMessage_t* msg, const char* value);

/**
 * Sets the value of the attachment field in the UserMessage_t struct.
 */
void usermessage_set_attachment(UserMessage_t* msg, const uint8_t* value, size_t len);

/**
 * calculate_usermessage_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserMessage message from the fixed header.
 */
size_t calculate_usermessage_dynamic_payload_size(uint8_t* hdr_buf);

/**
 * Serialize a UserMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Destination buffer (must be at least
 *                  WIRE_FRAME_HEADER_SIZE + USER_MESSAGE_FIXED_SIZE + dynamic payload bytes).
 * @param buf_size  Total capacity of out_buf in bytes.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int usermessage_marshal(const UserMessage_t* msg, uint8_t** out_buf);

/**
 * Deserialize a UserMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call usermessage_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int usermessage_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, UserMessage_t* out_msg);

/**
 * Free all dynamically allocated fields in a UserMessage_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void usermessage_free(UserMessage_t* msg);


/* ===========================================================================
 * HeartbeatMessage
 * Wire Type ID: 2
 * Fixed Header: 8 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for HeartbeatMessage. */
#define HEARTBEAT_MESSAGE_TYPE_ID 2

/** Byte size of the fixed header block for HeartbeatMessage (padded for alignment). */
#define HEARTBEAT_MESSAGE_FIXED_SIZE 8

/**
 * HeartbeatMessage_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
} HeartbeatMessage_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(HeartbeatMessage_t) >= 8,
    "wireforge: HeartbeatMessage_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the HeartbeatMessage_t struct.
 */
void heartbeatmessage_set_timestamp(HeartbeatMessage_t* msg, const int64_t value);

/**
 * calculate_heartbeatmessage_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the HeartbeatMessage message from the fixed header.
 */
size_t calculate_heartbeatmessage_dynamic_payload_size(uint8_t* hdr_buf);

/**
 * Serialize a HeartbeatMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Destination buffer (must be at least
 *                  WIRE_FRAME_HEADER_SIZE + HEARTBEAT_MESSAGE_FIXED_SIZE + dynamic payload bytes).
 * @param buf_size  Total capacity of out_buf in bytes.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int heartbeatmessage_marshal(const HeartbeatMessage_t* msg, uint8_t** out_buf);

/**
 * Deserialize a HeartbeatMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call heartbeatmessage_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int heartbeatmessage_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, HeartbeatMessage_t* out_msg);

/**
 * Free all dynamically allocated fields in a HeartbeatMessage_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void heartbeatmessage_free(HeartbeatMessage_t* msg);


/* ===========================================================================
 * UserJoinedMessage
 * Wire Type ID: 3
 * Fixed Header: 16 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for UserJoinedMessage. */
#define USER_JOINED_MESSAGE_TYPE_ID 3

/** Byte size of the fixed header block for UserJoinedMessage (padded for alignment). */
#define USER_JOINED_MESSAGE_FIXED_SIZE 16

/**
 * UserJoinedMessage_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
    uint32_t username_len;
    char* username;     /**< Heap-allocated; call userjoinedmessage_free() when done. */
    uint8_t _pad0[4]; /**< Explicit alignment padding. */
} UserJoinedMessage_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(UserJoinedMessage_t) >= 16,
    "wireforge: UserJoinedMessage_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the UserJoinedMessage_t struct.
 */
void userjoinedmessage_set_timestamp(UserJoinedMessage_t* msg, const int64_t value);

/**
 * Sets the value of the username field in the UserJoinedMessage_t struct.
 */
void userjoinedmessage_set_username(UserJoinedMessage_t* msg, const char* value);

/**
 * calculate_userjoinedmessage_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserJoinedMessage message from the fixed header.
 */
size_t calculate_userjoinedmessage_dynamic_payload_size(uint8_t* hdr_buf);

/**
 * Serialize a UserJoinedMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Destination buffer (must be at least
 *                  WIRE_FRAME_HEADER_SIZE + USER_JOINED_MESSAGE_FIXED_SIZE + dynamic payload bytes).
 * @param buf_size  Total capacity of out_buf in bytes.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int userjoinedmessage_marshal(const UserJoinedMessage_t* msg, uint8_t** out_buf);

/**
 * Deserialize a UserJoinedMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call userjoinedmessage_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int userjoinedmessage_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, UserJoinedMessage_t* out_msg);

/**
 * Free all dynamically allocated fields in a UserJoinedMessage_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void userjoinedmessage_free(UserJoinedMessage_t* msg);


/* ===========================================================================
 * UserLeftMessage
 * Wire Type ID: 4
 * Fixed Header: 16 bytes (including alignment padding)
 * ===========================================================================*/

/** Wire protocol message type ID for UserLeftMessage. */
#define USER_LEFT_MESSAGE_TYPE_ID 4

/** Byte size of the fixed header block for UserLeftMessage (padded for alignment). */
#define USER_LEFT_MESSAGE_FIXED_SIZE 16

/**
 * UserLeftMessage_t - Wire-serializable message structure.
 *
 * Fixed-size fields are stored inline. Variable-length fields (strings, byte
 * arrays) are represented as a uint32 length prefix plus a heap-allocated
 * pointer. Explicit padding fields (_padN) ensure the struct has a
 * deterministic memory layout matching the wire format regardless of compiler.
 *
 * IMPORTANT: Do not reorder fields. The layout must match the wire format.
 */
typedef struct {
    int64_t timestamp;
    uint32_t username_len;
    char* username;     /**< Heap-allocated; call userleftmessage_free() when done. */
    uint8_t _pad0[4]; /**< Explicit alignment padding. */
} UserLeftMessage_t;

/* Compile-time size check: catch layout mismatches before runtime. */
_Static_assert(sizeof(UserLeftMessage_t) >= 16,
    "wireforge: UserLeftMessage_t fixed layout size mismatch");

/**
 * Sets the value of the timestamp field in the UserLeftMessage_t struct.
 */
void userleftmessage_set_timestamp(UserLeftMessage_t* msg, const int64_t value);

/**
 * Sets the value of the username field in the UserLeftMessage_t struct.
 */
void userleftmessage_set_username(UserLeftMessage_t* msg, const char* value);

/**
 * calculate_userleftmessage_dynamic_payload_size - Compute the total size of
 * all variable-length fields in the UserLeftMessage message from the fixed header.
 */
size_t calculate_userleftmessage_dynamic_payload_size(uint8_t* hdr_buf);

/**
 * Serialize a UserLeftMessage message into out_buf in wire format.
 *
 * @param msg       Pointer to the message to serialize (must not be NULL).
 * @param out_buf   Destination buffer (must be at least
 *                  WIRE_FRAME_HEADER_SIZE + USER_LEFT_MESSAGE_FIXED_SIZE + dynamic payload bytes).
 * @param buf_size  Total capacity of out_buf in bytes.
 * @return          Total bytes written on success, or -1 on error
 *                  (NULL pointer, buffer too small, exceeds MAX_ALLOWED_PACKET).
 */
int userleftmessage_marshal(const UserLeftMessage_t* msg, uint8_t** out_buf);

/**
 * Deserialize a UserLeftMessage message from a contiguous buffer.
 *
 * @param in_buf           Input buffer starting at the fixed header (after frame header).
 * @param in_len           Total available bytes in in_buf (fixed header + dynamic payload).
 * @param fixed_header_len Fixed header length as read from the wire frame header.
 * @param out_msg          Output struct (zeroed on entry; fields populated on success).
 * @return                 0 on success, -1 on error (truncated data, allocation failure,
 *                         length exceeds MAX_ALLOWED_PACKET).
 *
 * On success, caller MUST call userleftmessage_free(out_msg) when done to release
 * any heap-allocated variable-length fields.
 */
int userleftmessage_unmarshal(const uint8_t* in_buf, size_t in_len, uint16_t fixed_header_len, UserLeftMessage_t* out_msg);

/**
 * Free all dynamically allocated fields in a UserLeftMessage_t struct.
 *
 * Safe to call multiple times: pointers are set to NULL and lengths to 0
 * after release. Does NOT free the struct itself (caller manages lifetime).
 *
 * @param msg  Pointer to the struct to clean up (NULL is a safe no-op).
 */
void userleftmessage_free(UserLeftMessage_t* msg);


#ifdef __cplusplus
}
#endif

#endif /* WIREFORGE_MESSAGES_H */
