openapi: 3.1.0
info:
  version: 1.0.0
  title: Chatapp Message Schemas
paths: {}
components:
  schemas:
    UserMessage:
      type: object
      properties:
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        attachment:
          type: string
          format: binary
    HeartbeatMessage:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
