// Code generated by wireforge. DO NOT EDIT.
// To know more visit: github.com/avatar31/wireforge
//
// This file contains type-safe message definitions with binary serialization
// for a length-prefixed wire protocol. All multi-byte integers are encoded in
// Big-Endian (network byte order) to ensure cross-platform compatibility.
//
// Wire Protocol Frame Layout:
//
//	+--------+---------------------+-------------------+--------------------+
//	| Offset | Field               | Type              | Description        |
//	+--------+---------------------+-------------------+--------------------+
//	| 0      | Message Type ID     | uint16 Big-Endian | Codec selector     |
//	| 2      | Fixed Payload Len   | uint16 Big-Endian | Fixed block size   |
//	| 4      | Overall Payload Len | uint32 Big-Endian | Fixed + Dynamic    |
//	| 8      | Fixed Payload       | raw bytes         | Padded fields      |
//	| 8+N    | Dynamic Payload     | raw bytes         | Strings/blobs      |
//	+--------+---------------------+-------------------+--------------------+
//
// Safety guarantees:
//   - MaxAllowedPacket (16 MB) prevents memory allocation exploits from
//     corrupted length fields ("poison pill" attack mitigation).
//   - init() performs compile-time layout validation via unsafe.Sizeof to
//     catch struct size mismatches between the generator and the Go compiler.
//   - All reads use io.ReadFull to handle socket short-reads correctly.
//   - Big-Endian encoding ensures consistent behavior across architectures.
package messages

import (
	"encoding/binary"
	"fmt"
	"io"
	"math"
	"unsafe"
)

const (
	// FrameHeaderSize represents the 2 bytes for TypeID, 2 bytes for FixedBlockLen
	// and 4 bytes for overall data size.
	FrameHeaderSize = 8

	// 2 bytes for the count prefix of any array
	ArrayCountPrefixSize = 2

	// 2 bytes for the type tag of any array
	TypeMarkerSize = 2

	// 4 bytes for the length prefix of any string or byte slice
	StrOrByteLenPrefixSize = 4

	// MaxAllowedPacket is the hard ceiling on any single message size (16 MB).
	// Any incoming length field exceeding this value is treated as corrupted
	// data and rejected immediately, preventing denial-of-service via
	// malicious allocation requests.
	MaxAllowedPacket = 16 * 1024 * 1024

	// 2^16 - 1, since array length is encoded as uint16
	MaxArrayElements = 65535
)

// Constants for our 2-byte Type Markers
const (
	TagNone           uint16 = 0x0000
	TagUint8          uint16 = 0x0001
	TagInt8           uint16 = 0x0002
	TagBool           uint16 = 0x0003
	TagUint16         uint16 = 0x0004
	TagInt16          uint16 = 0x0005
	TagUint32         uint16 = 0x0006
	TagInt32          uint16 = 0x0007
	TagFloat32        uint16 = 0x0008
	TagUint64         uint16 = 0x0009
	TagInt64          uint16 = 0x000A
	TagFloat64        uint16 = 0x000B
	TagString         uint16 = 0x000C
	TagBytes          uint16 = 0x000D
	TagArray          uint16 = 0x000E
	Tag2DArray        uint16 = 0x000F
	Tag3DArray        uint16 = 0x0010
	TagNoPaddingMsg   uint16 = 0x0020
	TagSmallFieldsMsg uint16 = 0x0021
	TagMixedSizeMsg   uint16 = 0x0022
	TagAlignedMsg     uint16 = 0x0023
)

// Compile-time import usage guarantees.
var (
	_ = binary.BigEndian
	_ = io.ReadFull
	_ = math.Float32frombits
	_ = unsafe.Sizeof(uint8(0))
)

// ---------------------------------------------------------------------------
// NoPaddingMsg
// ---------------------------------------------------------------------------
// Wire Type ID: 1
// Fixed Block Length: 8 bytes (includes alignment padding)
// Overall Block Length: 8 bytes + Runtime dynamic payload
// ---------------------------------------------------------------------------

// NoPaddingMsg represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type NoPaddingMsg struct {
	// A single 8-byte field; no padding required.
	Value int64
}

// NoPaddingMsgFixedSize is the byte size of the fixed block portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const NoPaddingMsgFixedSize = 8

// MessageTypeID returns the unique wire protocol type identifier for NoPaddingMsg.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (n *NoPaddingMsg) MessageTypeID() uint16 {
	return 1
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg NoPaddingMsg
	_ = msg
	if unsafe.Sizeof(msg.Value) != 8 {
		panic("wireforge: NoPaddingMsg.Value size mismatch")
	}
}

func (n *NoPaddingMsg) DynamicPayloadSize() int {
	dynamicSize := 0

	return dynamicSize
}

func (n *NoPaddingMsg) Size() int {
	return FrameHeaderSize + NoPaddingMsgFixedSize + n.DynamicPayloadSize()
}

// Marshal serializes the NoPaddingMsg message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (1)
//	[2:4]     Fixed Block Length (8)
//	[4:8]     Fixed and Dynamic Block Length
//	[8:16]    Fixed payload (primitives + length prefixes, Big-Endian)
//	[16:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (n *NoPaddingMsg) Marshal() ([]byte, error) {
	payloadSize := NoPaddingMsgFixedSize + n.DynamicPayloadSize()
	totalSize := FrameHeaderSize + payloadSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("NoPaddingMsg message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed payload length + overall payload length
	binary.BigEndian.PutUint16(buf[0:2], 1)
	binary.BigEndian.PutUint16(buf[2:4], uint16(NoPaddingMsgFixedSize))
	binary.BigEndian.PutUint32(buf[4:8], uint32(payloadSize))

	// Fixed block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + NoPaddingMsgFixedSize

	binary.BigEndian.PutUint64(hdr[0:8], uint64(n.Value))

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a NoPaddingMsg from the wire after the 8-byte frame
// header has already been consumed. The caller provides fixedPayloadSize (read
// from the frame) and overallPayloadSize so forward-compatible readers can skip
// unknown trailing bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (n *NoPaddingMsg) Unmarshal(reader io.Reader,
	fixedPayloadSize uint16, _ uint32) error {
	if int(fixedPayloadSize) < NoPaddingMsgFixedSize {
		return fmt.Errorf("NoPaddingMsg fixed payload size too short: got %d, need %d", fixedPayloadSize, NoPaddingMsgFixedSize)
	}

	hdr := make([]byte, fixedPayloadSize)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading NoPaddingMsg fixed payload: %w", err)
	}

	n.Value = int64(binary.BigEndian.Uint64(hdr[0:8]))

	return nil
}

// ---------------------------------------------------------------------------
// SmallFieldsMsg
// ---------------------------------------------------------------------------
// Wire Type ID: 2
// Fixed Block Length: 4 bytes (includes alignment padding)
// Overall Block Length: 4 bytes + Runtime dynamic payload
// ---------------------------------------------------------------------------

// SmallFieldsMsg represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type SmallFieldsMsg struct {
	// First byte field.
	Alpha uint8
	// Second byte field (signed).
	Beta int8
	// Boolean field (1 byte).
	Gamma bool
}

// SmallFieldsMsgFixedSize is the byte size of the fixed block portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const SmallFieldsMsgFixedSize = 4

// MessageTypeID returns the unique wire protocol type identifier for SmallFieldsMsg.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (s *SmallFieldsMsg) MessageTypeID() uint16 {
	return 2
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg SmallFieldsMsg
	_ = msg
	if unsafe.Sizeof(msg.Alpha) != 1 {
		panic("wireforge: SmallFieldsMsg.Alpha size mismatch")
	}
	if unsafe.Sizeof(msg.Beta) != 1 {
		panic("wireforge: SmallFieldsMsg.Beta size mismatch")
	}
	if unsafe.Sizeof(msg.Gamma) != 1 {
		panic("wireforge: SmallFieldsMsg.Gamma size mismatch")
	}
}

func (s *SmallFieldsMsg) DynamicPayloadSize() int {
	dynamicSize := 0

	return dynamicSize
}

func (s *SmallFieldsMsg) Size() int {
	return FrameHeaderSize + SmallFieldsMsgFixedSize + s.DynamicPayloadSize()
}

// Marshal serializes the SmallFieldsMsg message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (2)
//	[2:4]     Fixed Block Length (4)
//	[4:8]     Fixed and Dynamic Block Length
//	[8:12]    Fixed payload (primitives + length prefixes, Big-Endian)
//	[12:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (s *SmallFieldsMsg) Marshal() ([]byte, error) {
	payloadSize := SmallFieldsMsgFixedSize + s.DynamicPayloadSize()
	totalSize := FrameHeaderSize + payloadSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("SmallFieldsMsg message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed payload length + overall payload length
	binary.BigEndian.PutUint16(buf[0:2], 2)
	binary.BigEndian.PutUint16(buf[2:4], uint16(SmallFieldsMsgFixedSize))
	binary.BigEndian.PutUint32(buf[4:8], uint32(payloadSize))

	// Fixed block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + SmallFieldsMsgFixedSize

	hdr[0] = s.Alpha
	hdr[1] = uint8(s.Beta)
	if s.Gamma {
		hdr[2] = 1
	} else {
		hdr[2] = 0
	}

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a SmallFieldsMsg from the wire after the 8-byte frame
// header has already been consumed. The caller provides fixedPayloadSize (read
// from the frame) and overallPayloadSize so forward-compatible readers can skip
// unknown trailing bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (s *SmallFieldsMsg) Unmarshal(reader io.Reader,
	fixedPayloadSize uint16, _ uint32) error {
	if int(fixedPayloadSize) < SmallFieldsMsgFixedSize {
		return fmt.Errorf("SmallFieldsMsg fixed payload size too short: got %d, need %d", fixedPayloadSize, SmallFieldsMsgFixedSize)
	}

	hdr := make([]byte, fixedPayloadSize)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading SmallFieldsMsg fixed payload: %w", err)
	}

	s.Alpha = hdr[0]
	s.Beta = int8(hdr[1])
	s.Gamma = hdr[2] != 0

	return nil
}

// ---------------------------------------------------------------------------
// MixedSizeMsg
// ---------------------------------------------------------------------------
// Wire Type ID: 3
// Fixed Block Length: 16 bytes (includes alignment padding)
// Overall Block Length: 16 bytes + Runtime dynamic payload
// ---------------------------------------------------------------------------

// MixedSizeMsg represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type MixedSizeMsg struct {
	// 8-byte integer field.
	Big int64
	// 1-byte boolean field.
	Flag bool
}

// MixedSizeMsgFixedSize is the byte size of the fixed block portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const MixedSizeMsgFixedSize = 16

// MessageTypeID returns the unique wire protocol type identifier for MixedSizeMsg.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (m *MixedSizeMsg) MessageTypeID() uint16 {
	return 3
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg MixedSizeMsg
	_ = msg
	if unsafe.Sizeof(msg.Big) != 8 {
		panic("wireforge: MixedSizeMsg.Big size mismatch")
	}
	if unsafe.Sizeof(msg.Flag) != 1 {
		panic("wireforge: MixedSizeMsg.Flag size mismatch")
	}
}

func (m *MixedSizeMsg) DynamicPayloadSize() int {
	dynamicSize := 0

	return dynamicSize
}

func (m *MixedSizeMsg) Size() int {
	return FrameHeaderSize + MixedSizeMsgFixedSize + m.DynamicPayloadSize()
}

// Marshal serializes the MixedSizeMsg message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (3)
//	[2:4]     Fixed Block Length (16)
//	[4:8]     Fixed and Dynamic Block Length
//	[8:24]    Fixed payload (primitives + length prefixes, Big-Endian)
//	[24:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (m *MixedSizeMsg) Marshal() ([]byte, error) {
	payloadSize := MixedSizeMsgFixedSize + m.DynamicPayloadSize()
	totalSize := FrameHeaderSize + payloadSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("MixedSizeMsg message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed payload length + overall payload length
	binary.BigEndian.PutUint16(buf[0:2], 3)
	binary.BigEndian.PutUint16(buf[2:4], uint16(MixedSizeMsgFixedSize))
	binary.BigEndian.PutUint32(buf[4:8], uint32(payloadSize))

	// Fixed block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + MixedSizeMsgFixedSize

	binary.BigEndian.PutUint64(hdr[0:8], uint64(m.Big))
	if m.Flag {
		hdr[8] = 1
	} else {
		hdr[8] = 0
	}

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a MixedSizeMsg from the wire after the 8-byte frame
// header has already been consumed. The caller provides fixedPayloadSize (read
// from the frame) and overallPayloadSize so forward-compatible readers can skip
// unknown trailing bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (m *MixedSizeMsg) Unmarshal(reader io.Reader,
	fixedPayloadSize uint16, _ uint32) error {
	if int(fixedPayloadSize) < MixedSizeMsgFixedSize {
		return fmt.Errorf("MixedSizeMsg fixed payload size too short: got %d, need %d", fixedPayloadSize, MixedSizeMsgFixedSize)
	}

	hdr := make([]byte, fixedPayloadSize)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading MixedSizeMsg fixed payload: %w", err)
	}

	m.Big = int64(binary.BigEndian.Uint64(hdr[0:8]))
	m.Flag = hdr[8] != 0

	return nil
}

// ---------------------------------------------------------------------------
// AlignedMsg
// ---------------------------------------------------------------------------
// Wire Type ID: 4
// Fixed Block Length: 12 bytes (includes alignment padding)
// Overall Block Length: 12 bytes + Runtime dynamic payload
// ---------------------------------------------------------------------------

// AlignedMsg represents a wire-serializable message.
// Fields are ordered and padded to match natural alignment requirements,
// ensuring identical memory layout between Go and C implementations.
type AlignedMsg struct {
	// 4-byte integer field.
	Count int32
	// 4-byte float field.
	Rate float32
	// Variable-length string (4-byte length prefix in fixed block).
	Name string
}

// AlignedMsgFixedSize is the byte size of the fixed block portion
// (all fixed-width fields including alignment padding, plus uint32 length
// prefixes for any variable-length fields). This value is encoded in the
// wire frame header so the receiver knows how many bytes to read before
// parsing dynamic payload data.
const AlignedMsgFixedSize = 12

// MessageTypeID returns the unique wire protocol type identifier for AlignedMsg.
// This ID occupies the first 2 bytes of every framed message on the wire and
// is used by the receiver to select the correct deserialization codec.
func (a *AlignedMsg) MessageTypeID() uint16 {
	return 4
}

func init() {
	// Compile-time layout validation.
	// If the Go compiler's struct layout disagrees with our computed field
	// sizes, this panic fires immediately at program startup rather than
	// allowing silent data corruption on the wire.
	var msg AlignedMsg
	_ = msg
	if unsafe.Sizeof(msg.Count) != 4 {
		panic("wireforge: AlignedMsg.Count size mismatch")
	}
	if unsafe.Sizeof(msg.Rate) != 4 {
		panic("wireforge: AlignedMsg.Rate size mismatch")
	}
}

func (a *AlignedMsg) DynamicPayloadSize() int {
	dynamicSize := 0
	dynamicSize += calcTypeSize(a.Name)

	return dynamicSize
}

func (a *AlignedMsg) Size() int {
	return FrameHeaderSize + AlignedMsgFixedSize + a.DynamicPayloadSize()
}

// Marshal serializes the AlignedMsg message into wire format and writes the
// complete framed message (header + payload) to writer in a single Write call.
//
// Wire layout written:
//
//	[0:2]     Message Type ID (4)
//	[2:4]     Fixed Block Length (12)
//	[4:8]     Fixed and Dynamic Block Length
//	[8:20]    Fixed payload (primitives + length prefixes, Big-Endian)
//	[20:end]  Dynamic payload (concatenated variable-length data)
//
// Returns an error if the total message size exceeds MaxAllowedPacket.
func (a *AlignedMsg) Marshal() ([]byte, error) {
	payloadSize := AlignedMsgFixedSize + a.DynamicPayloadSize()
	totalSize := FrameHeaderSize + payloadSize
	if totalSize > MaxAllowedPacket {
		return nil, fmt.Errorf("AlignedMsg message size %d exceeds MaxAllowedPacket", totalSize)
	}

	buf := make([]byte, totalSize)

	// Frame header: type ID + fixed payload length + overall payload length
	binary.BigEndian.PutUint16(buf[0:2], 4)
	binary.BigEndian.PutUint16(buf[2:4], uint16(AlignedMsgFixedSize))
	binary.BigEndian.PutUint32(buf[4:8], uint32(payloadSize))

	// Fixed block (starts at offset FrameHeaderSize)
	hdr := buf[FrameHeaderSize:]
	// Dynamic payload sections start directly after the fixed wire block
	dynOff := FrameHeaderSize + AlignedMsgFixedSize

	binary.BigEndian.PutUint32(hdr[0:4], uint32(a.Count))
	binary.BigEndian.PutUint32(hdr[4:8], math.Float32bits(a.Rate))

	copy(buf[dynOff:], a.Name)
	binary.BigEndian.PutUint32(hdr[8:12], uint32(len(a.Name)))
	dynOff += len(a.Name)

	_ = dynOff
	return buf, nil
}

// Unmarshal deserializes a AlignedMsg from the wire after the 8-byte frame
// header has already been consumed. The caller provides fixedPayloadSize (read
// from the frame) and overallPayloadSize so forward-compatible readers can skip
// unknown trailing bytes in the fixed header if a newer sender adds fields.
//
// All variable-length fields are validated against MaxAllowedPacket before
// allocation, and io.ReadFull is used to guarantee complete reads even on
// streaming sockets that may deliver partial data.
func (a *AlignedMsg) Unmarshal(reader io.Reader,
	fixedPayloadSize uint16, _ uint32) error {
	if int(fixedPayloadSize) < AlignedMsgFixedSize {
		return fmt.Errorf("AlignedMsg fixed payload size too short: got %d, need %d", fixedPayloadSize, AlignedMsgFixedSize)
	}

	hdr := make([]byte, fixedPayloadSize)
	if _, err := io.ReadFull(reader, hdr); err != nil {
		return fmt.Errorf("reading AlignedMsg fixed payload: %w", err)
	}

	a.Count = int32(binary.BigEndian.Uint32(hdr[0:4]))
	a.Rate = math.Float32frombits(binary.BigEndian.Uint32(hdr[4:8]))
	a_Name_len := binary.BigEndian.Uint32(hdr[8:12])
	if a_Name_len > MaxAllowedPacket {
		return fmt.Errorf("AlignedMsg.Name length %d exceeds MaxAllowedPacket", a_Name_len)
	}

	// Read dynamic payload: variable-length fields are appended sequentially
	// after the fixed payload in the same order as their length prefixes above.

	if a_Name_len > 0 {
		a_Name_buf := make([]byte, a_Name_len)
		if _, err := io.ReadFull(reader, a_Name_buf); err != nil {
			return fmt.Errorf("wireforge: reading AlignedMsg.Name payload: %w", err)
		}
		a.Name = string(a_Name_buf)
	}

	return nil
}

// ReadMessageFrame reads the 8-byte wire frame header from r and returns the
// message type ID, fixed & overall payload length. Use this when you need to dispatch
// to different message types based on the type ID before calling Unmarshal.
func ReadMessageFrame(r io.Reader) (uint16, uint16, uint32, error) {
	var frame [FrameHeaderSize]byte
	if _, err := io.ReadFull(r, frame[:]); err != nil {
		return 0, 0, 0, err
	}
	typeID := binary.BigEndian.Uint16(frame[0:2])
	fixedPayloadLen := binary.BigEndian.Uint16(frame[2:4])
	overallPayloadLen := binary.BigEndian.Uint32(frame[4:8])

	return typeID, fixedPayloadLen, overallPayloadLen, nil
}

// ---------------------------------------------------------------------------
// Internal Helpers
// ---------------------------------------------------------------------------

// CalcArraySize calculates the size of a top-level homogeneous slice.
func calcArraySize[T any](elements ...T) int {
	size := ArrayCountPrefixSize
	if len(elements) == 0 {
		return size
	}

	// Primitive slices
	switch any(elements).(type) {
	case []bool, []int8, []uint8:
		return size + len(elements)
	case []int16, []uint16:
		return size + (len(elements) * 2)
	case []int32, []uint32, []float32:
		return size + (len(elements) * 4)
	case []int64, []uint64, []float64:
		return size + (len(elements) * 8)
	}

	// Non-Primitive Flat Arrays (e.g., []string, []any etc.)
	// These write a single 2-byte tag at the root, plus raw values.
	size += TypeMarkerSize
	for _, v := range elements {
		size += calcTypeSize(v)
	}

	return size
}

// calcTypeSize calculates the size of a single element,
// including any length prefixes for variable-length types.
func calcTypeSize(ele any) int {
	switch val := ele.(type) {
	// Primitives
	case bool, int8, uint8:
		return 1
	case int16, uint16:
		return 2
	case int32, uint32, float32:
		return 4
	case int64, uint64, float64:
		return 8

	// Strings & Byte Slices still require their 4-byte length prefix
	case string:
		return StrOrByteLenPrefixSize + len(val)
	case []byte:
		return StrOrByteLenPrefixSize + len(val)

	case *NoPaddingMsg:
		if val != nil {
			return val.Size()
		}
		return 0
	case []*NoPaddingMsg:
		// Layout: [Inner Type Tag (2B)] [Inner Element Count (2B)] + inner raw elements
		size := TypeMarkerSize + ArrayCountPrefixSize
		for _, innerItem := range val {
			size += calcTypeSize(innerItem)
		}
		return size

	case *SmallFieldsMsg:
		if val != nil {
			return val.Size()
		}
		return 0
	case []*SmallFieldsMsg:
		// Layout: [Inner Type Tag (2B)] [Inner Element Count (2B)] + inner raw elements
		size := TypeMarkerSize + ArrayCountPrefixSize
		for _, innerItem := range val {
			size += calcTypeSize(innerItem)
		}
		return size

	case *MixedSizeMsg:
		if val != nil {
			return val.Size()
		}
		return 0
	case []*MixedSizeMsg:
		// Layout: [Inner Type Tag (2B)] [Inner Element Count (2B)] + inner raw elements
		size := TypeMarkerSize + ArrayCountPrefixSize
		for _, innerItem := range val {
			size += calcTypeSize(innerItem)
		}
		return size

	case *AlignedMsg:
		if val != nil {
			return val.Size()
		}
		return 0
	case []*AlignedMsg:
		// Layout: [Inner Type Tag (2B)] [Inner Element Count (2B)] + inner raw elements
		size := TypeMarkerSize + ArrayCountPrefixSize
		for _, innerItem := range val {
			size += calcTypeSize(innerItem)
		}
		return size

	// Multi-Dimensional Layouts ([]any)
	case []any:
		// Layout: [Inner Type Tag (2B)] [Inner Element Count (2B)] + inner raw elements
		size := TypeMarkerSize + ArrayCountPrefixSize
		for _, innerItem := range val {
			size += calcTypeSize(innerItem)
		}
		return size
	case []string:
		// Layout: [Inner Type Tag (2B)] [Inner Element Count (2B)] + inner raw elements
		size := TypeMarkerSize + ArrayCountPrefixSize
		for _, innerItem := range val {
			size += calcTypeSize(innerItem)
		}
		return size
	default:
		// This should never reach because calcTypeSize will always be called with known types.
		panic(fmt.Errorf("unsupported type in size calculator: %T", val))
	}
}

func sliceToBytes[T any](eleType uint16, elements any) ([]byte, error) {
	switch arr := elements.(type) {
	case []T:
		overallItemsCount, arrBytes, err := oneDimensionalSliceToBytes(arr)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize 1D slice: %w", err)
		}
		result := make([]byte, (TypeMarkerSize*2)+ArrayCountPrefixSize+len(arrBytes))
		binary.BigEndian.PutUint16(result[0:], TagArray)
		binary.BigEndian.PutUint16(result[2:], eleType)
		binary.BigEndian.PutUint16(result[4:], uint16(overallItemsCount))
		copy(result[6:], arrBytes)
		return result, nil

	case [][]T:
		overallItemsCount, arrBytes, err := twoDimensionalSliceToBytes(arr)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize 2D slice: %w", err)
		}
		result := make([]byte, (TypeMarkerSize*2)+ArrayCountPrefixSize+len(arrBytes))
		binary.BigEndian.PutUint16(result[0:], Tag2DArray)
		binary.BigEndian.PutUint16(result[2:], eleType)
		binary.BigEndian.PutUint16(result[4:], uint16(overallItemsCount))
		copy(result[6:], arrBytes)
		return result, nil

	case [][][]T:
		overallItemsCount, arrBytes, err := threeDimensionalSliceToBytes(arr)
		if err != nil {
			return nil, fmt.Errorf("failed to serialize 3D slice: %w", err)
		}
		result := make([]byte, (TypeMarkerSize*2)+ArrayCountPrefixSize+len(arrBytes))
		binary.BigEndian.PutUint16(result[0:], Tag3DArray)
		binary.BigEndian.PutUint16(result[2:], eleType)
		binary.BigEndian.PutUint16(result[4:], uint16(overallItemsCount))
		copy(result[6:], arrBytes)
		return result, nil

	default:
		return nil, fmt.Errorf("unsupported slice type: %T", arr)
	}
}

func threeDimensionalSliceToBytes[T any](elements [][][]T) (int, []byte, error) {
	count := len(elements)
	if count == 0 {
		return 0, binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > int(MaxArrayElements) {
		return 0, nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	itemsCount := 0
	buf := make([]byte, ArrayCountPrefixSize, 512)
	binary.BigEndian.PutUint16(buf[0:], uint16(count))
	for i, v := range elements {
		n, bytes, err := twoDimensionalSliceToBytes(v)
		if err != nil {
			return 0, nil, fmt.Errorf("failed to serialize 2D slice at index %d: %w", i, err)
		}
		buf = append(buf, bytes...)
		itemsCount += n

	}
	return itemsCount, buf, nil
}

func twoDimensionalSliceToBytes[T any](elements [][]T) (int, []byte, error) {
	count := len(elements)
	if count == 0 {
		return 0, binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > int(MaxArrayElements) {
		return 0, nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	itemsCount := 0
	buf := make([]byte, ArrayCountPrefixSize, 256)
	binary.BigEndian.PutUint16(buf[0:], uint16(count))
	for i, v := range elements {
		n, bytes, err := oneDimensionalSliceToBytes(v)
		if err != nil {
			return 0, nil, fmt.Errorf("failed to serialize 1D slice at index %d: %w", i, err)
		}
		buf = append(buf, bytes...)
		itemsCount += n
	}
	return itemsCount, buf, nil
}

func oneDimensionalSliceToBytes[T any](elements []T) (int, []byte, error) {
	count := len(elements)
	if count == 0 {
		return 0, binary.BigEndian.AppendUint16(nil, 0), nil
	}

	if count > int(MaxArrayElements) {
		return 0, nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	switch sl := any(elements).(type) {
	// --- 1-Byte Primitives ---
	case []bool:
		buf := make([]byte, ArrayCountPrefixSize+count)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			if v {
				buf[ArrayCountPrefixSize+i] = 1
			} else {
				buf[ArrayCountPrefixSize+i] = 0
			}
		}
		return count, buf, nil

	case []uint8:
		buf := make([]byte, ArrayCountPrefixSize+count)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		copy(buf[ArrayCountPrefixSize:], sl)
		return count, buf, nil

	case []int8:
		buf := make([]byte, ArrayCountPrefixSize+count)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			buf[ArrayCountPrefixSize+i] = byte(v)
		}
		return count, buf, nil

	// --- 2-Byte Primitives ---
	case []uint16:
		buf := make([]byte, ArrayCountPrefixSize+(count*2))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint16(buf[ArrayCountPrefixSize+i*2:], v)
		}
		return count, buf, nil

	case []int16:
		buf := make([]byte, ArrayCountPrefixSize+(count*2))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint16(buf[ArrayCountPrefixSize+i*2:], uint16(v))
		}
		return count, buf, nil

	// --- 4-Byte Primitives ---
	case []uint32:
		buf := make([]byte, ArrayCountPrefixSize+(count*4))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint32(buf[ArrayCountPrefixSize+i*4:], v)
		}
		return count, buf, nil

	case []int32:
		buf := make([]byte, ArrayCountPrefixSize+(count*4))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint32(buf[ArrayCountPrefixSize+i*4:], uint32(v))
		}
		return count, buf, nil

	case []float32:
		buf := make([]byte, ArrayCountPrefixSize+(count*4))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint32(buf[ArrayCountPrefixSize+i*4:], math.Float32bits(v))
		}
		return count, buf, nil

	// --- 8-Byte Primitives ---
	case []uint64:
		buf := make([]byte, ArrayCountPrefixSize+(count*8))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint64(buf[ArrayCountPrefixSize+i*8:], v)
		}
		return count, buf, nil

	case []int64:
		buf := make([]byte, ArrayCountPrefixSize+(count*8))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint64(buf[ArrayCountPrefixSize+i*8:], uint64(v))
		}
		return count, buf, nil

	case []float64:
		buf := make([]byte, ArrayCountPrefixSize+(count*8))
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		for i, v := range sl {
			binary.BigEndian.PutUint64(buf[ArrayCountPrefixSize+i*8:], math.Float64bits(v))
		}
		return count, buf, nil

	// --- Variable-Length Sequences ---
	case []string:
		totalSize := 0
		for _, v := range sl {
			totalSize += StrOrByteLenPrefixSize + len(v)
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			binary.BigEndian.PutUint32(buf[dynOff:], uint32(len(v)))
			dynOff += StrOrByteLenPrefixSize
			copy(buf[dynOff:], v)
			dynOff += len(v)
		}
		return count, buf, nil

	case [][]byte:
		totalSize := 0
		for _, v := range sl {
			totalSize += StrOrByteLenPrefixSize + len(v)
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			binary.BigEndian.PutUint32(buf[dynOff:], uint32(len(v)))
			dynOff += StrOrByteLenPrefixSize
			copy(buf[dynOff:], v)
			dynOff += len(v)
		}
		return count, buf, nil

	case []*NoPaddingMsg:
		totalSize := 0
		for i, v := range sl {
			if v == nil {
				return 0, nil, fmt.Errorf("cannot serialize nil *NoPaddingMsg element at index %d", i)
			}
			totalSize += v.Size()
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			b, err := v.Marshal()
			if err != nil {
				return 0, nil, fmt.Errorf("failed to serialize *NoPaddingMsg element: %w", err)
			}
			copy(buf[dynOff:], b)
			dynOff += len(b)
		}
		return count, buf, nil

	case []*SmallFieldsMsg:
		totalSize := 0
		for i, v := range sl {
			if v == nil {
				return 0, nil, fmt.Errorf("cannot serialize nil *SmallFieldsMsg element at index %d", i)
			}
			totalSize += v.Size()
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			b, err := v.Marshal()
			if err != nil {
				return 0, nil, fmt.Errorf("failed to serialize *SmallFieldsMsg element: %w", err)
			}
			copy(buf[dynOff:], b)
			dynOff += len(b)
		}
		return count, buf, nil

	case []*MixedSizeMsg:
		totalSize := 0
		for i, v := range sl {
			if v == nil {
				return 0, nil, fmt.Errorf("cannot serialize nil *MixedSizeMsg element at index %d", i)
			}
			totalSize += v.Size()
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			b, err := v.Marshal()
			if err != nil {
				return 0, nil, fmt.Errorf("failed to serialize *MixedSizeMsg element: %w", err)
			}
			copy(buf[dynOff:], b)
			dynOff += len(b)
		}
		return count, buf, nil

	case []*AlignedMsg:
		totalSize := 0
		for i, v := range sl {
			if v == nil {
				return 0, nil, fmt.Errorf("cannot serialize nil *AlignedMsg element at index %d", i)
			}
			totalSize += v.Size()
		}
		buf := make([]byte, ArrayCountPrefixSize+totalSize)
		binary.BigEndian.PutUint16(buf[0:], uint16(count))
		dynOff := ArrayCountPrefixSize
		for _, v := range sl {
			b, err := v.Marshal()
			if err != nil {
				return 0, nil, fmt.Errorf("failed to serialize *AlignedMsg element: %w", err)
			}
			copy(buf[dynOff:], b)
			dynOff += len(b)
		}
		return count, buf, nil

	default:
		var zero T
		return 0, nil, fmt.Errorf("unsupported primitive type: %T", zero)
	}
}

func readThreeDimensionalSlice[T any](r io.Reader) ([][][]T, error) {
	count, err := readUint16(r)
	if err != nil {
		return nil, fmt.Errorf("failed to read 3D array count: %w", err)
	}

	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	// Read the 3D array elements
	slice := make([][][]T, count)
	for i := 0; i < int(count); i++ {
		innerSlice, err := readTwoDimensionalSlice[T](r)
		if err != nil {
			return nil, fmt.Errorf("failed to read 3D array element at index %d: %w", i, err)
		}

		slice[i] = innerSlice
	}
	return slice, nil
}

func readTwoDimensionalSlice[T any](r io.Reader) ([][]T, error) {
	count, err := readUint16(r)
	if err != nil {
		return nil, fmt.Errorf("failed to read 2D array count: %w", err)
	}

	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	// Read the 2D array elements
	slice := make([][]T, count)
	for i := 0; i < int(count); i++ {
		innerSlice, err := readOneDimensionalSlice[T](r)
		if err != nil {
			return nil, fmt.Errorf("failed to read 2D array element at index %d: %w", i, err)
		}

		slice[i] = innerSlice
	}
	return slice, nil
}

func readOneDimensionalSlice[T any](r io.Reader) ([]T, error) {
	count, err := readUint16(r)
	if err != nil {
		return nil, fmt.Errorf("failed to read 1D array count: %w", err)
	}

	if count == 0 {
		return []T{}, nil
	}

	if count > MaxArrayElements {
		return nil, fmt.Errorf("array length %d exceeds MaxArrayElements", count)
	}

	slice := make([]T, count)

	// Read the 1D array elements
	switch sl := any(slice).(type) {
	// --- 1-Byte Primitives ---
	case []uint8:
		if _, err := io.ReadFull(r, sl); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
	case []int8:
		data := make([]byte, count)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int8(data[i])
		}
	case []bool:
		data := make([]byte, count)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = data[i] != 0
		}

	// --- 2-Byte Primitives ---
	case []uint16:
		data := make([]byte, count*2)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = binary.BigEndian.Uint16(data[i*2:])
		}
	case []int16:
		data := make([]byte, count*2)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int16(binary.BigEndian.Uint16(data[i*2:]))
		}

	// --- 4-Byte Primitives ---
	case []uint32:
		data := make([]byte, count*4)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = binary.BigEndian.Uint32(data[i*4:])
		}
	case []int32:
		data := make([]byte, count*4)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int32(binary.BigEndian.Uint32(data[i*4:]))
		}
	case []float32:
		data := make([]byte, count*4)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = math.Float32frombits(binary.BigEndian.Uint32(data[i*4:]))
		}

	// --- 8-Byte Primitives ---
	case []uint64:
		data := make([]byte, count*8)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = binary.BigEndian.Uint64(data[i*8:])
		}
	case []int64:
		data := make([]byte, count*8)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = int64(binary.BigEndian.Uint64(data[i*8:]))
		}
	case []float64:
		data := make([]byte, count*8)
		if _, err := io.ReadFull(r, data); err != nil {
			return nil, fmt.Errorf("failed to read array elements: %w", err)
		}
		for i := range sl {
			sl[i] = math.Float64frombits(binary.BigEndian.Uint64(data[i*8:]))
		}

	// --- Variable-Length Sequences ---
	case []string:
		for i := range sl {
			length, err := readUint32(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read string length at index %d: %w", i, err)
			}
			if length > MaxAllowedPacket {
				return nil, fmt.Errorf("string length %d exceeds MaxAllowedPacket at index %d", length, i)
			}

			buf := make([]byte, length)
			if _, err := io.ReadFull(r, buf); err != nil {
				return nil, fmt.Errorf("failed to read string data at index %d: %w", i, err)
			}
			sl[i] = string(buf)
		}
	case [][]byte:
		for i := range sl {
			length, err := readUint32(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read []byte length at index %d: %w", i, err)
			}
			if length > MaxAllowedPacket {
				return nil, fmt.Errorf("[]byte length %d exceeds MaxAllowedPacket at index %d", length, i)
			}

			buf := make([]byte, length)
			if _, err := io.ReadFull(r, buf); err != nil {
				return nil, fmt.Errorf("failed to read []byte data at index %d: %w", i, err)
			}
			sl[i] = buf
		}

	case []*NoPaddingMsg:
		for i := range sl {
			typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read frame header for *NoPaddingMsg at index %d: %w", i, err)
			}

			var msg NoPaddingMsg
			if typeID != msg.MessageTypeID() {
				return nil, fmt.Errorf("unexpected type ID %d for NoPaddingMsg, expected %d", typeID, msg.MessageTypeID())
			}

			NoPaddingMsg_reader := io.LimitReader(r, int64(overallPayloadLen))
			if err := msg.Unmarshal(NoPaddingMsg_reader, fixedPayloadLen, overallPayloadLen); err != nil {
				return nil, fmt.Errorf("failed to deserialize NoPaddingMsg: %w", err)
			}
			sl[i] = &msg
		}

	case []*SmallFieldsMsg:
		for i := range sl {
			typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read frame header for *SmallFieldsMsg at index %d: %w", i, err)
			}

			var msg SmallFieldsMsg
			if typeID != msg.MessageTypeID() {
				return nil, fmt.Errorf("unexpected type ID %d for SmallFieldsMsg, expected %d", typeID, msg.MessageTypeID())
			}

			SmallFieldsMsg_reader := io.LimitReader(r, int64(overallPayloadLen))
			if err := msg.Unmarshal(SmallFieldsMsg_reader, fixedPayloadLen, overallPayloadLen); err != nil {
				return nil, fmt.Errorf("failed to deserialize SmallFieldsMsg: %w", err)
			}
			sl[i] = &msg
		}

	case []*MixedSizeMsg:
		for i := range sl {
			typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read frame header for *MixedSizeMsg at index %d: %w", i, err)
			}

			var msg MixedSizeMsg
			if typeID != msg.MessageTypeID() {
				return nil, fmt.Errorf("unexpected type ID %d for MixedSizeMsg, expected %d", typeID, msg.MessageTypeID())
			}

			MixedSizeMsg_reader := io.LimitReader(r, int64(overallPayloadLen))
			if err := msg.Unmarshal(MixedSizeMsg_reader, fixedPayloadLen, overallPayloadLen); err != nil {
				return nil, fmt.Errorf("failed to deserialize MixedSizeMsg: %w", err)
			}
			sl[i] = &msg
		}

	case []*AlignedMsg:
		for i := range sl {
			typeID, fixedPayloadLen, overallPayloadLen, err := ReadMessageFrame(r)
			if err != nil {
				return nil, fmt.Errorf("failed to read frame header for *AlignedMsg at index %d: %w", i, err)
			}

			var msg AlignedMsg
			if typeID != msg.MessageTypeID() {
				return nil, fmt.Errorf("unexpected type ID %d for AlignedMsg, expected %d", typeID, msg.MessageTypeID())
			}

			AlignedMsg_reader := io.LimitReader(r, int64(overallPayloadLen))
			if err := msg.Unmarshal(AlignedMsg_reader, fixedPayloadLen, overallPayloadLen); err != nil {
				return nil, fmt.Errorf("failed to deserialize AlignedMsg: %w", err)
			}
			sl[i] = &msg
		}

	default:
		return nil, fmt.Errorf("unsupported array element type")
	}

	return slice, nil
}

func getElementType(item any) (uint16, error) {
	switch item.(type) {
	case bool:
		return TagBool, nil
	case int8:
		return TagInt8, nil
	case uint8:
		return TagUint8, nil
	case int16:
		return TagInt16, nil
	case uint16:
		return TagUint16, nil
	case int32:
		return TagInt32, nil
	case uint32:
		return TagUint32, nil
	case float32:
		return TagFloat32, nil
	case int64:
		return TagInt64, nil
	case uint64:
		return TagUint64, nil
	case float64:
		return TagFloat64, nil
	case string:
		return TagString, nil
	case []byte:
		return TagBytes, nil

	case *NoPaddingMsg:
		return TagNoPaddingMsg, nil

	case *SmallFieldsMsg:
		return TagSmallFieldsMsg, nil

	case *MixedSizeMsg:
		return TagMixedSizeMsg, nil

	case *AlignedMsg:
		return TagAlignedMsg, nil

	default:
		return 0, fmt.Errorf("unsupported type: %T", item)
	}
}

func readUint32(r io.Reader) (uint32, error) {
	var buf [4]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return binary.BigEndian.Uint32(buf[:]), nil
}

func readUint16(r io.Reader) (uint16, error) {
	var buf [2]byte
	if _, err := io.ReadFull(r, buf[:]); err != nil {
		return 0, err
	}
	return binary.BigEndian.Uint16(buf[:]), nil
}
